<a href="https://colab.research.google.com/github/Andoniadou-Lab/consensus_pituitary_atlas/blob/main/Curation_flag_metadata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mounting Drive onto colab

In [ ]:
#mount drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
pip install scanpy

Collecting scanpy
  Downloading scanpy-1.12-py3-none-any.whl.metadata (8.4 kB)
Collecting anndata>=0.10.8 (from scanpy)
  Downloading anndata-0.12.10-py3-none-any.whl.metadata (9.9 kB)
Collecting fast-array-utils>=1.2.1 (from fast-array-utils[accel,sparse]>=1.2.1->scanpy)
  Downloading fast_array_utils-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: h5py>=3.11 in /usr/local/lib/python3.12/dist-packages (from scanpy) (3.15.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from scanpy) (1.5.3)
Collecting legacy-api-wrap>=1.5 (from scanpy)
  Downloading legacy_api_wrap-1.5-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: matplotlib>=3.9 in /usr/local/lib/python3.12/dist-packages (from scanpy) (3.10.0)
Requirement already satisfied: natsort in /usr/local/lib/python3.12/dist-packages (from scanpy) (8.4.0)
Requirement already satisfied: networkx>=2.8.8 in /usr/local/lib/python3.12/dist-packages (from scanpy) (3.6.1)
Requirement already satisfied: numba>=0.60 in /usr/local/lib/python3.12/dist-packages (from scanpy) (0.60.0)
Requirement already satisfied: numpy>=2 in /usr/local/lib/python3.12/dist-packages (from scanpy) (2.0.2)
Requirement already satisfied: packaging>=25 in /usr/local/lib/python3.12/dist-packages (from scanpy) (26.0)
Requirement already satisfied: pandas>=2.2.2 in /usr/local/lib/python3.12/dist-packages (from scanpy) (2.2.2)
Requirement already satisfied: patsy in /usr/local/lib/python3.12/dist-packages (from scanpy) (1.0.2)
Requirement already satisfied: pynndescent>=0.5.13 in /usr/local/lib/python3.12/dist-packages (from scanpy) (0.6.0)
Requirement already satisfied: scikit-learn>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from scanpy) (1.6.1)
Requirement already satisfied: scipy>=1.13 in /usr/local/lib/python3.12/dist-packages (from scanpy) (1.16.3)
Requirement already satisfied: seaborn>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from scanpy) (0.13.2)
Collecting session-info2 (from scanpy)
  Downloading session_info2-0.4-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: statsmodels>=0.14.5 in /usr/local/lib/python3.12/dist-packages (from scanpy) (0.14.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from scanpy) (4.67.3)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from scanpy) (4.15.0)
Requirement already satisfied: umap-learn>=0.5.7 in /usr/local/lib/python3.12/dist-packages (from scanpy) (0.5.11)
Collecting array-api-compat>=1.7.1 (from anndata>=0.10.8->scanpy)
  Downloading array_api_compat-1.14.0-py3-none-any.whl.metadata (2.5 kB)
Collecting zarr!=3.0.*,>=2.18.7 (from anndata>=0.10.8->scanpy)
  Downloading zarr-3.1.5-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9->scanpy) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9->scanpy) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9->scanpy) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9->scanpy) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9->scanpy) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9->scanpy) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.9->scanpy) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.60->scanpy) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.2->scanpy) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.2->scanpy) (2025.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4.2->scanpy) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.9->scanpy) (1.17.0)
Collecting donfig>=0.8 (from zarr!=3.0.*,>=2.18.7->anndata>=0.10.8->scanpy)
  Downloading donfig-0.8.1.post1-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: google-crc32c>=1.5 in /usr/local/lib/python3.12/dist-packages (from zarr!=3.0.*,>=2.18.7->anndata>=0.10.8->scanpy) (1.8.0)
Collecting numcodecs>=0.14 (from zarr!=3.0.*,>=2.18.7->anndata>=0.10.8->scanpy)
  Downloading numcodecs-0.16.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from donfig>=0.8->zarr!=3.0.*,>=2.18.7->anndata>=0.10.8->scanpy) (6.0.3)
Downloading scanpy-1.12-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 25.1 MB/s eta 0:00:00
Downloading anndata-0.12.10-py3-none-any.whl (176 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.6/176.6 kB 14.4 MB/s eta 0:00:00
Downloading fast_array_utils-1.3.1-py3-none-any.whl (36 kB)
Downloading legacy_api_wrap-1.5-py3-none-any.whl (10 kB)
Downloading session_info2-0.4-py3-none-any.whl (17 kB)
Downloading array_api_compat-1.14.0-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.1/60.1 kB 4.9 MB/s eta 0:00:00
Downloading zarr-3.1.5-py3-none-any.whl (284 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 284.1/284.1 kB 22.6 MB/s eta 0:00:00
Downloading donfig-0.8.1.post1-py3-none-any.whl (21 kB)
Downloading numcodecs-0.16.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (9.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 113.1 MB/s eta 0:00:00
Installing collected packages: session-info2, numcodecs, legacy-api-wrap, fast-array-utils, donfig, array-api-compat, zarr, anndata, scanpy
Successfully installed anndata-0.12.10 array-api-compat-1.14.0 donfig-0.8.1.post1 fast-array-utils-1.3.1 legacy-api-wrap-1.5 numcodecs-0.16.5 scanpy-1.12 session-info2-0.4 zarr-3.1.5

In [ ]:
import pandas as pd
df = pd.read_excel('/content/drive/MyDrive/pituitary_atlas/source_table/pituitary_atlas.xlsx')

# Number of datasets

In [ ]:
#remove where Author is Rebboah et al. or Kover et al.
df = df[~(df["Author"].str.startswith("Rebboah"))]
df = df[~(df["Author"].str.startswith("Kover"))]
df

,GEO,SRA_ID,Name,Conditions,Normal,Background,Sorted,Author,DOI,Age,...,filtering_junk,median_cellassign_prob,most_recent_workflow,n_cells,processed_atac,passed_qc_tcc,tcc_pseudobulked,Core,Notes 1,Notes 2
0,GSM4594333,SRX8489818,M-Pituitary,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,1.0,1.0,v_0.01,1278,0.0,1.0,v_0.01,1,NaN,NaN
1,GSM4594334,SRX8489819,FM_Pit_1-1,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,1.0,1.0,v_0.01,8236,0.0,1.0,v_0.01,1,NaN,NaN
2,GSM4594335,SRX8489820,FM_Pit_1-2,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,1.0,1.0,v_0.01,7092,0.0,1.0,v_0.01,1,GEO name should be FM_Pit_1-2,NaN
3,GSM4594336,SRX8489821,MM_Pit_4-1,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,1.0,1.0,v_0.01,1755,0.0,1.0,v_0.01,1,NaN,NaN
4,GSM4594337,SRX8489822,MM_Pit_1v2,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,1.0,1.0,v_0.01,416,0.0,1.0,v_0.01,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,GSM9302173,SRX31166359,"pituitary, HFD_2",high_fat_diet,0,Unclear,0,Guo et al. (2025),NaN,16 weeks,...,1.0,1.0,v_0.01,7193,NaN,NaN,NaN,1,NaN,NaN
279,GSM9302174,SRX31166360,"pituitary, ND_1",normal,1,Unclear,0,Guo et al. (2025),NaN,16 weeks,...,1.0,1.0,v_0.01,7298,NaN,NaN,NaN,1,NaN,NaN
280,GSM9302175,SRX31166361,"pituitary, ND_2",normal,1,Unclear,0,Guo et al. (2025),NaN,16 weeks,...,1.0,1.0,v_0.01,7530,NaN,NaN,NaN,1,in previous version Normal was switched as 0 w...,NaN
281,GSM9459038,SRX31798127,POMC-WT,POMC-WT,1,C57BL/6J,0,Sochodolsky et al. (2026),NaN,386 days,...,1.0,1.0,v_0.01,8083,NaN,NaN,NaN,1,NaN,NaN
282,GSM9459037,SRX31798126,POMC-KO,POMC-KO,0,C57BL/6J,0,Sochodolsky et al. (2026),NaN,376 and 386 days,...,1.0,1.0,v_0.01,7038,NaN,NaN,NaN,1,NaN,NaN

# Number of publications before Rebboah and Kover

In [ ]:
df["Author"].nunique()

38

# Sample wrong sex

In [ ]:
df[df['Sample_wrong_sex']==1][["Author","SRA_ID","Sex","Comp_sex"]]

                   Author       SRA_ID     Sex  Comp_sex
60       Li et al. (2023)  SRX21170825  female       1.0
66    Miles et al. (2023)  SRX21986110  female       1.0
68    Miles et al. (2023)  SRX21986112    male       0.0
258  Cheung et al. (2025)  SRX29174028  Female       1.0
259  Cheung et al. (2025)  SRX29174029    Male       0.0

# Sample missing sex

In [ ]:
df[df['Sample_missing_sex']==1][["Author","SRA_ID","Sex","Comp_sex"]]

                           Author       SRA_ID      Sex  Comp_sex
101     Moncho-Amor et al. (2021)   SRX8497092        ?       1.0
102     Moncho-Amor et al. (2021)   SRX8497093        ?       0.0
103     Moncho-Amor et al. (2021)   SRX8497094        ?       1.0
104         Bastedo et al. (2024)   SRX9637224        ?       1.0
119  Martinez-Mayer et al. (2024)  SRX22219345        ?       0.0
120  Martinez-Mayer et al. (2024)  SRX22219346        ?       1.0
183      Brinkmeier et al. (2025)  SRX26708357  unclear       0.0
261             Wei et al. (2025)  SRX21168593        ?       0.0
262             Wei et al. (2025)  SRX21168594        ?       0.0
263             Wei et al. (2025)  SRX21168595        ?       1.0
264             Wei et al. (2025)  SRX21168596        ?       1.0
277             Guo et al. (2025)  SRX31166358        ?       1.0
278             Guo et al. (2025)  SRX31166359        ?       1.0
279             Guo et al. (2025)  SRX31166360        ?       1.0
280             Guo et al. (2025)  SRX31166361        ?       1.0

# Sample wrong kit

In [ ]:
df[df['Sample_wrong_barcode_kit']==1][["Author","Notes 1","10X version"]]

,Author,Notes 1,10X version
54,Laporte et al. (2022),had to correct from v2 to v3 - Not actually mixed,10XV3
55,Laporte et al. (2022),had to correct from v2 to v3 - Not actually mixed,10XV3
56,Laporte et al. (2022),had to correct from v2 to v3 - Not actually mixed,10XV3
57,Laporte et al. (2022),had to correct from v2 to v3 - Not actually mixed,10XV3
58,Li et al. (2023),had to correct from v2 to v3,10XV3
59,Li et al. (2023),had to correct from v2 to v3,10XV3
60,Li et al. (2023),had to correct from v2 to v3,10XV3
92,Rizzoti et al. (2023),Incorrectly v3 in paper,10XV2
109,Masser et al. (2024),"V2 actually, not V3",10XV2
110,Masser et al. (2024),"V2 actually, not V3",10XV2
119,Martinez-Mayer et al. (2024),"V2 actually, not V3 ; no sex",10XV2
162,Huang et al. (2024),Incorrectly v2 on GEO,10XV3
163,Huang et al. (2024),Incorrectly v2 on GEO,10XV3

# Switched up

In [ ]:
df[df['Sample_switched_up']==1]

,GEO,SRA_ID,Name,Conditions,Normal,Background,Sorted,Author,DOI,Age,...,filtering_junk,median_cellassign_prob,most_recent_workflow,n_cells,processed_atac,passed_qc_tcc,tcc_pseudobulked,Core,Notes 1,Notes 2
97,GSM6212046,SRX15581370,YFP FAC-sorted cells from Tshb-Cre; R26-LSL-eYFP,sorted_thyrotropes,1,missing,1,Cheung et al. (2023),10.1210/endocr/bqad076,7,...,1.0,1.0,v_0.01,4257,0.0,1.0,v_0.01,1,This should be SRX15581371 - celltype proporti...,NaN
98,GSM6212047,SRX15581371,unsorted total pituitary cells from R26-LSL-eYFP,normal,1,missing,0,Cheung et al. (2023),10.1210/endocr/bqad076,7,...,1.0,1.0,v_0.01,4430,0.0,1.0,v_0.01,1,Potentially mixed sex sample. This should be S...,NaN

# Minimal n is 1

In [ ]:
print(df['Author'].unique())
print(df['Author'].nunique())

['Ruf-Zamojski et al. (2021)' 'Cheung et al. (2018)'
 'Mayran et al. (2019)' 'Chen et al. (2020)' 'Ho et al. (2020)'
 'Lopez et al. (2021)' 'Ruggiero-Ruff et al. (2024)'
 'Vennekens et al. (2021)' 'Laporte et al. (2022)' 'Li et al. (2023)'
 'Miles et al. (2023)' 'Bohaczuk et al. (2021)' 'Schang et al. (2022)'
 'Lin et al. (2022)' 'Rizzoti et al. (2023)' 'Cheung et al. (2023)'
 'Allensworth-James et al. (2021)' 'Moncho-Amor et al. (2021)'
 'Bastedo et al. (2024)' 'Zhang et al. (2024)' 'Cheung et al. (2020)'
 'Masser et al. (2024)' 'Qian et al. (2024)'
 'Martinez-Mayer et al. (2024)' 'Kang et al. (2023)'
 'Sheridan et al. (2025)' 'Khetchoumian et al. (2024)'
 'Wang et al. (2024)' 'Huang et al. (2024)' 'De Vriendt et al. (2025)'
 'Ongaro et al. (2025)' 'Brinkmeier et al. (2025)' 'Miles et al. (2025)'
 'Cheung et al. (2025)' 'Wei et al. (2025)' 'Jin et al. (2025)'
 'Guo et al. (2025)' 'Sochodolsky et al. (2026)']
38

In [ ]:
print(df[df['Study_minimum_n']<2]['Author'].unique())
print(df[df['Study_minimum_n']<2]['Author'].nunique())
print(df['Author'].nunique())

['Mayran et al. (2019)' 'Ho et al. (2020)' 'Lopez et al. (2021)'
 'Li et al. (2023)' 'Miles et al. (2023)' 'Lin et al. (2022)'
 'Rizzoti et al. (2023)' 'Cheung et al. (2023)'
 'Moncho-Amor et al. (2021)' 'Bastedo et al. (2024)' 'Zhang et al. (2024)'
 'Cheung et al. (2020)' 'Masser et al. (2024)'
 'Martinez-Mayer et al. (2024)' 'Kang et al. (2023)'
 'Sheridan et al. (2025)' 'Khetchoumian et al. (2024)'
 'Huang et al. (2024)' 'De Vriendt et al. (2025)'
 'Brinkmeier et al. (2025)' 'Cheung et al. (2025)'
 'Sochodolsky et al. (2026)']
22
38

In [ ]:
#turn these to integers based on the first number character 'Study_Seurat_version', 'Study_CR_version' using regex
df['Study_Seurat_version_int'] = df['Study_Seurat_version'].str.extract('(\d+)').astype('Int64')
df['Study_CR_version_int'] = df['Study_CR_version'].str.extract('(\d+)').astype('Int64')

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipython-input-6742/3412223779.py:2: SyntaxWarning: invalid escape sequence '\d'
  df['Study_Seurat_version_int'] = df['Study_Seurat_version'].str.extract('(\d+)').astype('Int64')
/tmp/ipython-input-6742/3412223779.py:3: SyntaxWarning: invalid escape sequence '\d'
  df['Study_CR_version_int'] = df['Study_CR_version'].str.extract('(\d+)').astype('Int64')

# Number of samples with outdated Cellranger

In [ ]:
#dropna
df_versions = df.dropna(subset=['Study_CR_version_int'])

df_versions ['Study_CR_version_int']

df_versions ['Author_year'] =df_versions ['Author'].str.extract('(\d{4})')
df_versions ['Author_year']


#print where year is > 2023 and ['Study_CR_version_int'] < 5
print(df_versions [(df_versions ['Author_year'].astype('Int64') > 2023) & (df_versions ['Study_CR_version_int'] < 7) & (df_versions ['Study_CR_version_int'] > 2)]['Author'].unique())

#print where year is > 2023 and ['Study_CR_version_int'] < 5
print(df_versions [(df_versions ['Author_year'].astype('Int64') > 2023) & (df_versions ['Study_CR_version_int'] < 7) & (df_versions ['Study_CR_version_int'] > 2)]['Author'].nunique())

['Ruggiero-Ruff et al. (2024)' 'Masser et al. (2024)'
 'Martinez-Mayer et al. (2024)' 'Sheridan et al. (2025)'
 'Khetchoumian et al. (2024)' 'Huang et al. (2024)'
 'De Vriendt et al. (2025)' 'Miles et al. (2025)' 'Cheung et al. (2025)'
 'Wei et al. (2025)']
10

<>:6: SyntaxWarning: invalid escape sequence '\d'
<>:6: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipython-input-6742/1791246390.py:6: SyntaxWarning: invalid escape sequence '\d'
  df_versions ['Author_year'] =df_versions ['Author'].str.extract('(\d{4})')
/tmp/ipython-input-6742/1791246390.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_versions ['Author_year'] =df_versions ['Author'].str.extract('(\d{4})')

# Number of samples with outdated Seurat

In [ ]:
#dropna
df_versions = df.dropna(subset=['Study_Seurat_version_int'])

df_versions ['Study_Seurat_version_int']

df_versions ['Author_year'] =df_versions ['Author'].str.extract('(\d{4})')
df_versions ['Author_year']


#print where year is > 2023 and ['Study_CR_version_int'] < 5
print(df_versions [(df_versions ['Author_year'].astype('Int64') > 2023) & (df_versions ['Study_Seurat_version_int'] < 5) & (df_versions ['Study_CR_version_int'] > 2)]['Author'].unique())

#print where year is > 2023 and ['Study_CR_version_int'] < 5
print(df_versions [(df_versions ['Author_year'].astype('Int64') > 2023) & (df_versions ['Study_Seurat_version_int'] < 5) & (df_versions ['Study_CR_version_int'] > 2)]['Author'].nunique())

['Ruggiero-Ruff et al. (2024)' 'Masser et al. (2024)'
 'Martinez-Mayer et al. (2024)' 'Sheridan et al. (2025)'
 'Khetchoumian et al. (2024)' 'Huang et al. (2024)'
 'De Vriendt et al. (2025)' 'Brinkmeier et al. (2025)']
8

<>:6: SyntaxWarning: invalid escape sequence '\d'
<>:6: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipython-input-6742/1287390759.py:6: SyntaxWarning: invalid escape sequence '\d'
  df_versions ['Author_year'] =df_versions ['Author'].str.extract('(\d{4})')
/tmp/ipython-input-6742/1287390759.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_versions ['Author_year'] =df_versions ['Author'].str.extract('(\d{4})')

In [ ]:
#how many are control

In [ ]:
df[df["Normal"]==1]

,GEO,SRA_ID,Name,Conditions,Normal,Background,Sorted,Author,DOI,Age,...,filtering_junk,median_cellassign_prob,most_recent_workflow,n_cells,processed_atac,passed_qc_tcc,tcc_pseudobulked,Core,Notes 1,Notes 2
0,GSM4594333,SRX8489818,M-Pituitary,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,1.0,1.0,v_0.01,1278,0.0,1.0,v_0.01,1,NaN,NaN
1,GSM4594334,SRX8489819,FM_Pit_1-1,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,1.0,1.0,v_0.01,8236,0.0,1.0,v_0.01,1,NaN,NaN
2,GSM4594335,SRX8489820,FM_Pit_1-2,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,1.0,1.0,v_0.01,7092,0.0,1.0,v_0.01,1,GEO name should be FM_Pit_1-2,NaN
3,GSM4594336,SRX8489821,MM_Pit_4-1,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,1.0,1.0,v_0.01,1755,0.0,1.0,v_0.01,1,NaN,NaN
4,GSM4594337,SRX8489822,MM_Pit_1v2,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,1.0,1.0,v_0.01,416,0.0,1.0,v_0.01,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,GSM9301719,SRX31143268,WildType_Mouse1,normal,1,C57BL/6,0,Jin et al. (2025),NaN,8 weeks,...,NaN,NaN,v_0.01,2506,NaN,NaN,NaN,1,NaN,NaN
270,GSM9301722,SRX31143271,WildType_Mouse4,normal,1,C57BL/6,0,Jin et al. (2025),NaN,8 weeks,...,NaN,NaN,v_0.01,6465,NaN,NaN,NaN,1,NaN,NaN
279,GSM9302174,SRX31166360,"pituitary, ND_1",normal,1,Unclear,0,Guo et al. (2025),NaN,16 weeks,...,1.0,1.0,v_0.01,7298,NaN,NaN,NaN,1,NaN,NaN
280,GSM9302175,SRX31166361,"pituitary, ND_2",normal,1,Unclear,0,Guo et al. (2025),NaN,16 weeks,...,1.0,1.0,v_0.01,7530,NaN,NaN,NaN,1,in previous version Normal was switched as 0 w...,NaN
281,GSM9459038,SRX31798127,POMC-WT,POMC-WT,1,C57BL/6J,0,Sochodolsky et al. (2026),NaN,386 days,...,1.0,1.0,v_0.01,8083,NaN,NaN,NaN,1,NaN,NaN

In [ ]:
df

,GEO,SRA_ID,Name,Conditions,Normal,Background,Sorted,Author,DOI,Age,...,filtering_junk,median_cellassign_prob,most_recent_workflow,n_cells,processed_atac,passed_qc_tcc,tcc_pseudobulked,Core,Notes 1,Notes 2
0,GSM4594333,SRX8489818,M-Pituitary,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,1.0,1.0,v_0.01,1278,0.0,1.0,v_0.01,1,NaN,NaN
1,GSM4594334,SRX8489819,FM_Pit_1-1,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,1.0,1.0,v_0.01,8236,0.0,1.0,v_0.01,1,NaN,NaN
2,GSM4594335,SRX8489820,FM_Pit_1-2,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,1.0,1.0,v_0.01,7092,0.0,1.0,v_0.01,1,GEO name should be FM_Pit_1-2,NaN
3,GSM4594336,SRX8489821,MM_Pit_4-1,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,1.0,1.0,v_0.01,1755,0.0,1.0,v_0.01,1,NaN,NaN
4,GSM4594337,SRX8489822,MM_Pit_1v2,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,1.0,1.0,v_0.01,416,0.0,1.0,v_0.01,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,GSM9302173,SRX31166359,"pituitary, HFD_2",high_fat_diet,0,Unclear,0,Guo et al. (2025),NaN,16 weeks,...,1.0,1.0,v_0.01,7193,NaN,NaN,NaN,1,NaN,NaN
279,GSM9302174,SRX31166360,"pituitary, ND_1",normal,1,Unclear,0,Guo et al. (2025),NaN,16 weeks,...,1.0,1.0,v_0.01,7298,NaN,NaN,NaN,1,NaN,NaN
280,GSM9302175,SRX31166361,"pituitary, ND_2",normal,1,Unclear,0,Guo et al. (2025),NaN,16 weeks,...,1.0,1.0,v_0.01,7530,NaN,NaN,NaN,1,in previous version Normal was switched as 0 w...,NaN
281,GSM9459038,SRX31798127,POMC-WT,POMC-WT,1,C57BL/6J,0,Sochodolsky et al. (2026),NaN,386 days,...,1.0,1.0,v_0.01,8083,NaN,NaN,NaN,1,NaN,NaN
282,GSM9459037,SRX31798126,POMC-KO,POMC-KO,0,C57BL/6J,0,Sochodolsky et al. (2026),NaN,376 and 386 days,...,1.0,1.0,v_0.01,7038,NaN,NaN,NaN,1,NaN,NaN

In [ ]:
df[df["Normal"]!=1]["Conditions"].unique()
#but remove normal, and organoid and wls

array(['mt/hGRF', 'stressed', 'high_fat_diet',
       'GHCre/+;R26iDTR/+ ablation', 'GATAcKO', 'SF1_KO',
       'adrenalectomy_sox9_sorted', 'gonadectomy_sox9_sorted', 'S2CK',
       'P27NULL', 'Hesx1Cre_dnRAR', 'Prop1 df/df', 'IREPKO',
       'Pituitary_TpitHT', 'Pituitary_TpitKO', 'p25OE', 'normal',
       'Acvr1bflox/flox;GnrhrCre/+ (Alk4-cKO)',
       'Tgfbr1flox/flox;GnrhrCre/+ (Alk5-cKO)', 'Nxn -/- ',
       'FVB.129P2-Pde6b + Tyr c-ch/AntJ; Tg(Gh1-cre)bKnmn (+/-); Leprtm1Rck (fl/fl)',
       'Fshb-Enh2-KO', 'IgG-treated', 'Bimagrumab-treated', 'POMC-KO'],
      dtype=object)

In [ ]:
df[df["Normal"]!=1]["Conditions"].nunique()

25

In [ ]:
len(['mt/hGRF', 'stressed', 'high_fat_diet',
       'GHCre/+;R26iDTR/+ ablation', 'GATAcKO', 'SF1_KO',
       'adrenalectomy_sox9_sorted', 'gonadectomy_sox9_sorted', 'S2CK',
       'P27NULL', 'Hesx1Cre_dnRAR', 'Prop1 df/df', 'IREPKO',
       'Pituitary_TpitHT', 'Pituitary_TpitKO', 'p25OE',
       'Acvr1bflox/flox;GnrhrCre/+ (Alk4-cKO)',
       'Tgfbr1flox/flox;GnrhrCre/+ (Alk5-cKO)', 'Nxn -/- ',
       'FVB.129P2-Pde6b + Tyr c-ch/AntJ; Tg(Gh1-cre)bKnmn (+/-); Leprtm1Rck (fl/fl)',
       'Fshb-Enh2-KO', 'IgG-treated', 'Bimagrumab-treated', 'POMC-KO'])

24

In [ ]:
conditions = df[df["Normal"]!=1]["Conditions"].unique()
#remove "normal"
conditions = [x for x in conditions if x not in ["normal"]]
print(len(conditions))

24

In [ ]:
df[df["Normal"]!=1]

,GEO,SRA_ID,Name,Conditions,Normal,Background,Sorted,Author,DOI,Age,...,filtering_junk,median_cellassign_prob,most_recent_workflow,n_cells,processed_atac,passed_qc_tcc,tcc_pseudobulked,Core,Notes 1,Notes 2
32,GSM4399745,SRX7874739,mt/hGRF transgenic-8wk-female,mt/hGRF,0,CD1,0,Ho et al. (2020),10.1007/s13238-020-00705-x,8 week,...,1.0,0.999969,v_0.01,1249,0.0,-1.0,NaN,1,NaN,NaN
41,GSM4914025,SRX9528565,Pituitary_Stress,stressed,0,C57BL/6,0,Lopez et al. (2021),10.1126/sciadv.abe4497,10 week,...,1.0,1.000000,v_0.01,4332,0.0,1.0,v_0.01,1,NaN,NaN
44,GSM7679946,SRX21241800,HFD 1,high_fat_diet,0,C57BL/6,0,Ruggiero-Ruff et al. (2024),10.1210/endocr/bqad196,16 week,...,1.0,1.000000,v_0.01,5297,0.0,1.0,v_0.01,1,NaN,NaN
45,GSM7679947,SRX21241801,HFD 2,high_fat_diet,0,C57BL/6,0,Ruggiero-Ruff et al. (2024),10.1210/endocr/bqad196,16 week,...,1.0,1.000000,v_0.01,6174,0.0,1.0,v_0.01,1,NaN,NaN
47,ERX4978538,ERX4978538,EXT037,GHCre/+;R26iDTR/+ ablation,0,C57BL/6,0,Vennekens et al. (2021),10.1073/pnas.2100052118,9-11 weeks,...,1.0,1.000000,v_0.01,3463,0.0,1.0,v_0.01,1,got fastq separately from arrayexpress,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,GSM9301727,SRX31143276,Bimagrumab-treated_Mouse14,Bimagrumab-treated,0,C57BL/6,0,Jin et al. (2025),NaN,9 weeks,...,NaN,NaN,v_0.01,6247,NaN,NaN,NaN,1,NaN,NaN
276,GSM9301728,SRX31143277,Bimagrumab-treated_Mouse15,Bimagrumab-treated,0,C57BL/6,0,Jin et al. (2025),NaN,9 weeks,...,NaN,NaN,v_0.01,7129,NaN,NaN,NaN,1,NaN,NaN
277,GSM9302172,SRX31166358,"pituitary, HFD_1",high_fat_diet,0,Unclear,0,Guo et al. (2025),NaN,16 weeks,...,1.0,1.000000,v_0.01,7192,NaN,NaN,NaN,1,NaN,NaN
278,GSM9302173,SRX31166359,"pituitary, HFD_2",high_fat_diet,0,Unclear,0,Guo et al. (2025),NaN,16 weeks,...,1.0,1.000000,v_0.01,7193,NaN,NaN,NaN,1,NaN,NaN
282,GSM9459037,SRX31798126,POMC-KO,POMC-KO,0,C57BL/6J,0,Sochodolsky et al. (2026),NaN,376 and 386 days,...,1.0,1.000000,v_0.01,7038,NaN,NaN,NaN,1,NaN,NaN

In [ ]:
#which samples have n_cells > 0
df[df["n_cells"]<300][["Author","10X version"]]

                Author 10X version
29  Chen et al. (2020)       10XV2
36    Ho et al. (2020)     DROPSEQ
37    Ho et al. (2020)     DROPSEQ

In [ ]:
df['10X version'].value_counts()

10X version
10XV3      130
10XV1       47
10XV2       30
DROPSEQ      8
Name: count, dtype: int64

# Number of perturbed datasets

In [ ]:
df[(df["Normal"]==0) & ~(df["Author"].str.startswith("Rebboah"))]

,GEO,SRA_ID,Name,Conditions,Normal,Background,Sorted,Author,DOI,Age,...,most_recent_workflow,n_cells,processed_atac,passed_qc_tcc,tcc_pseudobulked,Core,Notes 1,Notes 2,Study_Seurat_version_int,Study_CR_version_int
32,GSM4399745,SRX7874739,mt/hGRF transgenic-8wk-female,mt/hGRF,0,CD1,0,Ho et al. (2020),10.1007/s13238-020-00705-x,8 week,...,v_0.01,1249,0.0,-1.0,NaN,1,NaN,NaN,3,<NA>
41,GSM4914025,SRX9528565,Pituitary_Stress,stressed,0,C57BL/6,0,Lopez et al. (2021),10.1126/sciadv.abe4497,10 week,...,v_0.01,4332,0.0,1.0,v_0.01,1,NaN,NaN,1,2
44,GSM7679946,SRX21241800,HFD 1,high_fat_diet,0,C57BL/6,0,Ruggiero-Ruff et al. (2024),10.1210/endocr/bqad196,16 week,...,v_0.01,5297,0.0,1.0,v_0.01,1,NaN,NaN,4,6
45,GSM7679947,SRX21241801,HFD 2,high_fat_diet,0,C57BL/6,0,Ruggiero-Ruff et al. (2024),10.1210/endocr/bqad196,16 week,...,v_0.01,6174,0.0,1.0,v_0.01,1,NaN,NaN,4,6
47,ERX4978538,ERX4978538,EXT037,GHCre/+;R26iDTR/+ ablation,0,C57BL/6,0,Vennekens et al. (2021),10.1073/pnas.2100052118,9-11 weeks,...,v_0.01,3463,0.0,1.0,v_0.01,1,got fastq separately from arrayexpress,NaN,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,GSM9301727,SRX31143276,Bimagrumab-treated_Mouse14,Bimagrumab-treated,0,C57BL/6,0,Jin et al. (2025),NaN,9 weeks,...,v_0.01,6247,NaN,NaN,NaN,1,NaN,NaN,<NA>,<NA>
276,GSM9301728,SRX31143277,Bimagrumab-treated_Mouse15,Bimagrumab-treated,0,C57BL/6,0,Jin et al. (2025),NaN,9 weeks,...,v_0.01,7129,NaN,NaN,NaN,1,NaN,NaN,<NA>,<NA>
277,GSM9302172,SRX31166358,"pituitary, HFD_1",high_fat_diet,0,Unclear,0,Guo et al. (2025),NaN,16 weeks,...,v_0.01,7192,NaN,NaN,NaN,1,NaN,NaN,<NA>,<NA>
278,GSM9302173,SRX31166359,"pituitary, HFD_2",high_fat_diet,0,Unclear,0,Guo et al. (2025),NaN,16 weeks,...,v_0.01,7193,NaN,NaN,NaN,1,NaN,NaN,<NA>,<NA>
282,GSM9459037,SRX31798126,POMC-KO,POMC-KO,0,C57BL/6J,0,Sochodolsky et al. (2026),NaN,376 and 386 days,...,v_0.01,7038,NaN,NaN,NaN,1,NaN,NaN,<NA>,<NA>

# Which studies have no control?

In [ ]:
authors1 = df[(df["Normal"]==1)]['Author'].unique()

In [ ]:
authors2 = df['Author'].unique()

In [ ]:
#which authors2 not in authors1
[x for x in authors2 if x not in authors1]

['Brinkmeier et al. (2025)']

In [ ]:
#df where Author doesnt start with Rebboah
print(df[~(df["Author"].str.startswith("Rebboah"))].shape)
#print where not Rebboah and Normal == 1
print(df[(df["Normal"]==1) & ~(df["Author"].str.startswith("Rebboah"))].shape)

(216, 43)
(150, 43)

In [ ]:
#print where n_cells > 300
df[df["n_cells"]>300]

,GEO,SRA_ID,Name,Conditions,Normal,Background,Sorted,Author,DOI,Age,...,most_recent_workflow,n_cells,processed_atac,passed_qc_tcc,tcc_pseudobulked,Core,Notes 1,Notes 2,Study_Seurat_version_int,Study_CR_version_int
0,GSM4594333,SRX8489818,M-Pituitary,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,v_0.01,1278,0.0,1.0,v_0.01,1,NaN,NaN,3,3
1,GSM4594334,SRX8489819,FM_Pit_1-1,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,v_0.01,8236,0.0,1.0,v_0.01,1,NaN,NaN,3,3
2,GSM4594335,SRX8489820,FM_Pit_1-2,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,v_0.01,7092,0.0,1.0,v_0.01,1,NaN,NaN,3,3
3,GSM4594336,SRX8489821,MM_Pit_4-1,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,v_0.01,1755,0.0,1.0,v_0.01,1,NaN,NaN,3,3
4,GSM4594337,SRX8489822,MM_Pit_1v2,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,v_0.01,416,0.0,1.0,v_0.01,1,NaN,NaN,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,GSM9302173,SRX31166359,"pituitary, HFD_2",high_fat_diet,0,Unclear,0,Guo et al. (2025),NaN,16 weeks,...,v_0.01,7193,NaN,NaN,NaN,1,NaN,NaN,<NA>,<NA>
279,GSM9302174,SRX31166360,"pituitary, ND_1",normal,1,Unclear,0,Guo et al. (2025),NaN,16 weeks,...,v_0.01,7298,NaN,NaN,NaN,1,NaN,NaN,<NA>,<NA>
280,GSM9302175,SRX31166361,"pituitary, ND_2",normal,1,Unclear,0,Guo et al. (2025),NaN,16 weeks,...,v_0.01,7530,NaN,NaN,NaN,1,in previous version Normal was switched as 0 w...,NaN,<NA>,<NA>
281,GSM9459038,SRX31798127,POMC-WT,POMC-WT,1,C57BL/6J,0,Sochodolsky et al. (2026),NaN,386 days,...,v_0.01,8083,NaN,NaN,NaN,1,NaN,NaN,<NA>,<NA>
282,GSM9459037,SRX31798126,POMC-KO,POMC-KO,0,C57BL/6J,0,Sochodolsky et al. (2026),NaN,376 and 386 days,...,v_0.01,7038,NaN,NaN,NaN,1,NaN,NaN,<NA>,<NA>

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/pituitary_atlas/source_table/pituitary_atlas.xlsx')
#where less than 300
#print total rebboah datasets
print(df[df["Author"].str.startswith("Rebboah")].shape)
df[df["n_cells"]<300] # Reveals 8 rebboah datasets

(65, 41)

,GEO,SRA_ID,Name,Conditions,Normal,Background,Sorted,Author,DOI,Age,...,filtering_junk,median_cellassign_prob,most_recent_workflow,n_cells,processed_atac,passed_qc_tcc,tcc_pseudobulked,Core,Notes 1,Notes 2
29,GSM4026477,SRX6699503,PP2 (scRNA-Seq),normal,1,C57BL/6,1,Chen et al. (2020),10.1523/ENEURO.0345-19.2019,3 months,...,1.0,1.000000,v_0.01,266,0.0,-1.0,NaN,1,NaN,NaN
36,GSM4399749,SRX7874743,WT-8wk-0324-female,normal,1,CD1,0,Ho et al. (2020),10.1007/s13238-020-00705-x,8 week,...,1.0,0.949385,v_0.01,213,0.0,-1.0,NaN,1,NaN,NaN
37,GSM4399750,SRX7874744,WT-8wk-0324-male,normal,1,CD1,0,Ho et al. (2020),10.1007/s13238-020-00705-x,8 week,...,1.0,0.995482,v_0.01,65,0.0,-1.0,NaN,1,NaN,NaN
200,066_NODJ_10F_01,066_NODJ_10F_01,NaN,normal,1,NODJ,0,Rebboah et al. (2025),NaN,72,...,NaN,0.998990,v_0.02,3,NaN,NaN,NaN,0,NaN,NaN
203,069_NODJ_10M_01,069_NODJ_10M_01,NaN,normal,1,NODJ,0,Rebboah et al. (2025),NaN,72,...,NaN,0.985079,v_0.02,166,NaN,NaN,NaN,0,NaN,NaN
214,032_AJ_10F_01,032_AJ_10F_01,NaN,normal,1,AJ,0,Rebboah et al. (2025),NaN,69,...,NaN,0.980534,v_0.02,29,NaN,NaN,NaN,0,NaN,NaN
232,086_CASTJ_10F_01,086_CASTJ_10F_01,NaN,normal,1,CASTJ,0,Rebboah et al. (2025),NaN,69,...,NaN,0.979869,v_0.02,3,NaN,NaN,NaN,0,NaN,NaN
238,094_CASTJ_10F_01,094_CASTJ_10F_01,NaN,normal,1,CASTJ,0,Rebboah et al. (2025),NaN,69,...,NaN,0.996052,v_0.02,174,NaN,NaN,NaN,0,NaN,NaN
242,060_WSBJ_10F_01,060_WSBJ_10F_01,NaN,normal,1,WSBJ,0,Rebboah et al. (2025),NaN,69,...,NaN,0.990998,v_0.02,18,NaN,NaN,NaN,0,NaN,Pituitary seems to be missing
244,062_WSBJ_10F_01,062_WSBJ_10F_01,NaN,normal,1,WSBJ,0,Rebboah et al. (2025),NaN,69,...,NaN,0.980933,v_0.02,42,NaN,NaN,NaN,0,NaN,Pituitary seems to be missing
246,096_WSBJ_10F_01,096_WSBJ_10F_01,NaN,normal,1,WSBJ,0,Rebboah et al. (2025),NaN,69,...,NaN,0.999613,v_0.02,15,NaN,NaN,NaN,0,NaN,Pituitary seems to be missing

# Total cells

In [ ]:
df[(df["n_cells"]>300)&(df["Author"]!="Kover et al. (2025)")]["n_cells"].sum()

np.int64(1278316)

# Cells added from Rebboah

In [ ]:
df[(df["10X version"]=="PARSE_WT_MegaV2")&(df["n_cells"]>300)&(df["Author"]!="Kover et al. (2025)")]["n_cells"].sum()

np.int64(128315)

In [ ]:
df[(df["10X version"]!="PARSE_WT_MegaV2")&(df["n_cells"]>300)&(df["Author"]!="Kover et al. (2025)")]["n_cells"].sum()

np.int64(1150001)

In [ ]:
df[(df["n_cells"]>300)]["n_cells"].sum()

np.float64(1138243.0)

In [ ]:
df[(df["10X version"]=="PARSE_WT_MegaV2")&(df["n_cells"]>300)]["n_cells"].sum()

np.int64(128315)

# How many cells after adding in Kover et al.

In [ ]:
df[(df["10X version"]!="PARSE_WT_MegaV2")&(df["n_cells"]>300)]["n_cells"].sum()

np.int64(1154955)

# How many samples before Kover

In [ ]:
df[(df["n_cells"]>300) & (df["Author"]!="Kover et al. (2025)")].shape

(270, 41)

In [ ]:
df[df["Author"]!="Kover et al. (2025)"].shape

(281, 41)

# Samples and cells after Kover

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/pituitary_atlas/source_table/pituitary_atlas.xlsx')
df[(df["n_cells"]>300)].shape

(272, 41)

In [ ]:
df.shape

(283, 41)

In [ ]:
df[(df["n_cells"]>300)]["n_cells"].sum()

np.int64(1283270)

# Calculate union of multiome cells

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/pituitary_atlas/source_table/pituitary_atlas.xlsx')
#calculate n_cells in multi_rna samples
df_multi_rna = df[df["Modality"]=="multi_rna"]
df_multi_rna["n_cells"].sum()

np.int64(148585)

In [ ]:
multi = sc.read("/content/drive/MyDrive/pituitary_atlas/Unstructured/atac_cells_multi_2026_01_28")

In [ ]:
multi.obs["sample"].value_counts()

sample
GSM7807753    9323
GSM7807754    7996
GSM7807743    7441
GSM7807742    7428
GSM7807744    6745
GSM7807750    6258
GSM7807747    6023
GSM7807751    5815
GSM7807756    5523
GSM7807752    4073
GSM7807755    2317
GSM7807741    2187
GSM7483739    2126
Name: count, dtype: int64

In [ ]:
multi

AnnData object with n_obs × n_vars = 73255 × 245876
    obs: 'sample'
    var: 'count', 'selected'
    uns: 'Sex_colors', '_scvi_manager_uuid', '_scvi_uuid', 'leiden_poissonVI', 'leiden_poissonVI_colors', 'neighbors', 'umap'
    obsm: 'X_poissonVI', 'X_umap', '_scvi_extra_categorical_covs'
    obsp: 'connectivities', 'distances'

# Detected 73255 across other datasets and 2175 in our new multiome

In [ ]:
2175+73255

75430

In [ ]:
df

,GEO,SRA_ID,Name,Conditions,Normal,Background,Sorted,Author,DOI,Age,...,filtering_junk,median_cellassign_prob,most_recent_workflow,n_cells,processed_atac,passed_qc_tcc,tcc_pseudobulked,Core,Notes 1,Notes 2
0,GSM4594333,SRX8489818,M-Pituitary,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,1.0,1.0,v_0.01,1278,0.0,1.0,v_0.01,1,NaN,NaN
1,GSM4594334,SRX8489819,FM_Pit_1-1,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,1.0,1.0,v_0.01,8236,0.0,1.0,v_0.01,1,NaN,NaN
2,GSM4594335,SRX8489820,FM_Pit_1-2,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,1.0,1.0,v_0.01,7092,0.0,1.0,v_0.01,1,GEO name should be FM_Pit_1-2,NaN
3,GSM4594336,SRX8489821,MM_Pit_4-1,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,1.0,1.0,v_0.01,1755,0.0,1.0,v_0.01,1,NaN,NaN
4,GSM4594337,SRX8489822,MM_Pit_1v2,normal,1,C57BL/6,0,Ruf-Zamojski et al. (2021),10.1038/s41467-021-22859-w,10-12 weeks,...,1.0,1.0,v_0.01,416,0.0,1.0,v_0.01,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,GSM9302173,SRX31166359,"pituitary, HFD_2",high_fat_diet,0,Unclear,0,Guo et al. (2025),NaN,16 weeks,...,1.0,1.0,v_0.01,7193,NaN,NaN,NaN,1,NaN,NaN
279,GSM9302174,SRX31166360,"pituitary, ND_1",normal,1,Unclear,0,Guo et al. (2025),NaN,16 weeks,...,1.0,1.0,v_0.01,7298,NaN,NaN,NaN,1,NaN,NaN
280,GSM9302175,SRX31166361,"pituitary, ND_2",normal,1,Unclear,0,Guo et al. (2025),NaN,16 weeks,...,1.0,1.0,v_0.01,7530,NaN,NaN,NaN,1,in previous version Normal was switched as 0 w...,NaN
281,GSM9459038,SRX31798127,POMC-WT,POMC-WT,1,C57BL/6J,0,Sochodolsky et al. (2026),NaN,386 days,...,1.0,1.0,v_0.01,8083,NaN,NaN,NaN,1,NaN,NaN
282,GSM9459037,SRX31798126,POMC-KO,POMC-KO,0,C57BL/6J,0,Sochodolsky et al. (2026),NaN,376 and 386 days,...,1.0,1.0,v_0.01,7038,NaN,NaN,NaN,1,NaN,NaN

In [ ]:
df = df[(df["n_cells"]>300)]
df["Modality"].value_counts()

Modality
sc            121
sn             84
atac           31
multi_rna      18
multi_atac     18
Name: count, dtype: int64

In [ ]:
272-18

254

In [ ]:
121+84

205

In [ ]:
31

31

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/pituitary_atlas/source_table/pituitary_atlas.xlsx')

#print value_counts for Comp_sex in each Author
for author in df["Author"].unique():
  print(author)
  sub_df = df[df["Author"]==author]
  print(sub_df["Comp_sex"].value_counts())

Ruf-Zamojski et al. (2021)
Comp_sex
1.0    13
0.0    12
Name: count, dtype: int64
Cheung et al. (2018)
Comp_sex
1.0    2
Name: count, dtype: int64
Mayran et al. (2019)
Comp_sex
1.0    1
Name: count, dtype: int64
Chen et al. (2020)
Comp_sex
1.0    2
Name: count, dtype: int64
Ho et al. (2020)
Comp_sex
0.0    7
1.0    3
Name: count, dtype: int64
Lopez et al. (2021)
Comp_sex
1.0    2
Name: count, dtype: int64
Ruggiero-Ruff et al. (2024)
Comp_sex
1.0    4
Name: count, dtype: int64
Vennekens et al. (2021)
Comp_sex
1.0    8
Name: count, dtype: int64
Laporte et al. (2022)
Comp_sex
1.0    3
0.0    1
Name: count, dtype: int64
Li et al. (2023)
Comp_sex
0.0    2
1.0    1
Name: count, dtype: int64
Miles et al. (2023)
Comp_sex
0.0    6
1.0    6
Name: count, dtype: int64
Bohaczuk et al. (2021)
Comp_sex
1.0    2
Name: count, dtype: int64
Schang et al. (2022)
Comp_sex
1.0    12
Name: count, dtype: int64
Lin et al. (2022)
Comp_sex
1.0    4
Name: count, dtype: int64
Rizzoti et al. (2023)
Comp_sex
1.0    6
Name: count, dtype: int64
Cheung et al. (2023)
Comp_sex
1.0    1
0.0    1
Name: count, dtype: int64
Allensworth-James et al. (2021)
Comp_sex
0.0    2
Name: count, dtype: int64
Moncho-Amor et al. (2021)
Comp_sex
1.0    2
0.0    1
Name: count, dtype: int64
Bastedo et al. (2024)
Comp_sex
1.0    1
Name: count, dtype: int64
Zhang et al. (2024)
Comp_sex
1.0    2
Name: count, dtype: int64
Cheung et al. (2020)
Comp_sex
0.0    2
Name: count, dtype: int64
Masser et al. (2024)
Comp_sex
0.0    2
Name: count, dtype: int64
Qian et al. (2024)
Comp_sex
1.0    8
Name: count, dtype: int64
Martinez-Mayer et al. (2024)
Comp_sex
0.0    1
1.0    1
Name: count, dtype: int64
Kang et al. (2023)
Comp_sex
1.0    2
Name: count, dtype: int64
Sheridan et al. (2025)
Comp_sex
1.0    1
0.0    1
Name: count, dtype: int64
Khetchoumian et al. (2024)
Comp_sex
1.0    3
Name: count, dtype: int64
Wang et al. (2024)
Comp_sex
0.0    32
Name: count, dtype: int64
Huang et al. (2024)
Comp_sex
0.0    4
Name: count, dtype: int64
De Vriendt et al. (2025)
Comp_sex
1.0    8
Name: count, dtype: int64
Ongaro et al. (2025)
Comp_sex
0.0    6
1.0    5
Name: count, dtype: int64
Brinkmeier et al. (2025)
Comp_sex
0.0    1
Name: count, dtype: int64
Miles et al. (2025)
Comp_sex
0.0    4
1.0    4
Name: count, dtype: int64
Rebboah et al. (2025)
Comp_sex
0.0    31
1.0    29
Name: count, dtype: int64
Cheung et al. (2025)
Comp_sex
1.0    2
0.0    2
Name: count, dtype: int64
Wei et al. (2025)
Comp_sex
0.0    2
1.0    2
Name: count, dtype: int64
Kover et al. (2025)
Comp_sex
1.0    2
Name: count, dtype: int64
Jin et al. (2025)
Comp_sex
1.0    10
Name: count, dtype: int64
Guo et al. (2025)
Comp_sex
1.0    4
Name: count, dtype: int64
Sochodolsky et al. (2026)
Comp_sex
1.0    2
Name: count, dtype: int64

In [ ]:
sub_df["Comp_sex"]

Series([], Name: Comp_sex, dtype: object)

In [ ]:
from enum import unique
#print all studies with both 0 and 1 Comp_sex in it
for author in df["Author"].unique():
  sub_df = df[df["Author"]==author]

  #keep where Comp_sex is 0 or 1
  sub_df = sub_df[(sub_df["Comp_sex"]==0) | (sub_df["Comp_sex"]==1)]
  if sub_df["Comp_sex"].nunique() == 2:
    print(author)
    print(sub_df["Comp_sex"].value_counts())

Ruf-Zamojski et al. (2021)
Comp_sex
1.0    13
0.0    12
Name: count, dtype: int64
Ho et al. (2020)
Comp_sex
0.0    7
1.0    3
Name: count, dtype: int64
Laporte et al. (2022)
Comp_sex
1.0    3
0.0    1
Name: count, dtype: int64
Li et al. (2023)
Comp_sex
0.0    2
1.0    1
Name: count, dtype: int64
Miles et al. (2023)
Comp_sex
0.0    6
1.0    6
Name: count, dtype: int64
Cheung et al. (2023)
Comp_sex
1.0    1
0.0    1
Name: count, dtype: int64
Moncho-Amor et al. (2021)
Comp_sex
1.0    2
0.0    1
Name: count, dtype: int64
Martinez-Mayer et al. (2024)
Comp_sex
0.0    1
1.0    1
Name: count, dtype: int64
Sheridan et al. (2025)
Comp_sex
1.0    1
0.0    1
Name: count, dtype: int64
Ongaro et al. (2025)
Comp_sex
0.0    6
1.0    5
Name: count, dtype: int64
Miles et al. (2025)
Comp_sex
0.0    4
1.0    4
Name: count, dtype: int64
Rebboah et al. (2025)
Comp_sex
0.0    31
1.0    29
Name: count, dtype: int64
Cheung et al. (2025)
Comp_sex
1.0    2
0.0    2
Name: count, dtype: int64
Wei et al. (2025)
Comp_sex
0.0    2
1.0    2
Name: count, dtype: int64

In [ ]:
from enum import unique
#print all studies with both 0 and 1 Comp_sex in it
for author in df["Author"].unique():
  sub_df = df[df["Author"]==author]

  #keep where Comp_sex is 0 or 1
  sub_df = sub_df[(sub_df["Comp_sex"]==0) | (sub_df["Comp_sex"]==1)]
  if sub_df["Comp_sex"].nunique() == 1:
    #if unique is 1
    if sub_df["Comp_sex"].unique()[0] == 1:
      print(author)
      print(author)
      print(sub_df["Comp_sex"].value_counts())

Cheung et al. (2018)
Cheung et al. (2018)
Comp_sex
1.0    2
Name: count, dtype: int64
Mayran et al. (2019)
Mayran et al. (2019)
Comp_sex
1.0    1
Name: count, dtype: int64
Chen et al. (2020)
Chen et al. (2020)
Comp_sex
1.0    2
Name: count, dtype: int64
Lopez et al. (2021)
Lopez et al. (2021)
Comp_sex
1.0    2
Name: count, dtype: int64
Ruggiero-Ruff et al. (2024)
Ruggiero-Ruff et al. (2024)
Comp_sex
1.0    4
Name: count, dtype: int64
Vennekens et al. (2021)
Vennekens et al. (2021)
Comp_sex
1.0    8
Name: count, dtype: int64
Bohaczuk et al. (2021)
Bohaczuk et al. (2021)
Comp_sex
1.0    2
Name: count, dtype: int64
Schang et al. (2022)
Schang et al. (2022)
Comp_sex
1.0    12
Name: count, dtype: int64
Lin et al. (2022)
Lin et al. (2022)
Comp_sex
1.0    4
Name: count, dtype: int64
Rizzoti et al. (2023)
Rizzoti et al. (2023)
Comp_sex
1.0    6
Name: count, dtype: int64
Bastedo et al. (2024)
Bastedo et al. (2024)
Comp_sex
1.0    1
Name: count, dtype: int64
Zhang et al. (2024)
Zhang et al. (2024)
Comp_sex
1.0    2
Name: count, dtype: int64
Qian et al. (2024)
Qian et al. (2024)
Comp_sex
1.0    8
Name: count, dtype: int64
Kang et al. (2023)
Kang et al. (2023)
Comp_sex
1.0    2
Name: count, dtype: int64
Khetchoumian et al. (2024)
Khetchoumian et al. (2024)
Comp_sex
1.0    3
Name: count, dtype: int64
De Vriendt et al. (2025)
De Vriendt et al. (2025)
Comp_sex
1.0    8
Name: count, dtype: int64
Kover et al. (2025)
Kover et al. (2025)
Comp_sex
1.0    2
Name: count, dtype: int64
Jin et al. (2025)
Jin et al. (2025)
Comp_sex
1.0    10
Name: count, dtype: int64
Guo et al. (2025)
Guo et al. (2025)
Comp_sex
1.0    4
Name: count, dtype: int64
Sochodolsky et al. (2026)
Sochodolsky et al. (2026)
Comp_sex
1.0    2
Name: count, dtype: int64

In [ ]:
from enum import unique
#print all studies with both 0 and 1 Comp_sex in it
for author in df["Author"].unique():
  sub_df = df[df["Author"]==author]

  #keep where Comp_sex is 0 or 1
  sub_df = sub_df[(sub_df["Comp_sex"]==0) | (sub_df["Comp_sex"]==1)]
  if sub_df["Comp_sex"].nunique() == 1:
    #if unique is 1
    if sub_df["Comp_sex"].unique()[0] == 0:
      print(author)
      print(author)
      print(sub_df["Comp_sex"].value_counts())

Allensworth-James et al. (2021)
Allensworth-James et al. (2021)
Comp_sex
0.0    2
Name: count, dtype: int64
Cheung et al. (2020)
Cheung et al. (2020)
Comp_sex
0.0    2
Name: count, dtype: int64
Masser et al. (2024)
Masser et al. (2024)
Comp_sex
0.0    2
Name: count, dtype: int64
Wang et al. (2024)
Wang et al. (2024)
Comp_sex
0.0    32
Name: count, dtype: int64
Huang et al. (2024)
Huang et al. (2024)
Comp_sex
0.0    4
Name: count, dtype: int64
Brinkmeier et al. (2025)
Brinkmeier et al. (2025)
Comp_sex
0.0    1
Name: count, dtype: int64

In [ ]:
#print all Author wiht age numeric > 250
import numpy as np
for author in df["Author"].unique():
  sub_df = df[df["Author"]==author]
  if np.max(sub_df["Age_numeric"]) > 250:
    print(author)
    print(sub_df["Age_numeric"].max())

Vennekens et al. (2021)
420.0
Li et al. (2023)
630.0
Kang et al. (2023)
600.0
Huang et al. (2024)
280.0
De Vriendt et al. (2025)
750.0
Miles et al. (2025)
300.0
Cheung et al. (2025)
660.0
Wei et al. (2025)
720.0
Sochodolsky et al. (2026)
386.0

In [ ]:
#print all Author wiht age numeric > 250
import numpy as np
for author in df["Author"].unique():
  sub_df = df[df["Author"]==author]
  if np.min(sub_df["Age_numeric"]) < 25:
    print(author)
    print(sub_df["Age_numeric"].min())

Laporte et al. (2022)
7.0
Cheung et al. (2023)
7.0
Cheung et al. (2020)
4.0
Masser et al. (2024)
4.0
Martinez-Mayer et al. (2024)
-7.5
Sheridan et al. (2025)
3.0
De Vriendt et al. (2025)
7.0
Brinkmeier et al. (2025)
-5.5
Kover et al. (2025)
4.0