<a href="https://colab.research.google.com/github/Andoniadou-Lab/consensus_pituitary_atlas/blob/main/Fig_1/Figure_1_Create_pituitary_atlas_rna.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This notebook contains code that was used to download/access single-cell datasets

## Install packages

In [2]:
!pip install kb-python -q
!pip install ffq -q
!apt-get install jq -q
!apt-get install -y sra-toolkit
!pip install epitome_tools

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 kB 1.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.5/36.5 MB 46.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.6/176.6 kB 10.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 87.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 MB 37.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 71.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.1/60.1 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.0/24.0 MB 79.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 284.1/284.1 kB 16.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 kB 1.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 110.5 MB/s eta 0:00:00
  Building wheel for loompy (setup.py) ... done
Reading package lists...
Building dependency tree...
Reading state information...
jq is already the newest version (1.6-2.1ubuntu3.1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  blends-common libkdf5-2 libncbi-vdb2 libncbi-wvdb2 med-config menu
Suggested packages:
  blends-doc menu-l10n gksu | kde-runtime | ktsuss
The following NEW packages will be installed:
  blends-common libkdf5-2 libncbi-vdb2 libncbi-wvdb2 med-config menu
  sra-toolkit
0 upgraded, 7 newly installed, 0 to remove and 2 not upgraded.
Need to get 8,290 kB of archives.
After this operation, 23.0 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 menu amd64 2.1.47ubuntu4 [354 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/universe amd64 blends-common all 0.7.4ubuntu1 [15.9 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libkdf5-2 amd64 2.11.2+dfsg-4build2 [14.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libncbi-vdb2 amd64 2.11.2+dfsg-4build2 [1,364 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libncbi-wvdb2 amd64 2.11.2+dfsg-4build2 [1,252 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/universe amd64 sra-toolkit amd64 2.11.3+dfsg-1ubuntu1 [5,277 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/universe amd64 med-config all 3.7.1 [11.6 kB]
Fetched 8,290 kB in 1s (6,940 kB/s)
Preconfiguring packages ...
Selecting previously unselected package menu.
(Reading database ... 117540 files and directories currently installed.)
Preparing to unpack .../0-menu_2.1.47ubuntu4_amd64.deb ...
Unpacking menu (2.1.47ubuntu4) ...
Selecting previously unselected package blends-common.
Preparing to unpack .../1-blends-common_0.7.4ubuntu1_all.deb ...
Unpacking blends-common (0.7.4ubuntu1) ...
Selecting previously unselected package libkdf5-2.
Preparing to unpack .../2-libkdf5-2_2.11.2+dfsg-4build2_amd64.deb ...
Unpacking libkdf5-2 (2.11.2+dfsg-4build2) ...
Selecting previously unselected package libncbi-vdb2.
Preparing to unpack .../3-libncbi-vdb2_2.11.2+dfsg-4build2_amd64.deb ...
Unpacking libncbi-vdb2 (2.11.2+dfsg-4build2) ...
Selecting previously unselected package libncbi-wvdb2.
Preparing to unpack .../4-libncbi-wvdb2_2.11.2+dfsg-4build2_amd64.deb ...
Unpacking libncbi-wvdb2 (2.11.2+dfsg-4build2) ...
Selecting previously unselected package sra-toolkit.
Preparing to unpack .../5-sra-toolkit_2.11.3+dfsg-1ubuntu1_amd64.deb ...
Unpacking sra-toolkit (2.11.3+dfsg-1ubuntu1) ...
Selecting previously unselected package med-config.
Preparing to unpack .../6-med-config_3.7.1_all.deb ...
Unpacking med-config (3.7.1) ...
Setting up libncbi-vdb2 (2.11.2+dfsg-4build2) ...
Setting up libkdf5-2 (2.11.2+dfsg-4build2) ...
Setting up libncbi-wvdb2 (2.11.2+dfsg-4build2) ...
Setting up menu (2.1.47ubuntu4) ...
Setting up blends-common (0.7.4ubuntu1) ...
Setting up sra-toolkit (2.11.3+dfsg-1ubuntu1) ...
Setting up med-config (3.7.1) ...
Adding group `med' (GID 107) ...
Done.
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.11) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

Processing triggers for menu (2.1.47ubuntu4) ...
Collecting epitome_tools
  Downloading epitome_tools-1.0.4.tar.gz (69.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.2/69.2 MB 28.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (from epitome_tools) (3.2.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from epitome_tools) (1.16.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from epitome_tools) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost->epitome_tools) (2.29.7)
Building wheels for collected packages: epitome_tools
  Building wheel for epitome_tools (pyproject.toml) ... done
  Created wheel for epitome_tools: filename=epitome_tools-1.0.4-py3-none-any.whl size=69857498 sha256=9bf6cbc80202a2bff747bf9c5dd8d65c5c5a2fe99475d8ccf01c1105915e1ff5
  Stored in directory: /root/.cache/pip/wheels/42/2a/6f/b6754fe1f7b14c968fc6723594e7e274ddfc07d00d1ecc7298
Successfully built epitome_tools
Installing collected packages: epitome_tools
Successfully installed epitome_tools-1.0.4

In [3]:
!kb info

kb_python 0.29.5
kallisto: 0.51.1 (/usr/local/lib/python3.12/dist-packages/kb_python/bins/linux/kallisto/kallisto)
bustools: 0.45.1 (/usr/local/lib/python3.12/dist-packages/kb_python/bins/linux/bustools/bustools)
kb is a python package for rapidly pre-processing single-cell RNA-seq data. It
is a wrapper for the methods described in [2].

The goal of the wrapper is to simplify downloading and running of the kallisto
[1] and bustools [2] programs. It was inspired by Sten Linnarsson’s loompy
fromfq command (http://linnarssonlab.org/loompy/kallisto/index.html)

The kb program consists of three parts:

The `kb ref` command builds or downloads a species-specific index for
pseudoalignment of reads. This command must be run prior to `kb count`, and it
runs the `kallisto index` [1].

The `kb count` command runs the kallisto [1] and bustools [2] programs. It can
be used for pre-processing of data from a variety of single-cell RNA-seq
technologies, and for a number of different workflows (e.g. production of gene
count matrices, RNA velocity analyses, etc.). The output can be saved in a
variety of formats including mix and loom. Examples are provided below.

The `kb extract` command runs the kallisto [1] and bustools [2] programs. It
pulls out the raw reads from a fastq file that align to a specified gene or
transcript in the index.

Examples are available at: https://www.kallistobus.tools/tutorials

References
==========
[1] Bray, N. L., Pimentel, H., Melsted, P., & Pachter, L. (2016). Near-optimal
probabilistic RNA-seq quantification. Nature biotechnology, 34(5), 525.
[2] Melsted, P., Booeshaghi, A. S., Liu, L., Gao, F., Lu, L., Min, K. H., da
Veiga Beltrame, E., Hjorleifsson, K. E., Gehring, J., & Pachter, L. (2021).
Modular and efficient pre-processing of single-cell RNA-seq. Nature
Biotechnology.

In [4]:
!pip install epitome_tools --upgrade

Requirement already satisfied: epitome_tools in /usr/local/lib/python3.12/dist-packages (1.0.4)
Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (from epitome_tools) (3.2.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from epitome_tools) (1.16.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from epitome_tools) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost->epitome_tools) (2.29.7)

# Installing bamtofastq from 10X - for cases where only the bam file is accessible

In [5]:
!wget https://github.com/10XGenomics/bamtofastq/releases/download/v1.4.1/bamtofastq_linux -O bamtofastq
!chmod +x bamtofastq
!mv bamtofastq /usr/local/bin/

--2026-03-11 14:46:03--  https://github.com/10XGenomics/bamtofastq/releases/download/v1.4.1/bamtofastq_linux
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/112696910/68945361-1bfe-475a-9b64-d1a39a48e48a?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-11T15%3A44%3A29Z&rscd=attachment%3B+filename%3Dbamtofastq_linux&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-11T14%3A43%3A32Z&ske=2026-03-11T15%3A44%3A29Z&sks=b&skv=2018-11-09&sig=Q0KkDn4pmAuU19CjRqsmRn8Y9xYUjkItN1rylFsFo1E%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3MzI0MjE2MywibmJmIjoxNzczMjQwMzYzLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.mqnHaLiU3CBxBiMP9W73Whv_Ln-JaP0INMP-g1PxETQ&response-content-disposition=attachment%3B%20filename%3Dbamtofastq_linux&response-content-type=application%2Foctet-stream [following]
--2026-03-11 14:46:03--  https://release-assets.githubusercontent.com/github-production-release-asset/112696910/68945361-1bfe-475a-9b64-d1a39a48e48a?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-11T15%3A44%3A29Z&rscd=attachment%3B+filename%3Dbamtofastq_linux&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-11T14%3A43%3A32Z&ske=2026-03-11T15%3A44%3A29Z&sks=b&skv=2018-11-09&sig=Q0KkDn4pmAuU19CjRqsmRn8Y9xYUjkItN1rylFsFo1E%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3MzI0MjE2MywibmJmIjoxNzczMjQwMzYzLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.mqnHaLiU3CBxBiMP9W73Whv_Ln-JaP0INMP-g1PxETQ&response-content-disposition=attachment%3B%20filename%3Dbamtofastq_linux&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18540256 (18M) [application/octet-stream]
Saving to: ‘bamtofastq’

bamtofastq          100%[===================>]  17.68M   112MB/s    in 0.2s

2026-03-11 14:46:04 (112 MB/s) - ‘bamtofastq’ saved [18540256/18540256]

# installing kallisto necessary for TCC mapping (not used in final manuscript, but required for isoform-level results presented on epitome-atlas.com)

In [6]:
%%bash
git clone https://github.com/pachterlab/kallisto && \
cd kallisto && \
mkdir build && \
cd build && \
cmake .. && \
make && \
make install

-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_CXX17
-- Performing Test COMPILER_SUPPORTS_CXX17 - Success
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Configuring done (1.5s)
-- Generating done (0.0s)
-- Build files have been written to: /content/kallisto/build
[  2%] Creating directories for 'bifrost'
[  4%] No download step for 'bifrost'
[  7%] No update step for 'bifrost'
[  9%] No patch step for 'bifrost'
[ 11%] Performing configure step for 'bifrost'
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Configuring done (0.6s)
-- Generating done (0.0s)
-- Build files have been written to: /content/kallisto/ext/bifrost/build
[ 14%] Performing build step for 'bifrost'
[  3%] Building CXX object src/CMakeFiles/bifrost_static.dir/Bifrost.cpp.o
[  6%] Building CXX object src/CMakeFiles/bifrost_static.dir/BitContainer.cpp.o
[  9%] Building CXX object src/CMakeFiles/bifrost_static.dir/BlockedBloomFilter.cpp.o
[ 12%] Building CXX object src/CMakeFiles/bifrost_static.dir/ColorSet.cpp.o
[ 15%] Building CXX object src/CMakeFiles/bifrost_static.dir/CompressedCoverage.cpp.o
[ 18%] Building CXX object src/CMakeFiles/bifrost_static.dir/CompressedSequence.cpp.o
[ 21%] Building CXX object src/CMakeFiles/bifrost_static.dir/FASTX_Parser.cpp.o
[ 25%] Building CXX object src/CMakeFiles/bifrost_static.dir/GFA_Parser.cpp.o
[ 28%] Building CXX object src/CMakeFiles/bifrost_static.dir/Kmer.cpp.o
[ 31%] Building CXX object src/CMakeFiles/bifrost_static.dir/KmerIterator.cpp.o
[ 34%] Building CXX object src/CMakeFiles/bifrost_static.dir/MinimizerIndex.cpp.o
[ 37%] Building CXX object src/CMakeFiles/bifrost_static.dir/TinyBitmap.cpp.o
[ 40%] Building CXX object src/CMakeFiles/bifrost_static.dir/UnitigMap.cpp.o
[ 43%] Building C object src/CMakeFiles/bifrost_static.dir/roaring.c.o
[ 46%] Linking CXX static library libbifrost.a
[ 46%] Built target bifrost_static
[ 50%] Building CXX object src/CMakeFiles/bifrost_dynamic.dir/Bifrost.cpp.o
[ 53%] Building CXX object src/CMakeFiles/bifrost_dynamic.dir/BitContainer.cpp.o
[ 56%] Building CXX object src/CMakeFiles/bifrost_dynamic.dir/BlockedBloomFilter.cpp.o
[ 59%] Building CXX object src/CMakeFiles/bifrost_dynamic.dir/ColorSet.cpp.o
[ 62%] Building CXX object src/CMakeFiles/bifrost_dynamic.dir/CompressedCoverage.cpp.o
[ 65%] Building CXX object src/CMakeFiles/bifrost_dynamic.dir/CompressedSequence.cpp.o
[ 68%] Building CXX object src/CMakeFiles/bifrost_dynamic.dir/FASTX_Parser.cpp.o
[ 71%] Building CXX object src/CMakeFiles/bifrost_dynamic.dir/GFA_Parser.cpp.o
[ 75%] Building CXX object src/CMakeFiles/bifrost_dynamic.dir/Kmer.cpp.o
[ 78%] Building CXX object src/CMakeFiles/bifrost_dynamic.dir/KmerIterator.cpp.o
[ 81%] Building CXX object src/CMakeFiles/bifrost_dynamic.dir/MinimizerIndex.cpp.o
[ 84%] Building CXX object src/CMakeFiles/bifrost_dynamic.dir/TinyBitmap.cpp.o
[ 87%] Building CXX object src/CMakeFiles/bifrost_dynamic.dir/UnitigMap.cpp.o
[ 90%] Building C object src/CMakeFiles/bifrost_dynamic.dir/roaring.c.o
[ 93%] Linking CXX shared library libbifrost.so
[ 93%] Built target bifrost_dynamic
[ 96%] Building CXX object src/CMakeFiles/Bifrost.dir/Bifrost.cpp.o
[100%] Linking CXX executable Bifrost
[100%] Built target Bifrost
[ 16%] No install step for 'bifrost'
[ 19%] Completed 'bifrost'
[ 19%] Built target bifrost
[ 21%] Building CXX object src/CMakeFiles/kallisto_core.dir/BUSData.cpp.o
[ 23%] Building CXX object src/CMakeFiles/kallisto_core.dir/BUSTools.cpp.o
[ 26%] Building CXX object src/CMakeFiles/kallisto_core.dir/Bootstrap.cpp.o
[ 28%] Building CXX object src/CMakeFiles/kallisto_core.dir/Fusion.cpp.o
[ 30%] Building CXX object src/CMakeFiles/kallisto_core.dir/GeneModel.cpp.o
[ 33%] Building CXX object src/CMakeFiles/kallisto_core.dir/H5Writer.cpp.o
[ 35%] Building CXX object src/CMakeFiles/kallisto_core.dir/KmerIndex.cpp.o
[ 38%] Building CXX object src/CMakeFiles/kallisto_core.dir/MinCollector.cpp.o
[ 40%] Building CXX object src/CMakeFiles/kallisto_core.dir/PlaintextWriter.cpp.o
[ 42%] Building CXX object src/CMakeFiles/kallisto_core.dir/ProcessReads.cpp.o
[ 45%] Building CXX object src/CMakeFiles/kallisto_core.dir/PseudoBam.cpp.o
[ 47%] Building CXX object src/CMakeFiles/kallisto_core.dir/common.cpp.o
[ 50%] Building CXX object src/CMakeFiles/kallisto_core.dir/h5utils.cpp.o
[ 52%] Building CXX object src/CMakeFiles/kallisto_core.dir/hash.cpp.o
[ 54%] Building CXX object src/CMakeFiles/kallisto_core.dir/main.cpp.o
[ 57%] Building CXX object src/CMakeFiles/kallisto_core.dir/weights.cpp.o
[ 59%] Linking CXX static library libkallisto_core.a
[ 59%] Built target kallisto_core
[ 61%] Building CXX object src/CMakeFiles/kallisto.dir/main.cpp.o
[ 64%] Building CXX object src/CMakeFiles/kallisto.dir/BUSData.cpp.o
[ 66%] Building CXX object src/CMakeFiles/kallisto.dir/BUSTools.cpp.o
[ 69%] Building CXX object src/CMakeFiles/kallisto.dir/Bootstrap.cpp.o
[ 71%] Building CXX object src/CMakeFiles/kallisto.dir/Fusion.cpp.o
[ 73%] Building CXX object src/CMakeFiles/kallisto.dir/GeneModel.cpp.o
[ 76%] Building CXX object src/CMakeFiles/kallisto.dir/H5Writer.cpp.o
[ 78%] Building CXX object src/CMakeFiles/kallisto.dir/KmerIndex.cpp.o
[ 80%] Building CXX object src/CMakeFiles/kallisto.dir/MinCollector.cpp.o
[ 83%] Building CXX object src/CMakeFiles/kallisto.dir/PlaintextWriter.cpp.o
[ 85%] Building CXX object src/CMakeFiles/kallisto.dir/ProcessReads.cpp.o
[ 88%] Building CXX object src/CMakeFiles/kallisto.dir/PseudoBam.cpp.o
[ 90%] Building CXX object src/CMakeFiles/kallisto.dir/common.cpp.o
[ 92%] Building CXX object src/CMakeFiles/kallisto.dir/h5utils.cpp.o
[ 95%] Building CXX object src/CMakeFiles/kallisto.dir/hash.cpp.o
[ 97%] Building CXX object src/CMakeFiles/kallisto.dir/weights.cpp.o
[100%] Linking CXX executable kallisto
[100%] Built target kallisto
[ 19%] Built target bifrost
[ 59%] Built target kallisto_core
[100%] Built target kallisto
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/bin/kallisto

Cloning into 'kallisto'...
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


shared build
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


Compilation architecture: native
Build type: Release
Maximum k-mer size: 31
Maximum g-mer size: 31
In file included from /content/kallisto/ext/bifrost/src/MinimizerIndex.hpp:12,
                 from /content/kallisto/ext/bifrost/src/CompactedDBG.hpp:40,
                 from /content/kallisto/ext/bifrost/src/Bifrost.cpp:1:
/content/kallisto/ext/bifrost/src/BooPHF.h: In member function ‘void boomphf::bitVector::print() const’:
/content/kallisto/ext/bifrost/src/BooPHF.h:536:42: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
  536 |             printf("bit array of size %llu: \n",_size);
      |                                       ~~~^      ~~~~~
      |                                          |      |
      |                                          |      long unsigned int
      |                                          long long unsigned int
      |                                       %lu
/content/kallisto/ext/bifrost/src/BooPHF.h:540:34: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
  540 |                     printf(" (%llu) ",ii);
      |                               ~~~^    ~~
      |                                  |    |
      |                                  |    uint64_t {aka long unsigned int}
      |                                  long long unsigned int
      |                               %lu
/content/kallisto/ext/bifrost/src/BooPHF.h:549:28: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
  549 |                 printf("%llu :  %llu,  ",ii,_ranks[ii]);
      |                         ~~~^             ~~
      |                            |             |
      |                            |             uint64_t {aka long unsigned int}
      |                            long long unsigned int
      |                         %lu
/content/kallisto/ext/bifrost/src/BooPHF.h:549:36: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
  549 |                 printf("%llu :  %llu,  ",ii,_ranks[ii]);
      |                                 ~~~^
      |                                    |
      |                                    long long unsigned int
      |                                 %lu
In file included from /content/kallisto/ext/bifrost/src/MinimizerIndex.hpp:12,
                 from /content/kallisto/ext/bifrost/src/CompactedDBG.hpp:40,
                 from /content/kallisto/ext/bifrost/src/ColorSet.hpp:6,
                 from /content/kallisto/ext/bifrost/src/ColorSet.cpp:1:
/content/kallisto/ext/bifrost/src/BooPHF.h: In member function ‘void boomphf::bitVector::print() const’:
/content/kallisto/ext/bifrost/src/BooPHF.h:536:42: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
  536 |             printf("bit array of size %llu: \n",_size);
      |                                       ~~~^      ~~~~~
      |                                          |      |
      |                                          |      long unsigned int
      |                                          long long unsigned int
      |                                       %lu
/content/kallisto/ext/bifrost/src/BooPHF.h:540:34: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
  540 |                     printf(" (%llu) ",ii);
      |                               ~~~^    ~~
      |                                  |    |
      |                                  |    uint64_t {aka long unsigned int}
      |                                  long long unsigned int
      |                               %lu
/content/kallisto/ext/bifrost/src/BooPHF.h:549:28: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
  549 |                 printf("%llu :  %llu,  ",ii,_ranks[ii]);
      |                         ~~~^             ~~
      |                            |             |
      |                            |             uint64_t {aka long unsigned int}
      |                            long long unsigned int
      |                         %lu
/content/kallisto/ext/bifrost/src/BooPHF.h:549:36: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
  549 |                 printf("%llu :  %llu,  ",ii,_ranks[ii]);
      |                                 ~~~^
      |                                    |
      |                                    long long unsigned int
      |                                 %lu
In file included from /content/kallisto/ext/bifrost/src/MinimizerIndex.hpp:12,
                 from /content/kallisto/ext/bifrost/src/MinimizerIndex.cpp:1:
/content/kallisto/ext/bifrost/src/BooPHF.h: In member function ‘void boomphf::bitVector::print() const’:
/content/kallisto/ext/bifrost/src/BooPHF.h:536:42: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
  536 |             printf("bit array of size %llu: \n",_size);
      |                                       ~~~^      ~~~~~
      |                                          |      |
      |                                          |      long unsigned int
      |                                          long long unsigned int
      |                                       %lu
/content/kallisto/ext/bifrost/src/BooPHF.h:540:34: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
  540 |                     printf(" (%llu) ",ii);
      |                               ~~~^    ~~
      |                                  |    |
      |                                  |    uint64_t {aka long unsigned int}
      |                                  long long unsigned int
      |                               %lu
/content/kallisto/ext/bifrost/src/BooPHF.h:549:28: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
  549 |                 printf("%llu :  %llu,  ",ii,_ranks[ii]);
      |                         ~~~^             ~~
      |                            |             |
      |                            |             uint64_t {aka long unsigned int}
      |                            long long unsigned int
      |                         %lu
/content/kallisto/ext/bifrost/src/BooPHF.h:549:36: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
  549 |                 printf("%llu :  %llu,  ",ii,_ranks[ii]);
      |                                 ~~~^
      |                                    |
      |                                    long long unsigned int
      |                                 %lu
In file included from /content/kallisto/ext/bifrost/src/MinimizerIndex.hpp:12,
                 from /content/kallisto/ext/bifrost/src/CompactedDBG.hpp:40,
                 from /content/kallisto/ext/bifrost/src/UnitigMap.tcc:4,
                 from /content/kallisto/ext/bifrost/src/UnitigMap.hpp:324,
                 from /content/kallisto/ext/bifrost/src/UnitigMap.cpp:1:
/content/kallisto/ext/bifrost/src/BooPHF.h: In member function ‘void boomphf::bitVector::print() const’:
/content/kallisto/ext/bifrost/src/BooPHF.h:536:42: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
  536 |             printf("bit array of size %llu: \n",_size);
      |                                       ~~~^      ~~~~~
      |                                          |      |
      |                                          |      long unsigned int
      |                                          long long unsigned int
      |                                       %lu
/content/kallisto/ext/bifrost/src/BooPHF.h:540:34: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
  540 |                     printf(" (%llu) ",ii);
      |                               ~~~^    ~~
      |                                  |    |
      |                                  |    uint64_t {aka long unsigned int}
      |                                  long long unsigned int
      |                               %lu
/content/kallisto/ext/bifrost/src/BooPHF.h:549:28: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
  549 |                 printf("%llu :  %llu,  ",ii,_ranks[ii]);
      |                         ~~~^             ~~
      |                            |             |
      |                            |             uint64_t {aka long unsigned int}
      |                            long long unsigned int
      |                         %lu
/content/kallisto/ext/bifrost/src/BooPHF.h:549:36: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
  549 |                 printf("%llu :  %llu,  ",ii,_ranks[ii]);
      |                                 ~~~^
      |                                    |
      |                                    long long unsigned int
      |                                 %lu
In file included from /content/kallisto/ext/bifrost/src/MinimizerIndex.hpp:12,
                 from /content/kallisto/ext/bifrost/src/CompactedDBG.hpp:40,
                 from /content/kallisto/ext/bifrost/src/Bifrost.cpp:1:
/content/kallisto/ext/bifrost/src/BooPHF.h: In member function ‘void boomphf::bitVector::print() const’:
/content/kallisto/ext/bifrost/src/BooPHF.h:536:42: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
  536 |             printf("bit array of size %llu: \n",_size);
      |                                       ~~~^      ~~~~~
      |                                          |      |
      |                                          |      long unsigned int
      |                                          long long unsigned int
      |                                       %lu
/content/kallisto/ext/bifrost/src/BooPHF.h:540:34: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
  540 |                     printf(" (%llu) ",ii);
      |                               ~~~^    ~~
      |                                  |    |
      |                                  |    uint64_t {aka long unsigned int}
      |                                  long long unsigned int
      |                               %lu
/content/kallisto/ext/bifrost/src/BooPHF.h:549:28: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
  549 |                 printf("%llu :  %llu,  ",ii,_ranks[ii]);
      |                         ~~~^             ~~
      |                            |             |
      |                            |             uint64_t {aka long unsigned int}
      |                            long long unsigned int
      |                         %lu
/content/kallisto/ext/bifrost/src/BooPHF.h:549:36: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
  549 |                 printf("%llu :  %llu,  ",ii,_ranks[ii]);
      |                                 ~~~^
      |                                    |
      |                                    long long unsigned int
      |                                 %lu
In file included from /content/kallisto/ext/bifrost/src/MinimizerIndex.hpp:12,
                 from /content/kallisto/ext/bifrost/src/CompactedDBG.hpp:40,
                 from /content/kallisto/ext/bifrost/src/ColorSet.hpp:6,
                 from /content/kallisto/ext/bifrost/src/ColorSet.cpp:1:
/content/kallisto/ext/bifrost/src/BooPHF.h: In member function ‘void boomphf::bitVector::print() const’:
/content/kallisto/ext/bifrost/src/BooPHF.h:536:42: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
  536 |             printf("bit array of size %llu: \n",_size);
      |                                       ~~~^      ~~~~~
      |                                          |      |
      |                                          |      long unsigned int
      |                                          long long unsigned int
      |                                       %lu
/content/kallisto/ext/bifrost/src/BooPHF.h:540:34: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
  540 |                     printf(" (%llu) ",ii);
      |                               ~~~^    ~~
      |                                  |    |
      |                                  |    uint64_t {aka long unsigned int}
      |                                  long long unsigned int
      |                               %lu
/content/kallisto/ext/bifrost/src/BooPHF.h:549:28: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
  549 |                 printf("%llu :  %llu,  ",ii,_ranks[ii]);
      |                         ~~~^             ~~
      |                            |             |
      |                            |             uint64_t {aka long unsigned int}
      |                            long long unsigned int
      |                         %lu
/content/kallisto/ext/bifrost/src/BooPHF.h:549:36: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
  549 |                 printf("%llu :  %llu,  ",ii,_ranks[ii]);
      |                                 ~~~^
      |                                    |
      |                                    long long unsigned int
      |                                 %lu
In file included from /content/kallisto/ext/bifrost/src/MinimizerIndex.hpp:12,
                 from /content/kallisto/ext/bifrost/src/MinimizerIndex.cpp:1:
/content/kallisto/ext/bifrost/src/BooPHF.h: In member function ‘void boomphf::bitVector::print() const’:
/content/kallisto/ext/bifrost/src/BooPHF.h:536:42: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
  536 |             printf("bit array of size %llu: \n",_size);
      |                                       ~~~^      ~~~~~
      |                                          |      |
      |                                          |      long unsigned int
      |                                          long long unsigned int
      |                                       %lu
/content/kallisto/ext/bifrost/src/BooPHF.h:540:34: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
  540 |                     printf(" (%llu) ",ii);
      |                               ~~~^    ~~
      |                                  |    |
      |                                  |    uint64_t {aka long unsigned int}
      |                                  long long unsigned int
      |                               %lu
/content/kallisto/ext/bifrost/src/BooPHF.h:549:28: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
  549 |                 printf("%llu :  %llu,  ",ii,_ranks[ii]);
      |                         ~~~^             ~~
      |                            |             |
      |                            |             uint64_t {aka long unsigned int}
      |                            long long unsigned int
      |                         %lu
/content/kallisto/ext/bifrost/src/BooPHF.h:549:36: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
  549 |                 printf("%llu :  %llu,  ",ii,_ranks[ii]);
      |                                 ~~~^
      |                                    |
      |                                    long long unsigned int
      |                                 %lu
In file included from /content/kallisto/ext/bifrost/src/MinimizerIndex.hpp:12,
                 from /content/kallisto/ext/bifrost/src/CompactedDBG.hpp:40,
                 from /content/kallisto/ext/bifrost/src/UnitigMap.tcc:4,
                 from /content/kallisto/ext/bifrost/src/UnitigMap.hpp:324,
                 from /content/kallisto/ext/bifrost/src/UnitigMap.cpp:1:
/content/kallisto/ext/bifrost/src/BooPHF.h: In member function ‘void boomphf::bitVector::print() const’:
/content/kallisto/ext/bifrost/src/BooPHF.h:536:42: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
  536 |             printf("bit array of size %llu: \n",_size);
      |                                       ~~~^      ~~~~~
      |                                          |      |
      |                                          |      long unsigned int
      |                                          long long unsigned int
      |                                       %lu
/content/kallisto/ext/bifrost/src/BooPHF.h:540:34: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
  540 |                     printf(" (%llu) ",ii);
      |                               ~~~^    ~~
      |                                  |    |
      |                                  |    uint64_t {aka long unsigned int}
      |                                  long long unsigned int
      |                               %lu
/content/kallisto/ext/bifrost/src/BooPHF.h:549:28: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
  549 |                 printf("%llu :  %llu,  ",ii,_ranks[ii]);
      |                         ~~~^             ~~
      |                            |             |
      |                            |             uint64_t {aka long unsigned int}
      |                            long long unsigned int

# Mounting Drive onto colab

In [7]:
#mount drive
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

# Load the dataset table

In [ ]:
import pandas as pd
df = pd.read_excel('/content/drive/MyDrive/pituitary_atlas/source_table/pituitary_atlas.xlsx')
#only keep sn or sc for now
df = df[df['Modality'].isin(['sc','sn','multi_rna'])]
#keep where 10X version is not PARSE_WT_MegaV2
df = df[df['10X version'] != 'PARSE_WT_MegaV2']
df = df.reset_index(drop=True)
df.tail()

,GEO,SRA_ID,Name,Conditions,Normal,Background,Sorted,Author,DOI,Age,...,filtering_junk,median_cellassign_prob,most_recent_workflow,n_cells,processed_atac,passed_qc_tcc,tcc_pseudobulked,Core,Notes 1,Notes 2
164,GSM9302173,SRX31166359,"pituitary, HFD_2",High_fat_diet,1,Unclear,0,Guo et al. (2025),NaN,16 weeks,...,1.0,1.0,v_0.01,7193.0,NaN,NaN,NaN,2,NaN,NaN
165,GSM9302174,SRX31166360,"pituitary, ND_1",Normal_diet,0,Unclear,0,Guo et al. (2025),NaN,16 weeks,...,1.0,1.0,v_0.01,7298.0,NaN,NaN,NaN,2,NaN,NaN
166,GSM9302175,SRX31166361,"pituitary, ND_2",Normal_diet,0,Unclear,0,Guo et al. (2025),NaN,16 weeks,...,1.0,1.0,v_0.01,7530.0,NaN,NaN,NaN,2,NaN,NaN
167,NaN,SRX31798127,NaN,POMC-WT,1,C57BL/6J,0,Sochodolsky et al. (2026),NaN,386 days,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
168,NaN,SRX31798126,NaN,POMC-KO,0,C57BL/6J,0,Sochodolsky et al. (2026),NaN,376 and 386 days,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN


# Download all SRA files

In [ ]:
import epitome_tools.atlas as atlas

In [ ]:
#keep tail
df= df.tail(4).reset_index(drop=True)
df

,GEO,SRA_ID,Name,Conditions,Normal,Background,Sorted,Author,DOI,Age,...,filtering_junk,median_cellassign_prob,most_recent_workflow,n_cells,processed_atac,passed_qc_tcc,tcc_pseudobulked,Core,Notes 1,Notes 2
0,GSM9302174,SRX31166360,"pituitary, ND_1",Normal_diet,0,Unclear,0,Guo et al. (2025),NaN,16 weeks,...,1.0,1.0,v_0.01,7298.0,NaN,NaN,NaN,2,NaN,NaN
1,GSM9302175,SRX31166361,"pituitary, ND_2",Normal_diet,0,Unclear,0,Guo et al. (2025),NaN,16 weeks,...,1.0,1.0,v_0.01,7530.0,NaN,NaN,NaN,2,NaN,NaN
2,NaN,SRX31798127,NaN,POMC-WT,1,C57BL/6J,0,Sochodolsky et al. (2026),NaN,386 days,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
3,NaN,SRX31798126,NaN,POMC-KO,0,C57BL/6J,0,Sochodolsky et al. (2026),NaN,376 and 386 days,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN

In [ ]:
atlas.sra_downloader(raw_path='/content/drive/MyDrive/pituitary_atlas/raw/',df=df)

Folder created
wget -P /content/drive/MyDrive/pituitary_atlas/raw/SRX31798126 /path/to/target/folder $(ffq --ncbi SRX31798126 | jq -r '.[] | .url' | tr '
' ' ')
Folder created
wget -P /content/drive/MyDrive/pituitary_atlas/raw/SRX31798127 /path/to/target/folder $(ffq --ncbi SRX31798127 | jq -r '.[] | .url' | tr '
' ' ')
SRA_ID already downloaded
SRA_ID already downloaded

In [ ]:
atlas.fastq_downloader(raw_path='/content/drive/MyDrive/pituitary_atlas/raw/',df=df)

SRR36812920.lite.1
SRR36812919.lite.1
SRR36123270.lite.1_1.fastq.gz
fastq files found
SRR36123270.lite.1_2.fastq.gz
fastq files found
SRR36123271.lite.1_1.fastq.gz
fastq files found
SRR36123271.lite.1_2.fastq.gz
fastq files found

In [ ]:
atlas.run_kb_count_nac("/content/drive/MyDrive/pituitary_atlas/processed/nac/","/content/drive/MyDrive/pituitary_atlas/raw/", df, species="mouse")

Running kb ref for nac
Running kb ref for std

        SRA_ID: SRX31166360
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX31166361
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX31798127
        experiment_type: sc
        tech: 10XV3

['/content/drive/MyDrive/pituitary_atlas/raw/SRX31798127/SRR36812919.lite.1', '/content/drive/MyDrive/pituitary_atlas/raw/SRX31798127/SRR36812919.lite.1_2.fastq.gz']
Running kb count
kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt -x 10XV3 --workflow=nac --sum=total --overwrite --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX31798127/ /content/drive/MyDrive/pituitary_atlas/raw/SRX31798127/SRR36812919.lite.1_1.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX31798127/SRR36812919.lite.1_2.fastq.gz
kb count -i index_std.idx -g t2g_std.txt --overwrite -x 10XV3 --tcc --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/tcc/ /content/drive/MyDrive/pituitary_atlas/raw/SRX31798127/SRR36812919.lite.1_1.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX31798127/SRR36812919.lite.1_2.fastq.gz

        SRA_ID: SRX31798126
        experiment_type: sc
        tech: 10XV3

['/content/drive/MyDrive/pituitary_atlas/raw/SRX31798126/SRR36812920.lite.1', '/content/drive/MyDrive/pituitary_atlas/raw/SRX31798126/SRR36812920.lite.1_2.fastq.gz']
Running kb count
kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt -x 10XV3 --workflow=nac --sum=total --overwrite --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX31798126/ /content/drive/MyDrive/pituitary_atlas/raw/SRX31798126/SRR36812920.lite.1_1.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX31798126/SRR36812920.lite.1_2.fastq.gz

#Also downloading Multiome onlist for the multiome datasets

In [ ]:
#donwload multiome onlist
!wget -P 10xMultiome/ https://teichlab.github.io/scg_lib_structs/data/10X-Genomics/gex_737K-arc-v1.txt.gz
!gunzip 10xMultiome/gex_737K-arc-v1.txt.gz

--2024-10-16 08:26:15--  https://teichlab.github.io/scg_lib_structs/data/10X-Genomics/gex_737K-arc-v1.txt.gz
Resolving teichlab.github.io (teichlab.github.io)... 185.199.111.153, 185.199.110.153, 185.199.108.153, ...
Connecting to teichlab.github.io (teichlab.github.io)|185.199.111.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2142553 (2.0M) [application/gzip]
Saving to: ‘10xMultiome/gex_737K-arc-v1.txt.gz’

gex_737K-arc-v1.txt 100%[===================>]   2.04M  --.-KB/s    in 0.07s

2024-10-16 08:26:15 (29.4 MB/s) - ‘10xMultiome/gex_737K-arc-v1.txt.gz’ saved [2142553/2142553]

# Run alignment

In [ ]:
atlas.run_kb_count_nac(nac_path='/content/drive/MyDrive/pituitary_atlas/processed/nac/',raw_path='/content/drive/MyDrive/pituitary_atlas/raw/',df=df)

        SRA_ID: SRX8489818
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: SRX8489819
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX8489820
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX8489821
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX8489822
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: SRX8489823
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX8489824
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX8489834
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX8489835
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX8489836
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX8489837
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX8489838
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX8489839
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX8489840
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX8489841
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX8489842
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX4736337
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: SRX4736338
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: SRX5292053
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: SRX6699502
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: SRX6699503
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: SRX7874737
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: SRX7874738
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: SRX7874739
        experiment_type: sc
        tech: DROPSEQ

SRA_ID already aligned for nac

        SRA_ID: SRX7874740
        experiment_type: sc
        tech: DROPSEQ

SRA_ID already aligned for nac

        SRA_ID: SRX7874741
        experiment_type: sc
        tech: DROPSEQ

SRA_ID already aligned for nac

        SRA_ID: SRX7874742
        experiment_type: sc
        tech: DROPSEQ

SRA_ID already aligned for nac

        SRA_ID: SRX7874743
        experiment_type: sc
        tech: DROPSEQ

SRA_ID already aligned for nac

        SRA_ID: SRX7874744
        experiment_type: sc
        tech: DROPSEQ

SRA_ID already aligned for nac

        SRA_ID: SRX7874745
        experiment_type: sc
        tech: DROPSEQ

SRA_ID already aligned for nac

        SRA_ID: SRX7874746
        experiment_type: sc
        tech: DROPSEQ

SRA_ID already aligned for nac

        SRA_ID: SRX9528564
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: SRX9528565
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: SRX21241798
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21241799
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21241800
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21241801
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: ERX4978537
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: ERX4978538
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: ERX4978539
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: ERX4978540
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: ERX4978541
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: ERX4978542
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: ERX4978543
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: ERX4978544
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: ERX7593481
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: ERX7593482
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: ERX7593483
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: ERX7593484
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21170823
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21170824
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21170825
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21986105
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21986106
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21986107
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21986108
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21986109
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21986110
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21986111
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21986112
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21986113
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21986114
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21986115
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21986116
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX13290057
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX13290058
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX13290059
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX13290060
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX13290061
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX13290062
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX18224104
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: SRX18224105
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: SRX18224106
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX18224107
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX18224108
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: SRX18224109
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: SRX15581370
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX15581371
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX8602211
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX8602212
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX8497092
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX8497093
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX8497094
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX9637224
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX20679984
        experiment_type: multi_rna
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX7377164
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: SRX7377166
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: SRX25532498
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: SRX25532499
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: SRX24151432
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX24151433
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX24151434
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX24151435
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX24151436
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX24151437
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX24151438
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX24151439
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX22219345
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: SRX22219346
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21636476
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21636477
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX25839820
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX25839821
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX19698102
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX19698101
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX19698100
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21902348
        experiment_type: multi_rna
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21902349
        experiment_type: multi_rna
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21902350
        experiment_type: multi_rna
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21902351
        experiment_type: multi_rna
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21902352
        experiment_type: multi_rna
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21902353
        experiment_type: multi_rna
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21902354
        experiment_type: multi_rna
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21902355
        experiment_type: multi_rna
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21902356
        experiment_type: multi_rna
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21902364
        experiment_type: multi_rna
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21902365
        experiment_type: multi_rna
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21902366
        experiment_type: multi_rna
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21902367
        experiment_type: multi_rna
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21902368
        experiment_type: multi_rna
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21902369
        experiment_type: multi_rna
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21902370
        experiment_type: multi_rna
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX18716672
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: SRX18716673
        experiment_type: sc
        tech: 10XV2

SRA_ID already aligned for nac

        SRA_ID: SRX18716674
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX18716675
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: ERX13202612
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: ERX13202613
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: ERX13202614
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: ERX13202615
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: ERX12265374
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: ERX12265375
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: ERX12265376
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: ERX12265377
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX25736219
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX25736220
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX25736221
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX25736222
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX25736223
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX25736224
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX25736225
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX25736226
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX25736227
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX25736228
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX25736229
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX26708357
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX25982294
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX25982295
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX25982296
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX25982297
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX25982298
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX25982301
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX25982300
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX25982299
        experiment_type: sc
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX29174027
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX29174028
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX29174029
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX29174030
        experiment_type: sn
        tech: 10XV3

SRA_ID already aligned for nac

        SRA_ID: SRX21168593
        experiment_type: sc
        tech: 10XV3

['/content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434594', '/content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434594_2.fastq.gz', '/content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434595', '/content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434595_2.fastq.gz', '/content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434596', '/content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434596_2.fastq.gz', '/content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434597', '/content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434597_2.fastq.gz']
Running kb count
kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt -x 10XV3 --workflow=nac --sum=total --overwrite --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/ /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434596_2.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434596_1.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434595_2.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434595_1.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434594_2.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434594_1.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434597_2.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434597_1.fastq.gz

        SRA_ID: SRX21168594
        experiment_type: sc
        tech: 10XV3

['/content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434590', '/content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434590_2.fastq.gz', '/content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434591_2.fastq.gz', '/content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434591', '/content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434592', '/content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434592_2.fastq.gz', '/content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434593', '/content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434593_2.fastq.gz']
Running kb count

# Alignment where files needed to be manually specified

In [ ]:
!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt -x 10XV3 --workflow=nac --sum=total --overwrite --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/ /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434596_1.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434596_2.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434595_1.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434595_2.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434594_1.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434594_2.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434597_1.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434597_2.fastq.gz

[2025-08-15 06:46:17,366]    INFO [count_nac] Using index index_nac.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/ from
[2025-08-15 06:46:17,366]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434596_1.fastq.gz
[2025-08-15 06:46:17,366]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434596_2.fastq.gz
[2025-08-15 06:46:17,366]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434595_1.fastq.gz
[2025-08-15 06:46:17,366]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434595_2.fastq.gz
[2025-08-15 06:46:17,366]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434594_1.fastq.gz
[2025-08-15 06:46:17,366]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434594_2.fastq.gz
[2025-08-15 06:46:17,366]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434597_1.fastq.gz
[2025-08-15 06:46:17,367]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168593/SRR25434597_2.fastq.gz
[2025-08-15 08:32:37,015]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/tmp/output.s.bus
[2025-08-15 08:38:52,876]    INFO [count_nac] On-list not provided
[2025-08-15 08:38:52,877]    INFO [count_nac] Copying pre-packaged 10XV3 on-list to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/
[2025-08-15 08:38:53,797]    INFO [count_nac] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/tmp/output.s.bus
[2025-08-15 08:40:38,357]    INFO [count_nac] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/10x_version3_whitelist.txt
[2025-08-15 08:42:49,463]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/output.unfiltered.bus
[2025-08-15 08:48:26,403]    INFO [count_nac] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/counts_unfiltered/cells_x_genes from BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/output.unfiltered.bus
[2025-08-15 08:52:12,692]    INFO [count_nac] Writing gene names to file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/counts_unfiltered/cells_x_genes.genes.names.txt
[2025-08-15 08:52:12,951] WARNING [count_nac] 1599 gene IDs do not have corresponding valid gene names. These genes will use their gene IDs instead.
[2025-08-15 08:52:12,989]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/counts_unfiltered/cells_x_genes.cell.mtx
[2025-08-15 08:53:10,832]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/counts_unfiltered/cells_x_genes.cell.mtx
[2025-08-15 08:54:12,443]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/counts_unfiltered/cells_x_genes.nucleus.mtx
[2025-08-15 08:55:06,794]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/counts_unfiltered/cells_x_genes.nucleus.mtx
[2025-08-15 08:56:11,340]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/counts_unfiltered/cells_x_genes.total.mtx
[2025-08-15 08:57:02,158]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/counts_unfiltered/cells_x_genes.total.mtx
[2025-08-15 08:58:20,196]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/counts_unfiltered/cells_x_genes.mature.mtx
[2025-08-15 08:58:27,229]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/counts_unfiltered/cells_x_genes.nascent.mtx
[2025-08-15 08:58:32,366]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/counts_unfiltered/cells_x_genes.ambiguous.mtx
[2025-08-15 08:58:38,495]    INFO [count_nac] Combining matrices
[2025-08-15 08:58:43,350]    INFO [count_nac] Writing matrices to h5ad /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168593/counts_unfiltered/adata.h5ad

In [ ]:
!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt -x 10XV3 --workflow=nac --sum=total --overwrite --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/ /content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434590_1.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434590_2.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434593_1.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434593_2.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434592_1.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434592_2.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434591_1.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434591_2.fastq.gz

[2025-08-15 08:59:11,256]    INFO [count_nac] Using index index_nac.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/ from
[2025-08-15 08:59:11,256]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434590_1.fastq.gz
[2025-08-15 08:59:11,256]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434590_2.fastq.gz
[2025-08-15 08:59:11,256]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434593_1.fastq.gz
[2025-08-15 08:59:11,256]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434593_2.fastq.gz
[2025-08-15 08:59:11,256]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434592_1.fastq.gz
[2025-08-15 08:59:11,256]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434592_2.fastq.gz
[2025-08-15 08:59:11,256]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434591_1.fastq.gz
[2025-08-15 08:59:11,257]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168594/SRR25434591_2.fastq.gz
[2025-08-15 11:11:18,462]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/tmp/output.s.bus
[2025-08-15 11:16:39,880]    INFO [count_nac] On-list not provided
[2025-08-15 11:16:39,881]    INFO [count_nac] Copying pre-packaged 10XV3 on-list to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/
[2025-08-15 11:16:40,782]    INFO [count_nac] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/tmp/output.s.bus
[2025-08-15 11:18:27,574]    INFO [count_nac] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/10x_version3_whitelist.txt
[2025-08-15 11:20:32,188]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/output.unfiltered.bus
[2025-08-15 11:25:51,799]    INFO [count_nac] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/counts_unfiltered/cells_x_genes from BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/output.unfiltered.bus
[2025-08-15 11:29:44,758]    INFO [count_nac] Writing gene names to file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/counts_unfiltered/cells_x_genes.genes.names.txt
[2025-08-15 11:29:45,037] WARNING [count_nac] 1599 gene IDs do not have corresponding valid gene names. These genes will use their gene IDs instead.
[2025-08-15 11:29:45,080]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/counts_unfiltered/cells_x_genes.cell.mtx
[2025-08-15 11:30:36,324]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/counts_unfiltered/cells_x_genes.cell.mtx
[2025-08-15 11:31:37,058]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/counts_unfiltered/cells_x_genes.nucleus.mtx
[2025-08-15 11:32:18,166]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/counts_unfiltered/cells_x_genes.nucleus.mtx
[2025-08-15 11:33:22,806]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/counts_unfiltered/cells_x_genes.total.mtx
[2025-08-15 11:34:27,148]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/counts_unfiltered/cells_x_genes.total.mtx
[2025-08-15 11:35:46,951]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/counts_unfiltered/cells_x_genes.mature.mtx
[2025-08-15 11:35:53,744]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/counts_unfiltered/cells_x_genes.nascent.mtx
[2025-08-15 11:36:08,150]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/counts_unfiltered/cells_x_genes.ambiguous.mtx
[2025-08-15 11:36:16,146]    INFO [count_nac] Combining matrices
[2025-08-15 11:36:21,606]    INFO [count_nac] Writing matrices to h5ad /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168594/counts_unfiltered/adata.h5ad

In [ ]:
!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt -x 10XV3 --workflow=nac --sum=total --overwrite --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/ /content/drive/MyDrive/pituitary_atlas/raw/SRX21168595/SRR25434586_1.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168595/SRR25434586_2.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168595/SRR25434587_1.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168595/SRR25434587_2.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168595/SRR25434588_1.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168595/SRR25434588_2.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168595/SRR25434589_1.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168595/SRR25434589_2.fastq.gz

[2025-08-15 12:00:07,849]    INFO [count_nac] Using index index_nac.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/ from
[2025-08-15 12:00:07,850]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168595/SRR25434586_1.fastq.gz
[2025-08-15 12:00:07,850]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168595/SRR25434586_2.fastq.gz
[2025-08-15 12:00:07,850]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168595/SRR25434587_1.fastq.gz
[2025-08-15 12:00:07,850]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168595/SRR25434587_2.fastq.gz
[2025-08-15 12:00:07,850]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168595/SRR25434588_1.fastq.gz
[2025-08-15 12:00:07,850]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168595/SRR25434588_2.fastq.gz
[2025-08-15 12:00:07,850]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168595/SRR25434589_1.fastq.gz
[2025-08-15 12:00:07,850]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168595/SRR25434589_2.fastq.gz
[2025-08-15 13:55:09,328]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/tmp/output.s.bus
[2025-08-15 13:59:09,815]    INFO [count_nac] On-list not provided
[2025-08-15 13:59:09,816]    INFO [count_nac] Copying pre-packaged 10XV3 on-list to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/
[2025-08-15 13:59:10,674]    INFO [count_nac] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/tmp/output.s.bus
[2025-08-15 14:01:32,219]    INFO [count_nac] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/10x_version3_whitelist.txt
[2025-08-15 14:03:43,264]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/output.unfiltered.bus
[2025-08-15 14:07:43,965]    INFO [count_nac] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/counts_unfiltered/cells_x_genes from BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/output.unfiltered.bus
[2025-08-15 14:11:19,626]    INFO [count_nac] Writing gene names to file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/counts_unfiltered/cells_x_genes.genes.names.txt
[2025-08-15 14:11:19,880] WARNING [count_nac] 1599 gene IDs do not have corresponding valid gene names. These genes will use their gene IDs instead.
[2025-08-15 14:11:19,918]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/counts_unfiltered/cells_x_genes.cell.mtx
[2025-08-15 14:12:05,221]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/counts_unfiltered/cells_x_genes.cell.mtx
[2025-08-15 14:12:55,569]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/counts_unfiltered/cells_x_genes.nucleus.mtx
[2025-08-15 14:13:32,246]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/counts_unfiltered/cells_x_genes.nucleus.mtx
[2025-08-15 14:14:48,854]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/counts_unfiltered/cells_x_genes.total.mtx
[2025-08-15 14:15:33,608]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/counts_unfiltered/cells_x_genes.total.mtx
[2025-08-15 14:16:42,467]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/counts_unfiltered/cells_x_genes.mature.mtx
[2025-08-15 14:16:48,417]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/counts_unfiltered/cells_x_genes.nascent.mtx
[2025-08-15 14:16:53,085]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/counts_unfiltered/cells_x_genes.ambiguous.mtx
[2025-08-15 14:16:59,324]    INFO [count_nac] Combining matrices
[2025-08-15 14:17:04,183]    INFO [count_nac] Writing matrices to h5ad /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168595/counts_unfiltered/adata.h5ad

In [ ]:
!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt -x 10XV3 --workflow=nac --sum=total --overwrite --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/ /content/drive/MyDrive/pituitary_atlas/raw/SRX21168596/SRR25434582_1.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168596/SRR25434582_2.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168596/SRR25434583_1.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168596/SRR25434583_2.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168596/SRR25434584_1.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168596/SRR25434584_2.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168596/SRR25434585_1.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX21168596/SRR25434585_2.fastq.gz

[2025-08-15 16:59:15,396]    INFO [count_nac] Using index index_nac.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/ from
[2025-08-15 16:59:15,396]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168596/SRR25434582_1.fastq.gz
[2025-08-15 16:59:15,397]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168596/SRR25434582_2.fastq.gz
[2025-08-15 16:59:15,397]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168596/SRR25434583_1.fastq.gz
[2025-08-15 16:59:15,397]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168596/SRR25434583_2.fastq.gz
[2025-08-15 16:59:15,397]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168596/SRR25434584_1.fastq.gz
[2025-08-15 16:59:15,397]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168596/SRR25434584_2.fastq.gz
[2025-08-15 16:59:15,397]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168596/SRR25434585_1.fastq.gz
[2025-08-15 16:59:15,397]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX21168596/SRR25434585_2.fastq.gz
[2025-08-15 19:03:27,631]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/tmp/output.s.bus
[2025-08-15 19:08:46,726]    INFO [count_nac] On-list not provided
[2025-08-15 19:08:46,727]    INFO [count_nac] Copying pre-packaged 10XV3 on-list to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/
[2025-08-15 19:08:49,180]    INFO [count_nac] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/tmp/output.s.bus
[2025-08-15 19:09:56,867]    INFO [count_nac] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/10x_version3_whitelist.txt
[2025-08-15 19:12:45,092]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/output.unfiltered.bus
[2025-08-15 19:17:46,661]    INFO [count_nac] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/counts_unfiltered/cells_x_genes from BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/output.unfiltered.bus
[2025-08-15 19:21:22,158]    INFO [count_nac] Writing gene names to file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/counts_unfiltered/cells_x_genes.genes.names.txt
[2025-08-15 19:21:22,731] WARNING [count_nac] 1599 gene IDs do not have corresponding valid gene names. These genes will use their gene IDs instead.
[2025-08-15 19:21:23,453]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/counts_unfiltered/cells_x_genes.cell.mtx
[2025-08-15 19:22:39,948]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/counts_unfiltered/cells_x_genes.cell.mtx
[2025-08-15 19:23:39,643]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/counts_unfiltered/cells_x_genes.nucleus.mtx
[2025-08-15 19:24:23,271]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/counts_unfiltered/cells_x_genes.nucleus.mtx
[2025-08-15 19:25:26,271]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/counts_unfiltered/cells_x_genes.total.mtx
[2025-08-15 19:26:17,267]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/counts_unfiltered/cells_x_genes.total.mtx
[2025-08-15 19:27:30,953]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/counts_unfiltered/cells_x_genes.mature.mtx
[2025-08-15 19:27:35,780]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/counts_unfiltered/cells_x_genes.nascent.mtx
[2025-08-15 19:27:39,435]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/counts_unfiltered/cells_x_genes.ambiguous.mtx
[2025-08-15 19:27:43,632]    INFO [count_nac] Combining matrices
[2025-08-15 19:27:47,878]    INFO [count_nac] Writing matrices to h5ad /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/counts_unfiltered/adata.h5ad

# Cheung et al (2018) uploaded strange fastq files, and therefore we turned to the .bam files and aimed to convert those back to fastq files using the 10X bamtofastq tool.

In [ ]:
import os

# Ensure the destination directory exists
output_dir = "/content/drive/MyDrive/pituitary_atlas/raw/SRX4736337"
os.makedirs(output_dir, exist_ok=True)
# URL of the file to be downloaded
url = "https://sra-pub-src-1.s3.amazonaws.com/SRR7898909/pool1_possorted_genome_bam.bam.1"
# Path where the file will be saved
output_file_path = os.path.join(output_dir, "pool1_possorted_genome_bam.bam.1")
# Use wget to download the file
!wget -O {output_file_path} {url}
print(f"Downloaded file to {output_file_path}")

url2 = "https://sra-pub-src-1.s3.amazonaws.com/SRR7898910/pool2_possorted_genome_bam.bam.1"
output_dir = "/content/drive/MyDrive/pituitary_atlas/raw/SRX4736338"
output_file_path2 = os.path.join(output_dir, "pool2_possorted_genome_bam.bam.1")
!wget -O {output_file_path2} {url2}
print(f"Downloaded file to {output_file_path2}")

--2024-07-08 09:41:48--  https://sra-pub-src-1.s3.amazonaws.com/SRR7898909/pool1_possorted_genome_bam.bam.1
Resolving sra-pub-src-1.s3.amazonaws.com (sra-pub-src-1.s3.amazonaws.com)... 52.216.220.169, 3.5.30.143, 52.216.186.235, ...
Connecting to sra-pub-src-1.s3.amazonaws.com (sra-pub-src-1.s3.amazonaws.com)|52.216.220.169|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 29532119570 (28G) [application/x-troff-man]
Saving to: ‘/content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/pool1_possorted_genome_bam.bam.1’

/content/drive/MyDr 100%[===================>]  27.50G  54.4MB/s    in 9m 56s

2024-07-08 09:51:45 (47.2 MB/s) - ‘/content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/pool1_possorted_genome_bam.bam.1’ saved [29532119570/29532119570]

Downloaded file to /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/pool1_possorted_genome_bam.bam.1
--2024-07-08 09:51:47--  https://sra-pub-src-1.s3.amazonaws.com/SRR7898910/pool2_possorted_genome_bam.bam.1
Resolving sra-pub-src-1.s3.amazonaws.com (sra-pub-src-1.s3.amazonaws.com)... 52.216.43.161, 52.217.169.129, 52.216.184.27, ...
Connecting to sra-pub-src-1.s3.amazonaws.com (sra-pub-src-1.s3.amazonaws.com)|52.216.43.161|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 35721801699 (33G) [application/x-troff-man]
Saving to: ‘/content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/pool2_possorted_genome_bam.bam.1’

/content/drive/MyDr 100%[===================>]  33.27G  50.0MB/s    in 12m 2s

2024-07-08 10:03:49 (47.2 MB/s) - ‘/content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/pool2_possorted_genome_bam.bam.1’ saved [35721801699/35721801699]

Downloaded file to /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/pool2_possorted_genome_bam.bam.1

In [ ]:
!bamtofastq /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/pool1_possorted_genome_bam.bam.1 /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs

bamtofastq v1.4.1
Writing finished.  Observed 273079474 read pairs. Wrote 273079474 read pairs

In [ ]:
!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt --overwrite -x 10xv2 --workflow=nac --sum=total --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/ /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_003.fastq.gz

[2024-07-08 11:07:41,292]    INFO [count_nac] Using index index_nac.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/ from
[2024-07-08 11:07:41,292]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_001.fastq.gz
[2024-07-08 11:07:41,292]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_001.fastq.gz
[2024-07-08 11:07:41,292]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_002.fastq.gz
[2024-07-08 11:07:41,292]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_002.fastq.gz
[2024-07-08 11:07:41,292]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_003.fastq.gz
[2024-07-08 11:07:41,292]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_003.fastq.gz
[2024-07-08 11:07:41,292]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_001.fastq.gz
[2024-07-08 11:07:41,292]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_001.fastq.gz
[2024-07-08 11:07:41,292]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_002.fastq.gz
[2024-07-08 11:07:41,292]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_002.fastq.gz
[2024-07-08 11:07:41,292]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_003.fastq.gz
[2024-07-08 11:07:41,292]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_003.fastq.gz
[2024-07-08 11:52:19,760]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/tmp/output.s.bus
[2024-07-08 11:55:02,402]    INFO [count_nac] On-list not provided
[2024-07-08 11:55:02,402]    INFO [count_nac] Copying pre-packaged 10XV2 on-list to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/
[2024-07-08 11:55:02,562]    INFO [count_nac] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/tmp/output.s.bus
[2024-07-08 11:55:24,309]    INFO [count_nac] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/10x_version2_whitelist.txt
[2024-07-08 11:56:38,768]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/output.unfiltered.bus
[2024-07-08 11:57:10,942]    INFO [count_nac] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/counts_unfiltered/cells_x_genes from BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/output.unfiltered.bus
[2024-07-08 12:00:32,199]    INFO [count_nac] Writing gene names to file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/counts_unfiltered/cells_x_genes.genes.names.txt
[2024-07-08 12:00:32,558] WARNING [count_nac] 1599 gene IDs do not have corresponding valid gene names. These genes will use their gene IDs instead.
[2024-07-08 12:00:32,610]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/counts_unfiltered/cells_x_genes.cell.mtx
[2024-07-08 12:01:09,054]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/counts_unfiltered/cells_x_genes.cell.mtx
[2024-07-08 12:01:59,918]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/counts_unfiltered/cells_x_genes.nucleus.mtx
[2024-07-08 12:02:40,225]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/counts_unfiltered/cells_x_genes.nucleus.mtx
[2024-07-08 12:03:34,359]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/counts_unfiltered/cells_x_genes.total.mtx
[2024-07-08 12:04:19,448]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/counts_unfiltered/cells_x_genes.total.mtx
[2024-07-08 12:05:21,542]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/counts_unfiltered/cells_x_genes.mature.mtx
[2024-07-08 12:05:30,101]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/counts_unfiltered/cells_x_genes.nascent.mtx
[2024-07-08 12:05:40,698]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/counts_unfiltered/cells_x_genes.ambiguous.mtx
[2024-07-08 12:06:05,917]    INFO [count_nac] Combining matrices
[2024-07-08 12:06:07,110]    INFO [count_nac] Writing matrices to h5ad /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736337/counts_unfiltered/adata.h5ad

In [ ]:
!bamtofastq /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/pool2_possorted_genome_bam.bam.1 /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs

In [ ]:
!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt --overwrite -x 10xv2 --workflow=nac --sum=total --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736338/ /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_004.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_004.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_004.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_004.fastq.gz

[2024-07-08 14:33:44,870]    INFO [count_nac] Using index index_nac.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736338/ from
[2024-07-08 14:33:44,870]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_001.fastq.gz
[2024-07-08 14:33:44,870]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_001.fastq.gz
[2024-07-08 14:33:44,870]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_002.fastq.gz
[2024-07-08 14:33:44,870]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_002.fastq.gz
[2024-07-08 14:33:44,870]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_003.fastq.gz
[2024-07-08 14:33:44,870]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_003.fastq.gz
[2024-07-08 14:33:44,870]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_004.fastq.gz
[2024-07-08 14:33:44,870]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_004.fastq.gz
[2024-07-08 14:33:44,870]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_001.fastq.gz
[2024-07-08 14:33:44,871]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_001.fastq.gz
[2024-07-08 14:33:44,871]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_002.fastq.gz
[2024-07-08 14:33:44,871]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_002.fastq.gz
[2024-07-08 14:33:44,871]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_003.fastq.gz
[2024-07-08 14:33:44,871]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_003.fastq.gz
[2024-07-08 14:33:44,871]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_004.fastq.gz
[2024-07-08 14:33:44,871]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_004.fastq.gz
[2024-07-08 15:29:42,636]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736338/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736338/tmp/output.s.bus
[2024-07-08 15:33:10,222]    INFO [count_nac] On-list not provided
[2024-07-08 15:33:10,223]    INFO [count_nac] Copying pre-packaged 10XV2 on-list to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736338/
[2024-07-08 15:33:10,369]    INFO [count_nac] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736338/tmp/output.s.bus
[2024-07-08 15:33:38,430]    INFO [count_nac] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736338/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736338/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736338/10x_version2_whitelist.txt
[2024-07-08 15:35:09,224]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736338/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX4736338/output.unfiltered.bus

# Same for Bastedo et al

In [ ]:
import os

# Ensure the destination directory exists
output_dir = "/content/drive/MyDrive/pituitary_atlas/raw/SRX9637224"
os.makedirs(output_dir, exist_ok=True)
# URL of the file to be downloaded
url = "https://sra-pub-src-1.s3.amazonaws.com/SRR13203971/Pit_possorted_genome_bam.bam.1"
# Path where the file will be saved
output_file_path = os.path.join(output_dir, "pool1_possorted_genome_bam.bam.1")
# Use wget to download the file
!wget -O {output_file_path} {url}
print(f"Downloaded file to {output_file_path}")

--2024-08-03 15:02:57--  https://sra-pub-src-1.s3.amazonaws.com/SRR13203971/Pit_possorted_genome_bam.bam.1
Resolving sra-pub-src-1.s3.amazonaws.com (sra-pub-src-1.s3.amazonaws.com)... 3.5.30.241, 54.231.171.169, 52.216.28.156, ...
Connecting to sra-pub-src-1.s3.amazonaws.com (sra-pub-src-1.s3.amazonaws.com)|3.5.30.241|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 40072014800 (37G) [binary/octet-stream]
Saving to: ‘/content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/pool1_possorted_genome_bam.bam.1’

/content/drive/MyDr 100%[===================>]  37.32G  22.4MB/s    in 27m 13s

2024-08-03 15:30:10 (23.4 MB/s) - ‘/content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/pool1_possorted_genome_bam.bam.1’ saved [40072014800/40072014800]

Downloaded file to /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/pool1_possorted_genome_bam.bam.1

In [ ]:
!bamtofastq /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/pool1_possorted_genome_bam.bam.1 /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs

bamtofastq v1.4.1
Writing finished.  Observed 576030445 read pairs. Wrote 576030445 read pairs

In [ ]:
!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt --overwrite -x 10XV3 --workflow=nac --sum=total --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/ /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R2_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R2_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R2_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R2_003.fastq.gz

[2024-08-11 15:30:12,030]    INFO [count_nac] Using index index_nac.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/ from
[2024-08-11 15:30:12,030]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R1_001.fastq.gz
[2024-08-11 15:30:12,030]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R2_001.fastq.gz
[2024-08-11 15:30:12,030]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R1_002.fastq.gz
[2024-08-11 15:30:12,030]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R2_002.fastq.gz
[2024-08-11 15:30:12,030]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R1_003.fastq.gz
[2024-08-11 15:30:12,030]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R2_003.fastq.gz
[2024-08-11 15:30:12,030]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R1_001.fastq.gz
[2024-08-11 15:30:12,030]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R2_001.fastq.gz
[2024-08-11 15:30:12,030]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R1_002.fastq.gz
[2024-08-11 15:30:12,030]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R2_002.fastq.gz
[2024-08-11 15:30:12,030]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R1_003.fastq.gz
[2024-08-11 15:30:12,030]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R2_003.fastq.gz
[2024-08-11 15:30:12,031]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R1_001.fastq.gz
[2024-08-11 15:30:12,031]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R2_001.fastq.gz
[2024-08-11 15:30:12,031]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R1_002.fastq.gz
[2024-08-11 15:30:12,031]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R2_002.fastq.gz
[2024-08-11 15:30:12,031]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R1_003.fastq.gz
[2024-08-11 15:30:12,031]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R2_003.fastq.gz
[2024-08-11 15:30:12,031]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R1_001.fastq.gz
[2024-08-11 15:30:12,031]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R2_001.fastq.gz
[2024-08-11 15:30:12,031]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R1_002.fastq.gz
[2024-08-11 15:30:12,031]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R2_002.fastq.gz
[2024-08-11 15:30:12,031]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R1_003.fastq.gz
[2024-08-11 15:30:12,031]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R2_003.fastq.gz
[2024-08-11 15:59:40,364]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/tmp/output.s.bus
[2024-08-11 16:02:44,718]    INFO [count_nac] On-list not provided
[2024-08-11 16:02:44,719]    INFO [count_nac] Copying pre-packaged 10XV3 on-list to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/
[2024-08-11 16:02:45,466]    INFO [count_nac] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/tmp/output.s.bus
[2024-08-11 16:03:49,215]    INFO [count_nac] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/10x_version3_whitelist.txt
[2024-08-11 16:05:29,712]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/output.unfiltered.bus
[2024-08-11 16:07:34,861]    INFO [count_nac] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/counts_unfiltered/cells_x_genes from BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/output.unfiltered.bus
[2024-08-11 16:13:24,868]    INFO [count_nac] Writing gene names to file /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/counts_unfiltered/cells_x_genes.genes.names.txt
[2024-08-11 16:13:25,071] WARNING [count_nac] 1599 gene IDs do not have corresponding valid gene names. These genes will use their gene IDs instead.
[2024-08-11 16:13:25,102]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/counts_unfiltered/cells_x_genes.cell.mtx
[2024-08-11 16:14:09,103]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/counts_unfiltered/cells_x_genes.cell.mtx
[2024-08-11 16:15:02,487]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/counts_unfiltered/cells_x_genes.nucleus.mtx
[2024-08-11 16:15:42,551]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/counts_unfiltered/cells_x_genes.nucleus.mtx
[2024-08-11 16:16:35,617]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/counts_unfiltered/cells_x_genes.total.mtx
[2024-08-11 16:17:17,141]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/counts_unfiltered/cells_x_genes.total.mtx
[2024-08-11 16:18:14,866]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/counts_unfiltered/cells_x_genes.mature.mtx
[2024-08-11 16:18:17,744]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/counts_unfiltered/cells_x_genes.nascent.mtx
[2024-08-11 16:18:20,325]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/counts_unfiltered/cells_x_genes.ambiguous.mtx
[2024-08-11 16:18:23,766]    INFO [count_nac] Combining matrices
[2024-08-11 16:18:25,916]    INFO [count_nac] Writing matrices to h5ad /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX9637224/counts_unfiltered/adata.h5ad

# Now Cheung 2020

In [ ]:
import os

# Ensure the destination directory exists
output_dir = "/content/drive/MyDrive/pituitary_atlas/raw/SRX7377164"
os.makedirs(output_dir, exist_ok=True)
# URL of the file to be downloaded
url = "https://sra-pub-src-2.s3.amazonaws.com/SRR10700816/Hesx1Cre_possorted_genome_bam.bam.1"
# Path where the file will be saved
output_file_path = os.path.join(output_dir, "pool1_possorted_genome_bam.bam.1")
# Use wget to download the file
!wget -O {output_file_path} {url}
print(f"Downloaded file to {output_file_path}")

url2 = "https://sra-pub-src-2.s3.amazonaws.com/SRR10700818/Hesx1Cre_dnRAR_possorted_genome_bam.bam.1"
output_dir = "/content/drive/MyDrive/pituitary_atlas/raw/SRX7377166"
output_file_path2 = os.path.join(output_dir, "pool2_possorted_genome_bam.bam.1")
!wget -O {output_file_path2} {url2}
print(f"Downloaded file to {output_file_path2}")

In [ ]:
!bamtofastq /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/pool1_possorted_genome_bam.bam.1 /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs

In [ ]:
!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt --overwrite -x 10xv2 --workflow=nac --sum=total --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX7377164/ /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_004.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_004.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_004.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_004.fastq.gz

In [ ]:
!bamtofastq /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/pool2_possorted_genome_bam.bam.1 /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs

In [ ]:
!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt --overwrite -x 10xv2 --workflow=nac --sum=total --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX7377166/ /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_004.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_004.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_004.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_004.fastq.gz

# Found strange fastq files in De Vriendt et al. (2025) using SRA so getting files from arrayexpress instead.

In [ ]:
ftp_links = [
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892994/scrEXT356_mm10_S19_L001_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892995/scrEXT356_mm10_S3_L001_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892996/scrEXT356_mm10_S19_L002_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892996/scrEXT356_mm10_S19_L002_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892994/scrEXT356_mm10_S19_L001_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892995/scrEXT356_mm10_S3_L001_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892995/scrEXT356_mm10_S3_L001_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892994/scrEXT356_mm10_S19_L001_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892996/scrEXT356_mm10_S19_L002_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892998/scrEXT357_mm10_S4_L001_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12893000/scrEXT357_mm10_S20_L001_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12893000/scrEXT357_mm10_S20_L001_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892998/scrEXT357_mm10_S4_L001_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892991/scrEXT357_mm10_S20_L002_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892991/scrEXT357_mm10_S20_L002_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12893000/scrEXT357_mm10_S20_L001_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892991/scrEXT357_mm10_S20_L002_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892998/scrEXT357_mm10_S4_L001_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892993/scrEXT358_mm10_S11_L001_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892993/scrEXT358_mm10_S11_L001_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892993/scrEXT358_mm10_S11_L001_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892997/scrEXT364_mm10_S6_L002_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892988/scrEXT364_mm10_S6_L003_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892990/scrEXT364_mm10_S10_L002_I2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892988/scrEXT364_mm10_S6_L003_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892990/scrEXT364_mm10_S10_L002_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892992/scrEXT364_mm10_S10_L001_I2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892989/scrEXT364_mm10_S6_L001_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892999/scrEXT364_mm10_S6_L004_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892989/scrEXT364_mm10_S6_L001_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892992/scrEXT364_mm10_S10_L001_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892988/scrEXT364_mm10_S6_L003_I2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892990/scrEXT364_mm10_S10_L002_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892988/scrEXT364_mm10_S6_L003_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892989/scrEXT364_mm10_S6_L001_I2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892999/scrEXT364_mm10_S6_L004_I2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892997/scrEXT364_mm10_S6_L002_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892992/scrEXT364_mm10_S10_L001_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892989/scrEXT364_mm10_S6_L001_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892999/scrEXT364_mm10_S6_L004_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892997/scrEXT364_mm10_S6_L002_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892999/scrEXT364_mm10_S6_L004_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892990/scrEXT364_mm10_S10_L002_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892992/scrEXT364_mm10_S10_L001_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR128/ERR12892997/scrEXT364_mm10_S6_L002_I2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801862/scrEXT330_mm10_S1_L004_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801843/scrEXT330_mm10_S5_L001_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801862/scrEXT330_mm10_S1_L004_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801842/scrEXT330_mm10_S5_L002_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801856/scrEXT330_mm10_S1_L002_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801861/scrEXT330_mm10_S31_L002_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801856/scrEXT330_mm10_S1_L002_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801852/scrEXT330_mm10_S31_L001_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801856/scrEXT330_mm10_S1_L002_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801861/scrEXT330_mm10_S31_L002_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801846/scrEXT330_mm10_S1_L003_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801843/scrEXT330_mm10_S5_L001_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801861/scrEXT330_mm10_S31_L002_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801848/scrEXT330_mm10_S1_L001_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801852/scrEXT330_mm10_S31_L001_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801842/scrEXT330_mm10_S5_L002_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801846/scrEXT330_mm10_S1_L003_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801843/scrEXT330_mm10_S5_L001_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801848/scrEXT330_mm10_S1_L001_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801852/scrEXT330_mm10_S31_L001_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801848/scrEXT330_mm10_S1_L001_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801862/scrEXT330_mm10_S1_L004_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801842/scrEXT330_mm10_S5_L002_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801846/scrEXT330_mm10_S1_L003_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801855/scrEXT331_mm10_S2_L004_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801849/scrEXT331_mm10_S6_L002_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801857/scrEXT331_mm10_S2_L003_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801863/scrEXT331_mm10_S32_L002_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801857/scrEXT331_mm10_S2_L003_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801850/scrEXT331_mm10_S6_L001_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801858/scrEXT331_mm10_S2_L001_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801849/scrEXT331_mm10_S6_L002_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801859/scrEXT331_mm10_S2_L002_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801863/scrEXT331_mm10_S32_L002_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801859/scrEXT331_mm10_S2_L002_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801853/scrEXT331_mm10_S32_L001_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801855/scrEXT331_mm10_S2_L004_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801850/scrEXT331_mm10_S6_L001_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801859/scrEXT331_mm10_S2_L002_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801863/scrEXT331_mm10_S32_L002_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801855/scrEXT331_mm10_S2_L004_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801857/scrEXT331_mm10_S2_L003_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801850/scrEXT331_mm10_S6_L001_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801858/scrEXT331_mm10_S2_L001_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801853/scrEXT331_mm10_S32_L001_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801849/scrEXT331_mm10_S6_L002_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801858/scrEXT331_mm10_S2_L001_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801853/scrEXT331_mm10_S32_L001_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801841/scrEXT352_mm10_S15_L001_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801844/scrEXT352_mm10_S8_L002_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801845/scrEXT352_mm10_S8_L001_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801844/scrEXT352_mm10_S8_L002_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801841/scrEXT352_mm10_S15_L001_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801841/scrEXT352_mm10_S15_L001_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801845/scrEXT352_mm10_S8_L001_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801854/scrEXT352_mm10_S15_L002_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801854/scrEXT352_mm10_S15_L002_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801854/scrEXT352_mm10_S15_L002_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801845/scrEXT352_mm10_S8_L001_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801844/scrEXT352_mm10_S8_L002_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801847/scrEXT353_mm10_S16_L001_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801851/scrEXT353_mm10_S16_L002_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801840/scrEXT353_mm10_S9_L002_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801847/scrEXT353_mm10_S16_L001_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801860/scrEXT353_mm10_S9_L001_R2_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801847/scrEXT353_mm10_S16_L001_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801847/scrEXT353_mm10_S16_L001_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801851/scrEXT353_mm10_S16_L002_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801840/scrEXT353_mm10_S9_L002_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801851/scrEXT353_mm10_S16_L002_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801860/scrEXT353_mm10_S9_L001_I1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801860/scrEXT353_mm10_S9_L001_R1_001.fastq.gz",
    "ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR138/ERR13801840/scrEXT353_mm10_S9_L002_I1_001.fastq.gz"
]
ftp_urls = list(set(ftp_links))

In [ ]:
import os
import shutil
from ftplib import FTP
from urllib.parse import urlparse
from concurrent.futures import ThreadPoolExecutor
import gzip
from typing import List, Dict
import logging
from pathlib import Path
import time

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Directory setup
local_directory = '/content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/'
Path(local_directory).mkdir(parents=True, exist_ok=True)

# Clear directory contents if it exists
for item in os.listdir(local_directory):
    item_path = os.path.join(local_directory, item)
    if os.path.isfile(item_path):
        os.unlink(item_path)
    elif os.path.isdir(item_path):
        shutil.rmtree(item_path)



def download_file(url: str) -> Dict:
    """
    Download a single file from FTP server with error handling and retries
    """
    parsed_url = urlparse(url)
    filename = os.path.basename(parsed_url.path)
    local_path = os.path.join(local_directory, filename)

    max_retries = 3
    retry_delay = 5  # seconds

    for attempt in range(max_retries):
        try:
            with FTP(parsed_url.netloc) as ftp:
                ftp.login()  # anonymous login

                # Download file
                with open(local_path, 'wb') as f:
                    ftp.retrbinary(f'RETR {parsed_url.path}', f.write)

                # Verify gzip integrity
                try:
                    with gzip.open(local_path, 'rb') as f:
                        f.read(1)  # Try reading first byte to verify gzip integrity
                except Exception as e:
                    os.remove(local_path)  # Remove corrupted file
                    raise ValueError(f"Invalid gzip file: {str(e)}")

                logging.info(f"Successfully downloaded: {filename}")
                return {"success": True, "filename": filename}

        except Exception as e:
            if attempt < max_retries - 1:
                logging.warning(f"Attempt {attempt + 1} failed for {filename}: {str(e)}. Retrying...")
                time.sleep(retry_delay * (attempt + 1))  # Exponential backoff
            else:
                logging.error(f"Failed to download {filename} after {max_retries} attempts: {str(e)}")
                # Clean up any partial downloads
                if os.path.exists(local_path):
                    os.remove(local_path)
                return {"success": False, "filename": filename, "error": str(e)}

def main():
    # Create a thread pool for parallel downloads
    max_workers = 4  # Adjust based on available resources
    results = []

    logging.info(f"Starting download of {len(ftp_urls)} files...")

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        future_to_url = {executor.submit(download_file, url): url for url in ftp_urls}

        for future in future_to_url:
            try:
                result = future.result()
                results.append(result)
            except Exception as e:
                url = future_to_url[future]
                logging.error(f"Unexpected error for {url}: {str(e)}")
                results.append({"success": False, "filename": url, "error": str(e)})

    # Summary
    successful = sum(1 for r in results if r["success"])
    failed = len(results) - successful

    logging.info(f"\nDownload Summary:")
    logging.info(f"Successful downloads: {successful}")
    logging.info(f"Failed downloads: {failed}")

    if failed > 0:
        logging.info("\nFailed files:")
        for result in results:
            if not result["success"]:
                logging.info(f"- {result['filename']}: {result.get('error', 'Unknown error')}")

if __name__ == "__main__":
    main()

KeyboardInterrupt:

In [ ]:
!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt --overwrite -x 10xv3 --workflow=nac --sum=total --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202612/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L004_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S31_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S31_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S31_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S31_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S5_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S5_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S5_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S5_L002_R2_001.fastq.gz

[2025-01-10 09:01:27,697]    INFO [count_nac] Using index index_nac.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202612/ from
[2025-01-10 09:01:27,697]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L001_R1_001.fastq.gz
[2025-01-10 09:01:27,697]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L001_R2_001.fastq.gz
[2025-01-10 09:01:27,697]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L002_R1_001.fastq.gz
[2025-01-10 09:01:27,697]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L002_R2_001.fastq.gz
[2025-01-10 09:01:27,697]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L003_R1_001.fastq.gz
[2025-01-10 09:01:27,697]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L003_R2_001.fastq.gz
[2025-01-10 09:01:27,697]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L004_R1_001.fastq.gz
[2025-01-10 09:01:27,697]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L004_R2_001.fastq.gz
[2025-01-10 09:01:27,697]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S31_L001_R1_001.fastq.gz
[2025-01-10 09:01:27,697]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S31_L001_R2_001.fastq.gz
[2025-01-10 09:01:27,697]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S31_L002_R1_001.fastq.gz
[2025-01-10 09:01:27,697]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S31_L002_R2_001.fastq.gz
[2025-01-10 09:01:27,697]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S5_L001_R1_001.fastq.gz
[2025-01-10 09:01:27,697]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S5_L001_R2_001.fastq.gz
[2025-01-10 09:01:27,697]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S5_L002_R1_001.fastq.gz
[2025-01-10 09:01:27,697]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S5_L002_R2_001.fastq.gz

In [ ]:
!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt --overwrite -x 10xv3 --workflow=nac --sum=total --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L004_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S32_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S32_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S32_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S32_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S6_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S6_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S6_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S6_L002_R2_001.fastq.gz

[2025-01-10 11:22:21,304]    INFO [count_nac] Using index index_nac.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/ from
[2025-01-10 11:22:21,304]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L001_R1_001.fastq.gz
[2025-01-10 11:22:21,304]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L001_R2_001.fastq.gz
[2025-01-10 11:22:21,304]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L002_R1_001.fastq.gz
[2025-01-10 11:22:21,304]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L002_R2_001.fastq.gz
[2025-01-10 11:22:21,304]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L003_R1_001.fastq.gz
[2025-01-10 11:22:21,304]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L003_R2_001.fastq.gz
[2025-01-10 11:22:21,304]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L004_R1_001.fastq.gz
[2025-01-10 11:22:21,304]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L004_R2_001.fastq.gz
[2025-01-10 11:22:21,304]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S32_L001_R1_001.fastq.gz
[2025-01-10 11:22:21,304]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S32_L001_R2_001.fastq.gz
[2025-01-10 11:22:21,304]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S32_L002_R1_001.fastq.gz
[2025-01-10 11:22:21,304]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S32_L002_R2_001.fastq.gz
[2025-01-10 11:22:21,304]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S6_L001_R1_001.fastq.gz
[2025-01-10 11:22:21,304]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S6_L001_R2_001.fastq.gz
[2025-01-10 11:22:21,304]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S6_L002_R1_001.fastq.gz
[2025-01-10 11:22:21,304]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S6_L002_R2_001.fastq.gz
[2025-01-10 12:57:42,172]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/tmp/output.s.bus
[2025-01-10 13:01:22,971]    INFO [count_nac] On-list not provided
[2025-01-10 13:01:22,973]    INFO [count_nac] Copying pre-packaged 10XV3 on-list to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/
[2025-01-10 13:01:23,851]    INFO [count_nac] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/tmp/output.s.bus
[2025-01-10 13:02:08,552]    INFO [count_nac] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/10x_version3_whitelist.txt
[2025-01-10 13:03:42,778]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/output.unfiltered.bus
[2025-01-10 13:04:07,845]    INFO [count_nac] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/counts_unfiltered/cells_x_genes from BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/output.unfiltered.bus
[2025-01-10 13:07:52,269]    INFO [count_nac] Writing gene names to file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/counts_unfiltered/cells_x_genes.genes.names.txt
[2025-01-10 13:07:52,502] WARNING [count_nac] 1599 gene IDs do not have corresponding valid gene names. These genes will use their gene IDs instead.
[2025-01-10 13:07:52,540]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/counts_unfiltered/cells_x_genes.cell.mtx
[2025-01-10 13:08:21,502]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/counts_unfiltered/cells_x_genes.cell.mtx
[2025-01-10 13:09:02,360]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/counts_unfiltered/cells_x_genes.nucleus.mtx
[2025-01-10 13:09:36,242]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/counts_unfiltered/cells_x_genes.nucleus.mtx
[2025-01-10 13:10:25,071]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/counts_unfiltered/cells_x_genes.total.mtx
[2025-01-10 13:11:02,947]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/counts_unfiltered/cells_x_genes.total.mtx
[2025-01-10 13:12:16,440]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/counts_unfiltered/cells_x_genes.mature.mtx
[2025-01-10 13:12:20,604]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/counts_unfiltered/cells_x_genes.nascent.mtx
[2025-01-10 13:12:24,376]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/counts_unfiltered/cells_x_genes.ambiguous.mtx
[2025-01-10 13:12:29,032]    INFO [count_nac] Combining matrices
[2025-01-10 13:12:32,388]    INFO [count_nac] Writing matrices to h5ad /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202613/counts_unfiltered/adata.h5ad

In [ ]:
!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt --overwrite -x 10xv3 --workflow=nac --sum=total --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202614/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S15_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S15_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S15_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S15_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S8_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S8_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S8_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S8_L002_R2_001.fastq.gz

[2025-01-10 13:12:56,404]    INFO [count_nac] Using index index_nac.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202614/ from
[2025-01-10 13:12:56,404]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S15_L001_R1_001.fastq.gz
[2025-01-10 13:12:56,405]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S15_L001_R2_001.fastq.gz
[2025-01-10 13:12:56,405]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S15_L002_R1_001.fastq.gz
[2025-01-10 13:12:56,405]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S15_L002_R2_001.fastq.gz
[2025-01-10 13:12:56,405]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S8_L001_R1_001.fastq.gz
[2025-01-10 13:12:56,405]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S8_L001_R2_001.fastq.gz
[2025-01-10 13:12:56,405]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S8_L002_R1_001.fastq.gz
[2025-01-10 13:12:56,405]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S8_L002_R2_001.fastq.gz

In [ ]:
!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt --overwrite -x 10xv3 --workflow=nac --sum=total --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S16_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S16_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S16_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S16_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S9_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S9_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S9_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S9_L002_R2_001.fastq.gz

[2025-01-10 14:21:13,094]    INFO [count_nac] Using index index_nac.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/ from
[2025-01-10 14:21:13,094]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S16_L001_R1_001.fastq.gz
[2025-01-10 14:21:13,094]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S16_L001_R2_001.fastq.gz
[2025-01-10 14:21:13,094]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S16_L002_R1_001.fastq.gz
[2025-01-10 14:21:13,094]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S16_L002_R2_001.fastq.gz
[2025-01-10 14:21:13,094]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S9_L001_R1_001.fastq.gz
[2025-01-10 14:21:13,095]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S9_L001_R2_001.fastq.gz
[2025-01-10 14:21:13,095]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S9_L002_R1_001.fastq.gz
[2025-01-10 14:21:13,095]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S9_L002_R2_001.fastq.gz
[2025-01-10 15:36:42,204]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/tmp/output.s.bus
[2025-01-10 15:41:13,423]    INFO [count_nac] On-list not provided
[2025-01-10 15:41:13,424]    INFO [count_nac] Copying pre-packaged 10XV3 on-list to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/
[2025-01-10 15:41:14,274]    INFO [count_nac] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/tmp/output.s.bus
[2025-01-10 15:42:45,111]    INFO [count_nac] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/10x_version3_whitelist.txt
[2025-01-10 15:45:01,717]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/output.unfiltered.bus
[2025-01-10 15:48:01,301]    INFO [count_nac] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/counts_unfiltered/cells_x_genes from BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/output.unfiltered.bus
[2025-01-10 15:52:30,458]    INFO [count_nac] Writing gene names to file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/counts_unfiltered/cells_x_genes.genes.names.txt
[2025-01-10 15:52:30,676] WARNING [count_nac] 1599 gene IDs do not have corresponding valid gene names. These genes will use their gene IDs instead.
[2025-01-10 15:52:30,714]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/counts_unfiltered/cells_x_genes.cell.mtx
[2025-01-10 15:53:34,052]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/counts_unfiltered/cells_x_genes.cell.mtx
[2025-01-10 15:54:36,223]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/counts_unfiltered/cells_x_genes.nucleus.mtx
[2025-01-10 15:55:32,782]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/counts_unfiltered/cells_x_genes.nucleus.mtx
[2025-01-10 15:56:50,588]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/counts_unfiltered/cells_x_genes.total.mtx
[2025-01-10 15:57:47,003]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/counts_unfiltered/cells_x_genes.total.mtx
[2025-01-10 15:59:08,486]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/counts_unfiltered/cells_x_genes.mature.mtx
[2025-01-10 15:59:12,129]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/counts_unfiltered/cells_x_genes.nascent.mtx
[2025-01-10 15:59:15,907]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/counts_unfiltered/cells_x_genes.ambiguous.mtx
[2025-01-10 15:59:20,538]    INFO [count_nac] Combining matrices
[2025-01-10 15:59:24,686]    INFO [count_nac] Writing matrices to h5ad /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX13202615/counts_unfiltered/adata.h5ad

In [ ]:
!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt --overwrite -x 10xv3 --workflow=nac --sum=total --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S19_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S19_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S19_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S19_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S3_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S3_L001_R2_001.fastq.gz

[2025-01-11 02:42:05,701]    INFO [count_nac] Using index index_nac.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/ from
[2025-01-11 02:42:05,701]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S19_L001_R1_001.fastq.gz
[2025-01-11 02:42:05,701]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S19_L001_R2_001.fastq.gz
[2025-01-11 02:42:05,701]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S19_L002_R1_001.fastq.gz
[2025-01-11 02:42:05,701]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S19_L002_R2_001.fastq.gz
[2025-01-11 02:42:05,701]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S3_L001_R1_001.fastq.gz
[2025-01-11 02:42:05,701]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S3_L001_R2_001.fastq.gz
[2025-01-11 03:41:58,760]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/tmp/output.s.bus
[2025-01-11 03:47:00,571]    INFO [count_nac] On-list not provided
[2025-01-11 03:47:00,572]    INFO [count_nac] Copying pre-packaged 10XV3 on-list to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/
[2025-01-11 03:47:01,331]    INFO [count_nac] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/tmp/output.s.bus
[2025-01-11 03:48:04,547]    INFO [count_nac] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/10x_version3_whitelist.txt
[2025-01-11 03:50:03,271]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/output.unfiltered.bus
[2025-01-11 03:53:36,429]    INFO [count_nac] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/counts_unfiltered/cells_x_genes from BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/output.unfiltered.bus
[2025-01-11 03:57:33,033]    INFO [count_nac] Writing gene names to file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/counts_unfiltered/cells_x_genes.genes.names.txt
[2025-01-11 03:57:33,229] WARNING [count_nac] 1599 gene IDs do not have corresponding valid gene names. These genes will use their gene IDs instead.
[2025-01-11 03:57:33,260]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/counts_unfiltered/cells_x_genes.cell.mtx
[2025-01-11 03:58:42,013]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/counts_unfiltered/cells_x_genes.cell.mtx
[2025-01-11 04:00:14,594]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/counts_unfiltered/cells_x_genes.nucleus.mtx
[2025-01-11 04:01:16,014]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/counts_unfiltered/cells_x_genes.nucleus.mtx
[2025-01-11 04:02:39,628]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/counts_unfiltered/cells_x_genes.total.mtx
[2025-01-11 04:03:55,358]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/counts_unfiltered/cells_x_genes.total.mtx
[2025-01-11 04:05:36,366]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/counts_unfiltered/cells_x_genes.mature.mtx
[2025-01-11 04:05:41,679]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/counts_unfiltered/cells_x_genes.nascent.mtx
[2025-01-11 04:05:50,660]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/counts_unfiltered/cells_x_genes.ambiguous.mtx
[2025-01-11 04:06:06,752]    INFO [count_nac] Combining matrices
[2025-01-11 04:06:17,661]    INFO [count_nac] Writing matrices to h5ad /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265374/counts_unfiltered/adata.h5ad

In [ ]:
!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt --overwrite -x 10xv3 --workflow=nac --sum=total --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S20_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S20_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S20_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S20_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S4_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S4_L001_R2_001.fastq.gz

[2025-01-10 21:59:15,671]    INFO [count_nac] Using index index_nac.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/ from
[2025-01-10 21:59:15,671]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S20_L001_R1_001.fastq.gz
[2025-01-10 21:59:15,671]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S20_L001_R2_001.fastq.gz
[2025-01-10 21:59:15,671]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S20_L002_R1_001.fastq.gz
[2025-01-10 21:59:15,671]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S20_L002_R2_001.fastq.gz
[2025-01-10 21:59:15,671]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S4_L001_R1_001.fastq.gz
[2025-01-10 21:59:15,672]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S4_L001_R2_001.fastq.gz
[2025-01-10 22:45:36,542]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/tmp/output.s.bus
[2025-01-10 22:49:45,264]    INFO [count_nac] On-list not provided
[2025-01-10 22:49:45,265]    INFO [count_nac] Copying pre-packaged 10XV3 on-list to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/
[2025-01-10 22:49:46,097]    INFO [count_nac] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/tmp/output.s.bus
[2025-01-10 22:50:46,121]    INFO [count_nac] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/10x_version3_whitelist.txt
[2025-01-10 22:52:50,390]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/output.unfiltered.bus
[2025-01-10 22:56:22,544]    INFO [count_nac] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/counts_unfiltered/cells_x_genes from BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/output.unfiltered.bus
[2025-01-10 22:59:59,554]    INFO [count_nac] Writing gene names to file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/counts_unfiltered/cells_x_genes.genes.names.txt
[2025-01-10 22:59:59,813] WARNING [count_nac] 1599 gene IDs do not have corresponding valid gene names. These genes will use their gene IDs instead.
[2025-01-10 22:59:59,855]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/counts_unfiltered/cells_x_genes.cell.mtx
[2025-01-10 23:01:06,098]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/counts_unfiltered/cells_x_genes.cell.mtx
[2025-01-10 23:02:38,596]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/counts_unfiltered/cells_x_genes.nucleus.mtx
[2025-01-10 23:03:35,549]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/counts_unfiltered/cells_x_genes.nucleus.mtx
[2025-01-10 23:04:56,801]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/counts_unfiltered/cells_x_genes.total.mtx
[2025-01-10 23:06:27,868]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/counts_unfiltered/cells_x_genes.total.mtx
[2025-01-10 23:08:08,953]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/counts_unfiltered/cells_x_genes.mature.mtx
[2025-01-10 23:08:13,094]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/counts_unfiltered/cells_x_genes.nascent.mtx
[2025-01-10 23:08:16,477]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/counts_unfiltered/cells_x_genes.ambiguous.mtx
[2025-01-10 23:08:23,344]    INFO [count_nac] Combining matrices
[2025-01-10 23:08:27,974]    INFO [count_nac] Writing matrices to h5ad /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265375/counts_unfiltered/adata.h5ad

In [ ]:
!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt --overwrite -x 10xv3 --workflow=nac --sum=total --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT358_mm10_S11_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT358_mm10_S11_L001_R2_001.fastq.gz

[2025-01-10 23:08:55,659]    INFO [count_nac] Using index index_nac.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/ from
[2025-01-10 23:08:55,659]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT358_mm10_S11_L001_R1_001.fastq.gz
[2025-01-10 23:08:55,659]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT358_mm10_S11_L001_R2_001.fastq.gz
[2025-01-11 00:37:02,355]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/tmp/output.s.bus
[2025-01-11 00:44:09,788]    INFO [count_nac] On-list not provided
[2025-01-11 00:44:09,789]    INFO [count_nac] Copying pre-packaged 10XV3 on-list to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/
[2025-01-11 00:44:10,627]    INFO [count_nac] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/tmp/output.s.bus
[2025-01-11 00:46:03,473]    INFO [count_nac] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/10x_version3_whitelist.txt
[2025-01-11 00:49:14,433]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/output.unfiltered.bus
[2025-01-11 00:55:17,055]    INFO [count_nac] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/counts_unfiltered/cells_x_genes from BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/output.unfiltered.bus
[2025-01-11 00:59:51,605]    INFO [count_nac] Writing gene names to file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/counts_unfiltered/cells_x_genes.genes.names.txt
[2025-01-11 00:59:51,834] WARNING [count_nac] 1599 gene IDs do not have corresponding valid gene names. These genes will use their gene IDs instead.
[2025-01-11 00:59:51,880]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/counts_unfiltered/cells_x_genes.cell.mtx
[2025-01-11 01:00:46,991]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/counts_unfiltered/cells_x_genes.cell.mtx
[2025-01-11 01:02:01,739]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/counts_unfiltered/cells_x_genes.nucleus.mtx
[2025-01-11 01:02:57,232]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/counts_unfiltered/cells_x_genes.nucleus.mtx
[2025-01-11 01:04:29,471]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/counts_unfiltered/cells_x_genes.total.mtx
[2025-01-11 01:05:31,042]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/counts_unfiltered/cells_x_genes.total.mtx
[2025-01-11 01:06:56,177]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/counts_unfiltered/cells_x_genes.mature.mtx
[2025-01-11 01:07:00,868]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/counts_unfiltered/cells_x_genes.nascent.mtx
[2025-01-11 01:07:05,030]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/counts_unfiltered/cells_x_genes.ambiguous.mtx
[2025-01-11 01:07:10,779]    INFO [count_nac] Combining matrices
[2025-01-11 01:07:14,992]    INFO [count_nac] Writing matrices to h5ad /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265376/counts_unfiltered/adata.h5ad

In [ ]:
!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt --overwrite -x 10xv3 --workflow=nac --sum=total --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S10_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S10_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S10_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S10_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L004_R2_001.fastq.gz

[2025-01-11 01:07:42,443]    INFO [count_nac] Using index index_nac.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/ from
[2025-01-11 01:07:42,443]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S10_L001_R1_001.fastq.gz
[2025-01-11 01:07:42,443]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S10_L001_R2_001.fastq.gz
[2025-01-11 01:07:42,443]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S10_L002_R1_001.fastq.gz
[2025-01-11 01:07:42,443]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S10_L002_R2_001.fastq.gz
[2025-01-11 01:07:42,443]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L001_R1_001.fastq.gz
[2025-01-11 01:07:42,444]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L001_R2_001.fastq.gz
[2025-01-11 01:07:42,444]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L002_R1_001.fastq.gz
[2025-01-11 01:07:42,444]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L002_R2_001.fastq.gz
[2025-01-11 01:07:42,444]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L003_R1_001.fastq.gz
[2025-01-11 01:07:42,444]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L003_R2_001.fastq.gz
[2025-01-11 01:07:42,444]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L004_R1_001.fastq.gz
[2025-01-11 01:07:42,444]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L004_R2_001.fastq.gz
[2025-01-11 02:12:57,101]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/tmp/output.s.bus
[2025-01-11 02:19:00,200]    INFO [count_nac] On-list not provided
[2025-01-11 02:19:00,201]    INFO [count_nac] Copying pre-packaged 10XV3 on-list to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/
[2025-01-11 02:19:01,028]    INFO [count_nac] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/tmp/output.s.bus
[2025-01-11 02:20:45,942]    INFO [count_nac] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/10x_version3_whitelist.txt
[2025-01-11 02:23:31,312]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/output.unfiltered.bus
[2025-01-11 02:28:18,300]    INFO [count_nac] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/counts_unfiltered/cells_x_genes from BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/output.unfiltered.bus
[2025-01-11 02:33:24,730]    INFO [count_nac] Writing gene names to file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/counts_unfiltered/cells_x_genes.genes.names.txt
[2025-01-11 02:33:24,950] WARNING [count_nac] 1599 gene IDs do not have corresponding valid gene names. These genes will use their gene IDs instead.
[2025-01-11 02:33:24,992]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/counts_unfiltered/cells_x_genes.cell.mtx
[2025-01-11 02:34:26,443]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/counts_unfiltered/cells_x_genes.cell.mtx
[2025-01-11 02:35:48,402]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/counts_unfiltered/cells_x_genes.nucleus.mtx
[2025-01-11 02:36:49,317]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/counts_unfiltered/cells_x_genes.nucleus.mtx
[2025-01-11 02:38:11,983]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/counts_unfiltered/cells_x_genes.total.mtx
[2025-01-11 02:39:20,601]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/counts_unfiltered/cells_x_genes.total.mtx
[2025-01-11 02:41:16,958]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/counts_unfiltered/cells_x_genes.mature.mtx
[2025-01-11 02:41:21,473]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/counts_unfiltered/cells_x_genes.nascent.mtx
[2025-01-11 02:41:25,063]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/counts_unfiltered/cells_x_genes.ambiguous.mtx
[2025-01-11 02:41:31,826]    INFO [count_nac] Combining matrices
[2025-01-11 02:41:35,964]    INFO [count_nac] Writing matrices to h5ad /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX12265377/counts_unfiltered/adata.h5ad

# Found strange fastq files in Vennekens et al. (2021) using SRA so getting files from arrayexpress instead.

In [ ]:
import os
import requests
from concurrent.futures import ThreadPoolExecutor
from bs4 import BeautifulSoup

# Step 2: Create a local directory to store the downloaded files
local_directory = '/content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs'
os.makedirs(local_directory, exist_ok=True)

# Step 3: Define the download function and use parallel processing
base_url = "https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/"

def get_file_links(url):
    """Fetches all file links from the given directory URL."""
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    links = [link.get('href') for link in soup.find_all('a') if link.get('href')]
    return [url + link for link in links if not link.endswith('/')]

def download_file(url):
    """Downloads a single file from the given URL."""
    local_path = os.path.join(local_directory, os.path.basename(url))
    if not os.path.exists(local_path):
        print(f"Downloading {url}...")
        response = requests.get(url, stream=True)
        with open(local_path, 'wb') as f:
            for chunk in response.iter_content(chunk_size=8192):
                if chunk:
                    f.write(chunk)
    else:
        print(f"{local_path} already exists, skipping download.")

# Get all file links
file_links = get_file_links(base_url)

# Use ThreadPoolExecutor to download files in parallel
with ThreadPoolExecutor(max_workers=10) as executor:
    executor.map(download_file, file_links)

# Verify the download
# List the downloaded files
downloaded_files = os.listdir(local_directory)
downloaded_files

Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/?C=N;O=D...Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/?C=S;O=A...Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/?C=M;O=A...


Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/?C=D;O=A...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/E-MTAB-10021.sdrf.txt...Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/E-MTAB-10021.idf.txt...

Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT036_S9_L001_I1_001.fastq.gz...Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT036_S9_L001_R1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT036_S9_L001_R2_001.fastq.gz...

Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT036_S9_L002_I1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT036_S9_L002_R1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT036_S9_L002_R2_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT036_mm10_S9_L003_I1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT036_mm10_S9_L003_R1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT036_mm10_S9_L003_R2_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT036_mm10_S9_L004_I1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT036_mm10_S9_L004_R1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT036_mm10_S9_L004_R2_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT036_mm10_S9_L005_I1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT036_mm10_S9_L005_R1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT036_mm10_S9_L005_R2_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT036_mm10_S9_L006_I1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT036_mm10_S9_L006_R1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT036_mm10_S9_L006_R2_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT037_S10_L001_I1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT037_S10_L001_R1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT037_S10_L001_R2_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT037_S10_L002_I1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT037_S10_L002_R1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT037_S10_L002_R2_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT037_mm10_S10_L003_I1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT037_mm10_S10_L003_R1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT037_mm10_S10_L003_R2_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT037_mm10_S10_L004_I1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT037_mm10_S10_L004_R1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT037_mm10_S10_L004_R2_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT037_mm10_S10_L005_I1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT037_mm10_S10_L005_R1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT037_mm10_S10_L005_R2_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT037_mm10_S10_L006_I1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT037_mm10_S10_L006_R1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT037_mm10_S10_L006_R2_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT144_mm10_S13_L001_I1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT144_mm10_S13_L001_R1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT144_mm10_S13_L001_R2_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT144_mm10_S13_L002_I1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT144_mm10_S13_L002_R1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT144_mm10_S13_L002_R2_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT144_mm10_S27_L001_I1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT144_mm10_S27_L001_R1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT144_mm10_S27_L001_R2_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT144_mm10_S27_L002_I1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT144_mm10_S27_L002_R1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT144_mm10_S27_L002_R2_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT144_mm10_S27_L003_I1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT144_mm10_S27_L003_R1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT144_mm10_S27_L003_R2_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT144_mm10_S27_L004_I1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT144_mm10_S27_L004_R1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT144_mm10_S27_L004_R2_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT145_mm10_S9_L001_I1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT145_mm10_S9_L001_R1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT145_mm10_S9_L001_R2_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT145_mm10_S9_L002_I1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT145_mm10_S9_L002_R1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT145_mm10_S9_L002_R2_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT145_mm10_S14_L001_I1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT145_mm10_S14_L001_R1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT145_mm10_S14_L001_R2_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT145_mm10_S14_L002_I1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT145_mm10_S14_L002_R1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT145_mm10_S14_L002_R2_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT145_mm10_S28_L001_I1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT145_mm10_S28_L001_R1_001.fastq.gz...
Downloading https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/021/E-MTAB-10021/Files/scrEXT145_mm10_S28_L001_R2_001.fastq.gz...

# Aligning these Vennekens et al files now

In [ ]:
import subprocess
import shutil
import os
for SRA_ID in ["ERX4978537","ERX4978538","ERX4978539","ERX4978540",
               "ERX4978541","ERX4978542","ERX4978543","ERX4978544"]:
#if no folder in nac
  if not os.path.exists('/content/drive/MyDrive/pituitary_atlas/processed/nac/' + SRA_ID):
    os.mkdir('/content/drive/MyDrive/pituitary_atlas/processed/nac/' + SRA_ID)

# We can see it is v2 library.

In [ ]:
!gunzip /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L003_R1_001.fastq.gz
!head /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L003_R1_001.fastq

@NB501171:232:HJL3KBGX7:3:11401:5056:1022 1:N:0:GNTCCTCA
GCAATCAAGCACCGTCACCGCCCCTG
+
AAAAAEEEEAAEEEEE/E/EAE///E
@NB501171:232:HJL3KBGX7:3:11401:20483:1023 1:N:0:GNTCCTCA
GTAACGTAGCGCCTTGTAATCCGTAT
+
AAAAAEEEEEAEAEEEEEAEEEEEEE
@NB501171:232:HJL3KBGX7:3:11401:9431:1027 1:N:0:GTTCCTCA
CCACGGATCCACTCCATTTTTCCCTT

In [ ]:
!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt --overwrite -x 10xv2 --workflow=nac --sum=total --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978537/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_S9_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_S9_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_S9_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_S9_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L004_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L005_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L005_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L006_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L006_R2_001.fastq.gz

!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt --overwrite -x 10xv2 --workflow=nac --sum=total --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978538/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_S10_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_S10_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_S10_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_S10_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L004_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L005_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L005_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L006_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L006_R2_001.fastq.gz

!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt --overwrite -x 10xv2 --workflow=nac --sum=total --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S13_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S13_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S13_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S13_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L004_R2_001.fastq.gz



!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt --overwrite -x 10xv2 --workflow=nac --sum=total --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S14_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S14_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S14_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S14_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L004_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S9_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S9_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S9_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S9_L002_R2_001.fastq.gz



!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt --overwrite -x 10xv2 --workflow=nac --sum=total --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S10_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S10_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S10_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S10_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S15_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S15_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S15_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S15_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L004_R2_001.fastq.gz

!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt --overwrite -x 10xv2 --workflow=nac --sum=total --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978542/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S11_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S11_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S11_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S11_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S16_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S16_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S16_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S16_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S30_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S30_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S30_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S30_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S30_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S30_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S30_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S30_L004_R2_001.fastq.gz

!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt --overwrite -x 10xv2 --workflow=nac --sum=total --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978543/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S12_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S12_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S12_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S12_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S17_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S17_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S17_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S17_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S31_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S31_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S31_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S31_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S31_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S31_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S31_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S31_L004_R2_001.fastq.gz


!kb count -i index_nac.idx -g t2g_nac.txt -c1 cdna.txt -c2 nascent.txt --overwrite -x 10xv2 --workflow=nac --sum=total --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978544/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S13_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S13_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S13_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S13_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S18_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S18_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S18_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S18_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S32_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S32_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S32_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S32_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S32_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S32_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S32_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S32_L004_R2_001.fastq.gz

[2024-07-11 15:03:42,972]    INFO [count_nac] Using index index_nac.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/ from
[2024-07-11 15:03:42,973]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S13_L001_R1_001.fastq.gz
[2024-07-11 15:03:42,973]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S13_L001_R2_001.fastq.gz
[2024-07-11 15:03:42,973]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S13_L002_R1_001.fastq.gz
[2024-07-11 15:03:42,973]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S13_L002_R2_001.fastq.gz
[2024-07-11 15:03:42,973]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L001_R1_001.fastq.gz
[2024-07-11 15:03:42,973]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L001_R2_001.fastq.gz
[2024-07-11 15:03:42,973]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L002_R1_001.fastq.gz
[2024-07-11 15:03:42,973]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L002_R2_001.fastq.gz
[2024-07-11 15:03:42,973]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L003_R1_001.fastq.gz
[2024-07-11 15:03:42,973]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L003_R2_001.fastq.gz
[2024-07-11 15:03:42,973]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L004_R1_001.fastq.gz
[2024-07-11 15:03:42,973]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L004_R2_001.fastq.gz
[2024-07-11 20:22:23,334]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/tmp/output.s.bus
[2024-07-11 20:32:02,939]    INFO [count_nac] On-list not provided
[2024-07-11 20:32:02,942]    INFO [count_nac] Copying pre-packaged 10XV2 on-list to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/
[2024-07-11 20:32:03,112]    INFO [count_nac] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/tmp/output.s.bus
[2024-07-11 20:32:44,222]    INFO [count_nac] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/10x_version2_whitelist.txt
[2024-07-11 20:34:22,273]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/output.unfiltered.bus
[2024-07-11 20:34:47,037]    INFO [count_nac] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/counts_unfiltered/cells_x_genes from BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/output.unfiltered.bus
[2024-07-11 20:41:33,788]    INFO [count_nac] Writing gene names to file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/counts_unfiltered/cells_x_genes.genes.names.txt
[2024-07-11 20:41:34,233] WARNING [count_nac] 1599 gene IDs do not have corresponding valid gene names. These genes will use their gene IDs instead.
[2024-07-11 20:41:34,304]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/counts_unfiltered/cells_x_genes.cell.mtx
[2024-07-11 20:42:18,425]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/counts_unfiltered/cells_x_genes.cell.mtx
[2024-07-11 20:43:23,094]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/counts_unfiltered/cells_x_genes.nucleus.mtx
[2024-07-11 20:44:16,635]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/counts_unfiltered/cells_x_genes.nucleus.mtx
[2024-07-11 20:45:30,207]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/counts_unfiltered/cells_x_genes.total.mtx
[2024-07-11 20:46:25,204]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/counts_unfiltered/cells_x_genes.total.mtx
[2024-07-11 20:47:39,051]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/counts_unfiltered/cells_x_genes.mature.mtx
[2024-07-11 20:47:45,197]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/counts_unfiltered/cells_x_genes.nascent.mtx
[2024-07-11 20:47:58,403]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/counts_unfiltered/cells_x_genes.ambiguous.mtx
[2024-07-11 20:48:42,259]    INFO [count_nac] Combining matrices
[2024-07-11 20:48:51,994]    INFO [count_nac] Writing matrices to h5ad /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978539/counts_unfiltered/adata.h5ad
[2024-07-11 20:49:21,893]    INFO [count_nac] Using index index_nac.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/ from
[2024-07-11 20:49:21,893]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S14_L001_R1_001.fastq.gz
[2024-07-11 20:49:21,893]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S14_L001_R2_001.fastq.gz
[2024-07-11 20:49:21,893]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S14_L002_R1_001.fastq.gz
[2024-07-11 20:49:21,893]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S14_L002_R2_001.fastq.gz
[2024-07-11 20:49:21,893]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L001_R1_001.fastq.gz
[2024-07-11 20:49:21,893]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L001_R2_001.fastq.gz
[2024-07-11 20:49:21,893]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L002_R1_001.fastq.gz
[2024-07-11 20:49:21,893]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L002_R2_001.fastq.gz
[2024-07-11 20:49:21,893]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L003_R1_001.fastq.gz
[2024-07-11 20:49:21,893]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L003_R2_001.fastq.gz
[2024-07-11 20:49:21,893]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L004_R1_001.fastq.gz
[2024-07-11 20:49:21,893]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L004_R2_001.fastq.gz
[2024-07-11 20:49:21,893]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S9_L001_R1_001.fastq.gz
[2024-07-11 20:49:21,893]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S9_L001_R2_001.fastq.gz
[2024-07-11 20:49:21,893]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S9_L002_R1_001.fastq.gz
[2024-07-11 20:49:21,893]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S9_L002_R2_001.fastq.gz
[2024-07-11 21:11:56,879]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/tmp/output.s.bus
[2024-07-11 21:12:15,819]    INFO [count_nac] On-list not provided
[2024-07-11 21:12:15,819]    INFO [count_nac] Copying pre-packaged 10XV2 on-list to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/
[2024-07-11 21:12:15,996]    INFO [count_nac] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/tmp/output.s.bus
[2024-07-11 21:12:24,417]    INFO [count_nac] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/10x_version2_whitelist.txt
[2024-07-11 21:12:50,074]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/output.unfiltered.bus
[2024-07-11 21:13:04,712]    INFO [count_nac] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/counts_unfiltered/cells_x_genes from BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/output.unfiltered.bus
[2024-07-11 21:15:09,039]    INFO [count_nac] Writing gene names to file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/counts_unfiltered/cells_x_genes.genes.names.txt
[2024-07-11 21:15:09,375] WARNING [count_nac] 1599 gene IDs do not have corresponding valid gene names. These genes will use their gene IDs instead.
[2024-07-11 21:15:09,418]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/counts_unfiltered/cells_x_genes.cell.mtx
[2024-07-11 21:15:25,399]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/counts_unfiltered/cells_x_genes.cell.mtx
[2024-07-11 21:15:47,492]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/counts_unfiltered/cells_x_genes.nucleus.mtx
[2024-07-11 21:16:06,897]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/counts_unfiltered/cells_x_genes.nucleus.mtx
[2024-07-11 21:16:33,280]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/counts_unfiltered/cells_x_genes.total.mtx
[2024-07-11 21:16:53,838]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/counts_unfiltered/cells_x_genes.total.mtx
[2024-07-11 21:17:22,054]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/counts_unfiltered/cells_x_genes.mature.mtx
[2024-07-11 21:17:25,074]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/counts_unfiltered/cells_x_genes.nascent.mtx
[2024-07-11 21:17:30,076]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/counts_unfiltered/cells_x_genes.ambiguous.mtx
[2024-07-11 21:17:42,295]    INFO [count_nac] Combining matrices
[2024-07-11 21:17:42,918]    INFO [count_nac] Writing matrices to h5ad /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978540/counts_unfiltered/adata.h5ad
[2024-07-11 21:17:58,323]    INFO [count_nac] Using index index_nac.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/ from
[2024-07-11 21:17:58,324]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S10_L001_R1_001.fastq.gz
[2024-07-11 21:17:58,324]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S10_L001_R2_001.fastq.gz
[2024-07-11 21:17:58,324]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S10_L002_R1_001.fastq.gz
[2024-07-11 21:17:58,324]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S10_L002_R2_001.fastq.gz
[2024-07-11 21:17:58,324]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S15_L001_R1_001.fastq.gz
[2024-07-11 21:17:58,324]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S15_L001_R2_001.fastq.gz
[2024-07-11 21:17:58,324]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S15_L002_R1_001.fastq.gz
[2024-07-11 21:17:58,324]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S15_L002_R2_001.fastq.gz
[2024-07-11 21:17:58,324]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L001_R1_001.fastq.gz
[2024-07-11 21:17:58,324]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L001_R2_001.fastq.gz
[2024-07-11 21:17:58,324]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L002_R1_001.fastq.gz
[2024-07-11 21:17:58,324]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L002_R2_001.fastq.gz
[2024-07-11 21:17:58,324]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L003_R1_001.fastq.gz
[2024-07-11 21:17:58,324]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L003_R2_001.fastq.gz
[2024-07-11 21:17:58,324]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L004_R1_001.fastq.gz
[2024-07-11 21:17:58,324]    INFO [count_nac]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L004_R2_001.fastq.gz
[2024-07-11 21:37:33,762]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/tmp/output.s.bus
[2024-07-11 21:37:51,300]    INFO [count_nac] On-list not provided
[2024-07-11 21:37:51,300]    INFO [count_nac] Copying pre-packaged 10XV2 on-list to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/
[2024-07-11 21:37:51,431]    INFO [count_nac] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/tmp/output.s.bus
[2024-07-11 21:37:58,349]    INFO [count_nac] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/10x_version2_whitelist.txt
[2024-07-11 21:38:20,898]    INFO [count_nac] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/output.unfiltered.bus
[2024-07-11 21:38:30,424]    INFO [count_nac] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/counts_unfiltered/cells_x_genes from BUS file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/output.unfiltered.bus
[2024-07-11 21:40:29,275]    INFO [count_nac] Writing gene names to file /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/counts_unfiltered/cells_x_genes.genes.names.txt
[2024-07-11 21:40:29,620] WARNING [count_nac] 1599 gene IDs do not have corresponding valid gene names. These genes will use their gene IDs instead.
[2024-07-11 21:40:29,666]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/counts_unfiltered/cells_x_genes.cell.mtx
[2024-07-11 21:40:44,276]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/counts_unfiltered/cells_x_genes.cell.mtx
[2024-07-11 21:41:04,406]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/counts_unfiltered/cells_x_genes.nucleus.mtx
[2024-07-11 21:41:20,991]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/counts_unfiltered/cells_x_genes.nucleus.mtx
[2024-07-11 21:41:43,329]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/counts_unfiltered/cells_x_genes.total.mtx
[2024-07-11 21:42:00,849]    INFO [count_nac] Summing matrices into /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/counts_unfiltered/cells_x_genes.total.mtx
[2024-07-11 21:42:51,707]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/counts_unfiltered/cells_x_genes.mature.mtx
[2024-07-11 21:42:54,470]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/counts_unfiltered/cells_x_genes.nascent.mtx
[2024-07-11 21:42:58,142]    INFO [count_nac] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/counts_unfiltered/cells_x_genes.ambiguous.mtx
[2024-07-11 21:43:10,032]    INFO [count_nac] Combining matrices
[2024-07-11 21:43:10,629]    INFO [count_nac] Writing matrices to h5ad /content/drive/MyDrive/pituitary_atlas/processed/nac/ERX4978541/counts_unfiltered/adata.h5ad

# Aligning strange datasets again, using tcc workflow

# First aligning Cheung et al files

In [ ]:
!kb count -i index_std.idx -g t2g_std.txt --overwrite -x 10xv2 --tcc --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736337/ /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_003.fastq.gz

[2024-07-12 09:32:27,398]    INFO [count] Using index index_std.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736337/ from
[2024-07-12 09:32:27,399]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_001.fastq.gz
[2024-07-12 09:32:27,399]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_001.fastq.gz
[2024-07-12 09:32:27,399]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_002.fastq.gz
[2024-07-12 09:32:27,399]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_002.fastq.gz
[2024-07-12 09:32:27,399]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_003.fastq.gz
[2024-07-12 09:32:27,399]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_003.fastq.gz
[2024-07-12 09:32:27,399]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_001.fastq.gz
[2024-07-12 09:32:27,399]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_001.fastq.gz
[2024-07-12 09:32:27,399]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_002.fastq.gz
[2024-07-12 09:32:27,399]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_002.fastq.gz
[2024-07-12 09:32:27,399]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_003.fastq.gz
[2024-07-12 09:32:27,399]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736337/fastqs/7wo_B6N_males_Pool1_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_003.fastq.gz
[2024-07-12 09:58:58,293]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736337/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736337/tmp/output.s.bus
[2024-07-12 10:01:10,781]    INFO [count] On-list not provided
[2024-07-12 10:01:10,782]    INFO [count] Copying pre-packaged 10XV2 on-list to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736337/
[2024-07-12 10:01:10,913]    INFO [count] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736337/tmp/output.s.bus
[2024-07-12 10:01:29,553]    INFO [count] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736337/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736337/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736337/10x_version2_whitelist.txt
[2024-07-12 10:02:28,273]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736337/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736337/output.unfiltered.bus
[2024-07-12 10:04:25,546]    INFO [count] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736337/counts_unfiltered/cells_x_tcc from BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736337/output.unfiltered.bus
[2024-07-12 10:05:47,875]    INFO [count] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736337/counts_unfiltered/cells_x_tcc.mtx
[2024-07-12 10:06:25,156]    INFO [count] Writing matrix to h5ad /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736337/counts_unfiltered/adata.h5ad

In [ ]:
!kb count -i index_std.idx -g t2g_std.txt --overwrite -x 10xv2 --tcc --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736338/ /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_004.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_004.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_004.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_004.fastq.gz

[2024-07-12 10:28:05,627]    INFO [count] Using index index_std.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736338/ from
[2024-07-12 10:28:05,627]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_001.fastq.gz
[2024-07-12 10:28:05,627]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_001.fastq.gz
[2024-07-12 10:28:05,627]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_002.fastq.gz
[2024-07-12 10:28:05,627]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_002.fastq.gz
[2024-07-12 10:28:05,627]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_003.fastq.gz
[2024-07-12 10:28:05,627]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_003.fastq.gz
[2024-07-12 10:28:05,627]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R1_004.fastq.gz
[2024-07-12 10:28:05,627]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L001_R2_004.fastq.gz
[2024-07-12 10:28:05,627]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_001.fastq.gz
[2024-07-12 10:28:05,627]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_001.fastq.gz
[2024-07-12 10:28:05,627]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_002.fastq.gz
[2024-07-12 10:28:05,627]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_002.fastq.gz
[2024-07-12 10:28:05,627]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_003.fastq.gz
[2024-07-12 10:28:05,627]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_003.fastq.gz
[2024-07-12 10:28:05,627]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R1_004.fastq.gz
[2024-07-12 10:28:05,627]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX4736338/fastqs/7wo_B6N_males_Pool2_mm10v7b_MissingLibrary_1_HW73WBBXX/bamtofastq_S1_L002_R2_004.fastq.gz
[2024-07-12 11:01:37,545]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736338/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736338/tmp/output.s.bus
[2024-07-12 11:04:22,280]    INFO [count] On-list not provided
[2024-07-12 11:04:22,280]    INFO [count] Copying pre-packaged 10XV2 on-list to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736338/
[2024-07-12 11:04:22,453]    INFO [count] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736338/tmp/output.s.bus
[2024-07-12 11:04:44,600]    INFO [count] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736338/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736338/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736338/10x_version2_whitelist.txt
[2024-07-12 11:06:01,774]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736338/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736338/output.unfiltered.bus
[2024-07-12 11:08:12,074]    INFO [count] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736338/counts_unfiltered/cells_x_tcc from BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736338/output.unfiltered.bus
[2024-07-12 11:09:46,624]    INFO [count] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736338/counts_unfiltered/cells_x_tcc.mtx
[2024-07-12 11:10:30,853]    INFO [count] Writing matrix to h5ad /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX4736338/counts_unfiltered/adata.h5ad

# Cheung 2020 now

In [ ]:
!kb count -i index_std.idx -g t2g_std.txt --overwrite -x 10xv2 --tcc --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377164/ /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_004.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_004.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_004.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_004.fastq.gz

[2024-09-13 11:54:02,994]    INFO [count] Using index index_std.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377164/ from
[2024-09-13 11:54:02,994]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_001.fastq.gz
[2024-09-13 11:54:02,994]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_001.fastq.gz
[2024-09-13 11:54:02,994]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_002.fastq.gz
[2024-09-13 11:54:02,994]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_002.fastq.gz
[2024-09-13 11:54:02,994]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_003.fastq.gz
[2024-09-13 11:54:02,994]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_003.fastq.gz
[2024-09-13 11:54:02,994]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_004.fastq.gz
[2024-09-13 11:54:02,994]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_004.fastq.gz
[2024-09-13 11:54:02,994]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_001.fastq.gz
[2024-09-13 11:54:02,995]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_001.fastq.gz
[2024-09-13 11:54:02,995]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_002.fastq.gz
[2024-09-13 11:54:02,995]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_002.fastq.gz
[2024-09-13 11:54:02,995]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_003.fastq.gz
[2024-09-13 11:54:02,995]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_003.fastq.gz
[2024-09-13 11:54:02,995]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_004.fastq.gz
[2024-09-13 11:54:02,995]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377164/fastqs/P4_Hesx1Cre_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_004.fastq.gz
[2024-09-13 12:17:41,506]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377164/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377164/tmp/output.s.bus
[2024-09-13 12:19:34,653]    INFO [count] On-list not provided
[2024-09-13 12:19:34,655]    INFO [count] Copying pre-packaged 10XV2 on-list to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377164/
[2024-09-13 12:19:34,768]    INFO [count] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377164/tmp/output.s.bus
[2024-09-13 12:19:48,902]    INFO [count] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377164/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377164/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377164/10x_version2_whitelist.txt
[2024-09-13 12:20:39,409]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377164/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377164/output.unfiltered.bus
[2024-09-13 12:21:46,860]    INFO [count] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377164/counts_unfiltered/cells_x_tcc from BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377164/output.unfiltered.bus
[2024-09-13 12:22:41,270]    INFO [count] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377164/counts_unfiltered/cells_x_tcc.mtx
[2024-09-13 12:22:44,152]    INFO [count] Writing matrix to h5ad /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377164/counts_unfiltered/adata.h5ad

In [ ]:
!kb count -i index_std.idx -g t2g_std.txt --overwrite -x 10xv2 --tcc --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377166/ /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_004.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_004.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_004.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_004.fastq.gz

[2024-09-13 12:22:58,308]    INFO [count] Using index index_std.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377166/ from
[2024-09-13 12:22:58,308]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_001.fastq.gz
[2024-09-13 12:22:58,308]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_001.fastq.gz
[2024-09-13 12:22:58,308]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_002.fastq.gz
[2024-09-13 12:22:58,309]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_002.fastq.gz
[2024-09-13 12:22:58,309]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_003.fastq.gz
[2024-09-13 12:22:58,309]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_003.fastq.gz
[2024-09-13 12:22:58,309]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R1_004.fastq.gz
[2024-09-13 12:22:58,309]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L004_R2_004.fastq.gz
[2024-09-13 12:22:58,309]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_001.fastq.gz
[2024-09-13 12:22:58,309]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_001.fastq.gz
[2024-09-13 12:22:58,309]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_002.fastq.gz
[2024-09-13 12:22:58,309]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_002.fastq.gz
[2024-09-13 12:22:58,309]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_003.fastq.gz
[2024-09-13 12:22:58,309]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_003.fastq.gz
[2024-09-13 12:22:58,309]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R1_004.fastq.gz
[2024-09-13 12:22:58,309]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX7377166/fastqs/P4_Hesx1Cre_dnRAR_v3_expect10k_0_1_HTYCGBBXX/bamtofastq_S1_L005_R2_004.fastq.gz
[2024-09-13 12:46:18,161]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377166/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377166/tmp/output.s.bus
[2024-09-13 12:48:51,567]    INFO [count] On-list not provided
[2024-09-13 12:48:51,568]    INFO [count] Copying pre-packaged 10XV2 on-list to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377166/
[2024-09-13 12:48:51,686]    INFO [count] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377166/tmp/output.s.bus
[2024-09-13 12:49:05,918]    INFO [count] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377166/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377166/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377166/10x_version2_whitelist.txt
[2024-09-13 12:49:51,418]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377166/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377166/output.unfiltered.bus
[2024-09-13 12:50:54,060]    INFO [count] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377166/counts_unfiltered/cells_x_tcc from BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377166/output.unfiltered.bus
[2024-09-13 12:51:41,838]    INFO [count] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377166/counts_unfiltered/cells_x_tcc.mtx
[2024-09-13 12:51:44,660]    INFO [count] Writing matrix to h5ad /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX7377166/counts_unfiltered/adata.h5ad

# Now Bastedo

In [ ]:
!kb count -i index_std.idx -g t2g_std.txt --overwrite -x 10xv3 --tcc --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX9637224/ /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R2_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R2_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R2_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R1_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R2_002.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R1_003.fastq.gz /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R2_003.fastq.gz

[2024-09-13 12:52:02,071]    INFO [count] Using index index_std.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX9637224/ from
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R1_001.fastq.gz
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R2_001.fastq.gz
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R1_002.fastq.gz
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R2_002.fastq.gz
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R1_003.fastq.gz
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L001_R2_003.fastq.gz
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R1_001.fastq.gz
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R2_001.fastq.gz
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R1_002.fastq.gz
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R2_002.fastq.gz
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R1_003.fastq.gz
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L002_R2_003.fastq.gz
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R1_001.fastq.gz
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R2_001.fastq.gz
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R1_002.fastq.gz
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R2_002.fastq.gz
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R1_003.fastq.gz
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L003_R2_003.fastq.gz
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R1_001.fastq.gz
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R2_001.fastq.gz
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R1_002.fastq.gz
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R2_002.fastq.gz
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R1_003.fastq.gz
[2024-09-13 12:52:02,072]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/raw/SRX9637224/fastqs/sc62__RNA_WS20200904_8WeekPituitary_0_1_HY3YGBGXF/bamtofastq_S1_L004_R2_003.fastq.gz
[2024-09-13 13:13:12,147]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX9637224/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX9637224/tmp/output.s.bus
[2024-09-13 13:15:41,253]    INFO [count] On-list not provided
[2024-09-13 13:15:41,254]    INFO [count] Copying pre-packaged 10XV3 on-list to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX9637224/
[2024-09-13 13:15:42,108]    INFO [count] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX9637224/tmp/output.s.bus
[2024-09-13 13:16:21,391]    INFO [count] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX9637224/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX9637224/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX9637224/10x_version3_whitelist.txt
[2024-09-13 13:17:39,456]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX9637224/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX9637224/output.unfiltered.bus
[2024-09-13 13:19:07,744]    INFO [count] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX9637224/counts_unfiltered/cells_x_tcc from BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX9637224/output.unfiltered.bus
[2024-09-13 13:20:56,967]    INFO [count] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX9637224/counts_unfiltered/cells_x_tcc.mtx
[2024-09-13 13:21:02,665]    INFO [count] Writing matrix to h5ad /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX9637224/counts_unfiltered/adata.h5ad

Now repeat for Vennekens datasets

In [ ]:
!kb count -i index_std.idx -g t2g_std.txt --overwrite -x 10xv2 --tcc --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978537/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_S9_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_S9_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_S9_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_S9_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L004_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L005_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L005_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L006_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L006_R2_001.fastq.gz

!kb count -i index_std.idx -g t2g_std.txt --overwrite -x 10xv2 --tcc --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978538/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_S10_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_S10_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_S10_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_S10_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L004_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L005_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L005_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L006_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L006_R2_001.fastq.gz

!kb count -i index_std.idx -g t2g_std.txt --overwrite -x 10xv2 --tcc --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978539/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S13_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S13_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S13_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S13_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L004_R2_001.fastq.gz



!kb count -i index_std.idx -g t2g_std.txt --overwrite -x 10xv2 --tcc --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978540/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S14_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S14_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S14_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S14_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L004_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S9_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S9_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S9_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S9_L002_R2_001.fastq.gz



!kb count -i index_std.idx -g t2g_std.txt --overwrite -x 10xv2 --tcc --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978541/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S10_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S10_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S10_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S10_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S15_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S15_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S15_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S15_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L004_R2_001.fastq.gz

!kb count -i index_std.idx -g t2g_std.txt --overwrite -x 10xv2 --tcc --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978542/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S11_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S11_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S11_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S11_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S16_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S16_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S16_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S16_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S30_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S30_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S30_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S30_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S30_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S30_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S30_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S30_L004_R2_001.fastq.gz

!kb count -i index_std.idx -g t2g_std.txt --overwrite -x 10xv2 --tcc --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978543/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S12_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S12_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S12_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S12_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S17_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S17_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S17_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S17_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S31_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S31_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S31_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S31_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S31_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S31_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S31_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT148_mm10_S31_L004_R2_001.fastq.gz


!kb count -i index_std.idx -g t2g_std.txt --overwrite -x 10xv2 --tcc --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978544/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S13_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S13_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S13_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S13_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S18_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S18_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S18_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S18_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S32_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S32_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S32_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S32_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S32_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S32_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S32_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT149_mm10_S32_L004_R2_001.fastq.gz

[2024-07-12 11:36:43,725]    INFO [count] Using index index_std.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978537/ from
[2024-07-12 11:36:43,725]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_S9_L001_R1_001.fastq.gz
[2024-07-12 11:36:43,725]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_S9_L001_R2_001.fastq.gz
[2024-07-12 11:36:43,725]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_S9_L002_R1_001.fastq.gz
[2024-07-12 11:36:43,725]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_S9_L002_R2_001.fastq.gz
[2024-07-12 11:36:43,725]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L003_R1_001.fastq.gz
[2024-07-12 11:36:43,725]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L003_R2_001.fastq.gz
[2024-07-12 11:36:43,725]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L004_R1_001.fastq.gz
[2024-07-12 11:36:43,725]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L004_R2_001.fastq.gz
[2024-07-12 11:36:43,725]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L005_R1_001.fastq.gz
[2024-07-12 11:36:43,725]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L005_R2_001.fastq.gz
[2024-07-12 11:36:43,726]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L006_R1_001.fastq.gz
[2024-07-12 11:36:43,726]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT036_mm10_S9_L006_R2_001.fastq.gz
[2024-07-12 11:54:29,432]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978537/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978537/tmp/output.s.bus
[2024-07-12 11:56:16,369]    INFO [count] On-list not provided
[2024-07-12 11:56:16,369]    INFO [count] Copying pre-packaged 10XV2 on-list to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978537/
[2024-07-12 11:56:16,581]    INFO [count] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978537/tmp/output.s.bus
[2024-07-12 11:56:35,430]    INFO [count] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978537/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978537/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978537/10x_version2_whitelist.txt
[2024-07-12 11:57:21,126]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978537/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978537/output.unfiltered.bus
[2024-07-12 11:58:28,270]    INFO [count] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978537/counts_unfiltered/cells_x_tcc from BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978537/output.unfiltered.bus
[2024-07-12 11:59:34,672]    INFO [count] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978537/counts_unfiltered/cells_x_tcc.mtx
[2024-07-12 12:00:05,369]    INFO [count] Writing matrix to h5ad /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978537/counts_unfiltered/adata.h5ad
[2024-07-12 12:00:19,764]    INFO [count] Using index index_std.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978538/ from
[2024-07-12 12:00:19,764]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_S10_L001_R1_001.fastq.gz
[2024-07-12 12:00:19,764]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_S10_L001_R2_001.fastq.gz
[2024-07-12 12:00:19,764]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_S10_L002_R1_001.fastq.gz
[2024-07-12 12:00:19,764]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_S10_L002_R2_001.fastq.gz
[2024-07-12 12:00:19,764]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L003_R1_001.fastq.gz
[2024-07-12 12:00:19,764]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L003_R2_001.fastq.gz
[2024-07-12 12:00:19,764]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L004_R1_001.fastq.gz
[2024-07-12 12:00:19,764]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L004_R2_001.fastq.gz
[2024-07-12 12:00:19,764]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L005_R1_001.fastq.gz
[2024-07-12 12:00:19,764]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L005_R2_001.fastq.gz
[2024-07-12 12:00:19,764]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L006_R1_001.fastq.gz
[2024-07-12 12:00:19,764]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT037_mm10_S10_L006_R2_001.fastq.gz
[2024-07-12 12:26:01,050]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978538/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978538/tmp/output.s.bus
[2024-07-12 12:27:47,974]    INFO [count] On-list not provided
[2024-07-12 12:27:47,974]    INFO [count] Copying pre-packaged 10XV2 on-list to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978538/
[2024-07-12 12:27:48,111]    INFO [count] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978538/tmp/output.s.bus
[2024-07-12 12:28:00,339]    INFO [count] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978538/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978538/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978538/10x_version2_whitelist.txt
[2024-07-12 12:28:43,435]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978538/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978538/output.unfiltered.bus
[2024-07-12 12:28:57,070]    INFO [count] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978538/counts_unfiltered/cells_x_tcc from BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978538/output.unfiltered.bus
[2024-07-12 12:30:08,991]    INFO [count] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978538/counts_unfiltered/cells_x_tcc.mtx
[2024-07-12 12:30:38,723]    INFO [count] Writing matrix to h5ad /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978538/counts_unfiltered/adata.h5ad
[2024-07-12 12:30:53,185]    INFO [count] Using index index_std.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978539/ from
[2024-07-12 12:30:53,185]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S13_L001_R1_001.fastq.gz
[2024-07-12 12:30:53,186]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S13_L001_R2_001.fastq.gz
[2024-07-12 12:30:53,186]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S13_L002_R1_001.fastq.gz
[2024-07-12 12:30:53,186]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S13_L002_R2_001.fastq.gz
[2024-07-12 12:30:53,186]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L001_R1_001.fastq.gz
[2024-07-12 12:30:53,186]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L001_R2_001.fastq.gz
[2024-07-12 12:30:53,186]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L002_R1_001.fastq.gz
[2024-07-12 12:30:53,186]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L002_R2_001.fastq.gz
[2024-07-12 12:30:53,186]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L003_R1_001.fastq.gz
[2024-07-12 12:30:53,186]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L003_R2_001.fastq.gz
[2024-07-12 12:30:53,186]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L004_R1_001.fastq.gz
[2024-07-12 12:30:53,186]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT144_mm10_S27_L004_R2_001.fastq.gz
[2024-07-12 15:00:29,604]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978539/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978539/tmp/output.s.bus
[2024-07-12 15:08:40,898]    INFO [count] On-list not provided
[2024-07-12 15:08:40,899]    INFO [count] Copying pre-packaged 10XV2 on-list to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978539/
[2024-07-12 15:08:41,079]    INFO [count] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978539/tmp/output.s.bus
[2024-07-12 15:09:05,930]    INFO [count] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978539/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978539/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978539/10x_version2_whitelist.txt
[2024-07-12 15:10:32,738]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978539/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978539/output.unfiltered.bus
[2024-07-12 15:11:45,895]    INFO [count] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978539/counts_unfiltered/cells_x_tcc from BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978539/output.unfiltered.bus
[2024-07-12 15:13:18,191]    INFO [count] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978539/counts_unfiltered/cells_x_tcc.mtx
[2024-07-12 15:14:02,723]    INFO [count] Writing matrix to h5ad /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978539/counts_unfiltered/adata.h5ad
[2024-07-12 15:14:39,638]    INFO [count] Using index index_std.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978540/ from
[2024-07-12 15:14:39,639]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S14_L001_R1_001.fastq.gz
[2024-07-12 15:14:39,639]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S14_L001_R2_001.fastq.gz
[2024-07-12 15:14:39,639]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S14_L002_R1_001.fastq.gz
[2024-07-12 15:14:39,639]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S14_L002_R2_001.fastq.gz
[2024-07-12 15:14:39,639]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L001_R1_001.fastq.gz
[2024-07-12 15:14:39,640]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L001_R2_001.fastq.gz
[2024-07-12 15:14:39,640]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L002_R1_001.fastq.gz
[2024-07-12 15:14:39,640]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L002_R2_001.fastq.gz
[2024-07-12 15:14:39,640]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L003_R1_001.fastq.gz
[2024-07-12 15:14:39,640]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L003_R2_001.fastq.gz
[2024-07-12 15:14:39,640]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L004_R1_001.fastq.gz
[2024-07-12 15:14:39,640]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S28_L004_R2_001.fastq.gz
[2024-07-12 15:14:39,640]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S9_L001_R1_001.fastq.gz
[2024-07-12 15:14:39,640]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S9_L001_R2_001.fastq.gz
[2024-07-12 15:14:39,640]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S9_L002_R1_001.fastq.gz
[2024-07-12 15:14:39,640]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT145_mm10_S9_L002_R2_001.fastq.gz
[2024-07-12 15:24:28,188]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978540/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978540/tmp/output.s.bus
[2024-07-12 15:25:09,376]    INFO [count] On-list not provided
[2024-07-12 15:25:09,376]    INFO [count] Copying pre-packaged 10XV2 on-list to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978540/
[2024-07-12 15:25:09,510]    INFO [count] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978540/tmp/output.s.bus
[2024-07-12 15:25:18,236]    INFO [count] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978540/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978540/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978540/10x_version2_whitelist.txt
[2024-07-12 15:26:05,069]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978540/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978540/output.unfiltered.bus
[2024-07-12 15:26:17,399]    INFO [count] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978540/counts_unfiltered/cells_x_tcc from BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978540/output.unfiltered.bus
[2024-07-12 15:26:54,265]    INFO [count] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978540/counts_unfiltered/cells_x_tcc.mtx
[2024-07-12 15:27:12,114]    INFO [count] Writing matrix to h5ad /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978540/counts_unfiltered/adata.h5ad
[2024-07-12 15:27:27,720]    INFO [count] Using index index_std.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978541/ from
[2024-07-12 15:27:27,721]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S10_L001_R1_001.fastq.gz
[2024-07-12 15:27:27,721]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S10_L001_R2_001.fastq.gz
[2024-07-12 15:27:27,721]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S10_L002_R1_001.fastq.gz
[2024-07-12 15:27:27,721]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S10_L002_R2_001.fastq.gz
[2024-07-12 15:27:27,721]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S15_L001_R1_001.fastq.gz
[2024-07-12 15:27:27,721]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S15_L001_R2_001.fastq.gz
[2024-07-12 15:27:27,721]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S15_L002_R1_001.fastq.gz
[2024-07-12 15:27:27,721]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S15_L002_R2_001.fastq.gz
[2024-07-12 15:27:27,721]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L001_R1_001.fastq.gz
[2024-07-12 15:27:27,721]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L001_R2_001.fastq.gz
[2024-07-12 15:27:27,721]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L002_R1_001.fastq.gz
[2024-07-12 15:27:27,721]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L002_R2_001.fastq.gz
[2024-07-12 15:27:27,721]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L003_R1_001.fastq.gz
[2024-07-12 15:27:27,721]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L003_R2_001.fastq.gz
[2024-07-12 15:27:27,721]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L004_R1_001.fastq.gz
[2024-07-12 15:27:27,721]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT146_mm10_S29_L004_R2_001.fastq.gz
[2024-07-12 15:35:45,280]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978541/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978541/tmp/output.s.bus
[2024-07-12 15:36:00,021]    INFO [count] On-list not provided
[2024-07-12 15:36:00,021]    INFO [count] Copying pre-packaged 10XV2 on-list to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978541/
[2024-07-12 15:36:00,299]    INFO [count] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978541/tmp/output.s.bus
[2024-07-12 15:36:13,344]    INFO [count] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978541/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978541/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978541/10x_version2_whitelist.txt
[2024-07-12 15:36:47,037]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978541/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978541/output.unfiltered.bus
[2024-07-12 15:36:57,364]    INFO [count] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978541/counts_unfiltered/cells_x_tcc from BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978541/output.unfiltered.bus
[2024-07-12 15:37:30,580]    INFO [count] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978541/counts_unfiltered/cells_x_tcc.mtx
[2024-07-12 15:37:46,589]    INFO [count] Writing matrix to h5ad /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978541/counts_unfiltered/adata.h5ad
[2024-07-12 15:37:57,159]    INFO [count] Using index index_std.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX4978542/ from
[2024-07-12 15:37:57,160]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S11_L001_R1_001.fastq.gz
[2024-07-12 15:37:57,160]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/scrEXT147_mm10_S11_L001_R2_001.fastq.gz

# Now repeat for De Vriendt dataset

In [ ]:
!kb count -i index_std.idx -g t2g_std.txt --overwrite -x 10xv3 --tcc --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202612/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L004_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S31_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S31_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S31_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S31_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S5_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S5_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S5_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S5_L002_R2_001.fastq.gz

[2025-01-11 09:01:55,513]    INFO [count] Using index index_std.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202612/ from
[2025-01-11 09:01:55,513]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L001_R1_001.fastq.gz
[2025-01-11 09:01:55,513]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L001_R2_001.fastq.gz
[2025-01-11 09:01:55,513]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L002_R1_001.fastq.gz
[2025-01-11 09:01:55,513]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L002_R2_001.fastq.gz
[2025-01-11 09:01:55,513]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L003_R1_001.fastq.gz
[2025-01-11 09:01:55,513]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L003_R2_001.fastq.gz
[2025-01-11 09:01:55,513]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L004_R1_001.fastq.gz
[2025-01-11 09:01:55,513]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S1_L004_R2_001.fastq.gz
[2025-01-11 09:01:55,513]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S31_L001_R1_001.fastq.gz
[2025-01-11 09:01:55,513]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S31_L001_R2_001.fastq.gz
[2025-01-11 09:01:55,513]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S31_L002_R1_001.fastq.gz
[2025-01-11 09:01:55,513]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S31_L002_R2_001.fastq.gz
[2025-01-11 09:01:55,513]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S5_L001_R1_001.fastq.gz
[2025-01-11 09:01:55,513]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S5_L001_R2_001.fastq.gz
[2025-01-11 09:01:55,513]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S5_L002_R1_001.fastq.gz
[2025-01-11 09:01:55,513]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT330_mm10_S5_L002_R2_001.fastq.gz
[2025-01-11 09:40:53,193]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202612/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202612/tmp/output.s.bus
[2025-01-11 09:42:36,285]    INFO [count] On-list not provided
[2025-01-11 09:42:36,286]    INFO [count] Copying pre-packaged 10XV3 on-list to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202612/
[2025-01-11 09:42:37,079]    INFO [count] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202612/tmp/output.s.bus
[2025-01-11 09:43:00,121]    INFO [count] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202612/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202612/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202612/10x_version3_whitelist.txt
[2025-01-11 09:43:44,705]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202612/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202612/output.unfiltered.bus
[2025-01-11 09:44:35,904]    INFO [count] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202612/counts_unfiltered/cells_x_tcc from BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202612/output.unfiltered.bus
[2025-01-11 09:45:09,829]    INFO [count] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202612/counts_unfiltered/cells_x_tcc.mtx
[2025-01-11 09:45:16,177]    INFO [count] Writing matrix to h5ad /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202612/counts_unfiltered/adata.h5ad

In [ ]:
!kb count -i index_std.idx -g t2g_std.txt --overwrite -x 10xv3 --tcc --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202613/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L004_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S32_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S32_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S32_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S32_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S6_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S6_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S6_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S6_L002_R2_001.fastq.gz

[2025-01-11 09:45:41,596]    INFO [count] Using index index_std.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202613/ from
[2025-01-11 09:45:41,596]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L001_R1_001.fastq.gz
[2025-01-11 09:45:41,596]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L001_R2_001.fastq.gz
[2025-01-11 09:45:41,597]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L002_R1_001.fastq.gz
[2025-01-11 09:45:41,597]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L002_R2_001.fastq.gz
[2025-01-11 09:45:41,597]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L003_R1_001.fastq.gz
[2025-01-11 09:45:41,597]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L003_R2_001.fastq.gz
[2025-01-11 09:45:41,597]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L004_R1_001.fastq.gz
[2025-01-11 09:45:41,598]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S2_L004_R2_001.fastq.gz
[2025-01-11 09:45:41,598]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S32_L001_R1_001.fastq.gz
[2025-01-11 09:45:41,598]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S32_L001_R2_001.fastq.gz
[2025-01-11 09:45:41,598]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S32_L002_R1_001.fastq.gz
[2025-01-11 09:45:41,598]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S32_L002_R2_001.fastq.gz
[2025-01-11 09:45:41,598]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S6_L001_R1_001.fastq.gz
[2025-01-11 09:45:41,598]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S6_L001_R2_001.fastq.gz
[2025-01-11 09:45:41,599]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S6_L002_R1_001.fastq.gz
[2025-01-11 09:45:41,599]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT331_mm10_S6_L002_R2_001.fastq.gz
[2025-01-11 10:31:59,556]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202613/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202613/tmp/output.s.bus
[2025-01-11 10:34:20,528]    INFO [count] On-list not provided
[2025-01-11 10:34:20,529]    INFO [count] Copying pre-packaged 10XV3 on-list to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202613/
[2025-01-11 10:34:22,120]    INFO [count] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202613/tmp/output.s.bus
[2025-01-11 10:34:53,180]    INFO [count] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202613/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202613/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202613/10x_version3_whitelist.txt
[2025-01-11 10:35:46,082]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202613/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202613/output.unfiltered.bus
[2025-01-11 10:36:58,327]    INFO [count] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202613/counts_unfiltered/cells_x_tcc from BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202613/output.unfiltered.bus
[2025-01-11 10:37:43,760]    INFO [count] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202613/counts_unfiltered/cells_x_tcc.mtx
[2025-01-11 10:37:48,355]    INFO [count] Writing matrix to h5ad /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202613/counts_unfiltered/adata.h5ad

In [ ]:
!kb count -i index_std.idx -g t2g_std.txt --overwrite -x 10xv3 --tcc --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202614/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S15_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S15_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S15_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S15_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S8_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S8_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S8_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S8_L002_R2_001.fastq.gz

[2025-01-11 10:38:05,597]    INFO [count] Using index index_std.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202614/ from
[2025-01-11 10:38:05,597]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S15_L001_R1_001.fastq.gz
[2025-01-11 10:38:05,597]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S15_L001_R2_001.fastq.gz
[2025-01-11 10:38:05,597]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S15_L002_R1_001.fastq.gz
[2025-01-11 10:38:05,597]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S15_L002_R2_001.fastq.gz
[2025-01-11 10:38:05,597]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S8_L001_R1_001.fastq.gz
[2025-01-11 10:38:05,597]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S8_L001_R2_001.fastq.gz
[2025-01-11 10:38:05,597]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S8_L002_R1_001.fastq.gz
[2025-01-11 10:38:05,597]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT352_mm10_S8_L002_R2_001.fastq.gz
[2025-01-11 11:03:59,742]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202614/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202614/tmp/output.s.bus
[2025-01-11 11:05:42,537]    INFO [count] On-list not provided
[2025-01-11 11:05:42,537]    INFO [count] Copying pre-packaged 10XV3 on-list to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202614/
[2025-01-11 11:05:43,287]    INFO [count] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202614/tmp/output.s.bus
[2025-01-11 11:06:14,048]    INFO [count] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202614/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202614/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202614/10x_version3_whitelist.txt
[2025-01-11 11:07:05,755]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202614/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202614/output.unfiltered.bus
[2025-01-11 11:08:10,683]    INFO [count] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202614/counts_unfiltered/cells_x_tcc from BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202614/output.unfiltered.bus
[2025-01-11 11:08:51,909]    INFO [count] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202614/counts_unfiltered/cells_x_tcc.mtx
[2025-01-11 11:08:55,677]    INFO [count] Writing matrix to h5ad /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202614/counts_unfiltered/adata.h5ad

In [ ]:
!kb count -i index_std.idx -g t2g_std.txt --overwrite -x 10xv3 --tcc --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202615/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S16_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S16_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S16_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S16_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S9_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S9_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S9_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S9_L002_R2_001.fastq.gz

[2025-01-11 11:09:10,947]    INFO [count] Using index index_std.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202615/ from
[2025-01-11 11:09:10,948]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S16_L001_R1_001.fastq.gz
[2025-01-11 11:09:10,948]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S16_L001_R2_001.fastq.gz
[2025-01-11 11:09:10,948]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S16_L002_R1_001.fastq.gz
[2025-01-11 11:09:10,948]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S16_L002_R2_001.fastq.gz
[2025-01-11 11:09:10,948]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S9_L001_R1_001.fastq.gz
[2025-01-11 11:09:10,948]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S9_L001_R2_001.fastq.gz
[2025-01-11 11:09:10,948]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S9_L002_R1_001.fastq.gz
[2025-01-11 11:09:10,948]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT353_mm10_S9_L002_R2_001.fastq.gz
[2025-01-11 11:46:21,799]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202615/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202615/tmp/output.s.bus
[2025-01-11 11:49:11,333]    INFO [count] On-list not provided
[2025-01-11 11:49:11,333]    INFO [count] Copying pre-packaged 10XV3 on-list to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202615/
[2025-01-11 11:49:12,103]    INFO [count] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202615/tmp/output.s.bus
[2025-01-11 11:49:53,485]    INFO [count] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202615/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202615/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202615/10x_version3_whitelist.txt
[2025-01-11 11:51:05,328]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202615/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202615/output.unfiltered.bus
[2025-01-11 11:52:53,951]    INFO [count] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202615/counts_unfiltered/cells_x_tcc from BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202615/output.unfiltered.bus
[2025-01-11 11:53:52,772]    INFO [count] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202615/counts_unfiltered/cells_x_tcc.mtx
[2025-01-11 11:53:57,389]    INFO [count] Writing matrix to h5ad /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX13202615/counts_unfiltered/adata.h5ad

In [ ]:
!kb count -i index_std.idx -g t2g_std.txt --overwrite -x 10xv3 --tcc --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265374/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S19_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S19_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S19_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S19_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S3_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S3_L001_R2_001.fastq.gz

[2025-01-11 11:54:14,428]    INFO [count] Using index index_std.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265374/ from
[2025-01-11 11:54:14,428]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S19_L001_R1_001.fastq.gz
[2025-01-11 11:54:14,428]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S19_L001_R2_001.fastq.gz
[2025-01-11 11:54:14,428]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S19_L002_R1_001.fastq.gz
[2025-01-11 11:54:14,428]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S19_L002_R2_001.fastq.gz
[2025-01-11 11:54:14,428]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S3_L001_R1_001.fastq.gz
[2025-01-11 11:54:14,428]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT356_mm10_S3_L001_R2_001.fastq.gz
[2025-01-11 12:26:51,022]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265374/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265374/tmp/output.s.bus
[2025-01-11 12:30:59,428]    INFO [count] On-list not provided
[2025-01-11 12:30:59,429]    INFO [count] Copying pre-packaged 10XV3 on-list to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265374/
[2025-01-11 12:31:00,168]    INFO [count] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265374/tmp/output.s.bus
[2025-01-11 12:31:53,867]    INFO [count] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265374/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265374/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265374/10x_version3_whitelist.txt
[2025-01-11 12:33:41,766]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265374/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265374/output.unfiltered.bus
[2025-01-11 12:36:55,559]    INFO [count] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265374/counts_unfiltered/cells_x_tcc from BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265374/output.unfiltered.bus
[2025-01-11 12:38:45,531]    INFO [count] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265374/counts_unfiltered/cells_x_tcc.mtx
[2025-01-11 12:38:58,555]    INFO [count] Writing matrix to h5ad /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265374/counts_unfiltered/adata.h5ad

In [ ]:
!kb count -i index_std.idx -g t2g_std.txt --overwrite -x 10xv3 --tcc --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265375/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S20_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S20_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S20_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S20_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S4_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S4_L001_R2_001.fastq.gz

[2025-01-11 12:39:21,603]    INFO [count] Using index index_std.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265375/ from
[2025-01-11 12:39:21,603]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S20_L001_R1_001.fastq.gz
[2025-01-11 12:39:21,603]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S20_L001_R2_001.fastq.gz
[2025-01-11 12:39:21,604]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S20_L002_R1_001.fastq.gz
[2025-01-11 12:39:21,604]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S20_L002_R2_001.fastq.gz
[2025-01-11 12:39:21,604]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S4_L001_R1_001.fastq.gz
[2025-01-11 12:39:21,604]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT357_mm10_S4_L001_R2_001.fastq.gz
[2025-01-11 13:07:50,219]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265375/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265375/tmp/output.s.bus
[2025-01-11 13:12:08,846]    INFO [count] On-list not provided
[2025-01-11 13:12:08,846]    INFO [count] Copying pre-packaged 10XV3 on-list to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265375/
[2025-01-11 13:12:09,605]    INFO [count] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265375/tmp/output.s.bus
[2025-01-11 13:13:05,309]    INFO [count] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265375/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265375/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265375/10x_version3_whitelist.txt
[2025-01-11 13:14:46,308]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265375/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265375/output.unfiltered.bus
[2025-01-11 13:17:31,133]    INFO [count] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265375/counts_unfiltered/cells_x_tcc from BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265375/output.unfiltered.bus
[2025-01-11 13:18:56,742]    INFO [count] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265375/counts_unfiltered/cells_x_tcc.mtx
[2025-01-11 13:19:02,966]    INFO [count] Writing matrix to h5ad /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265375/counts_unfiltered/adata.h5ad

In [ ]:
!kb count -i index_std.idx -g t2g_std.txt --overwrite -x 10xv3 --tcc --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265376/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT358_mm10_S11_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT358_mm10_S11_L001_R2_001.fastq.gz

[2025-01-11 13:19:21,969]    INFO [count] Using index index_std.idx to generate BUS file to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265376/ from
[2025-01-11 13:19:21,969]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT358_mm10_S11_L001_R1_001.fastq.gz
[2025-01-11 13:19:21,969]    INFO [count]         /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT358_mm10_S11_L001_R2_001.fastq.gz
[2025-01-11 14:03:54,323]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265376/output.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265376/tmp/output.s.bus
[2025-01-11 14:10:02,209]    INFO [count] On-list not provided
[2025-01-11 14:10:02,210]    INFO [count] Copying pre-packaged 10XV3 on-list to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265376/
[2025-01-11 14:10:03,039]    INFO [count] Inspecting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265376/tmp/output.s.bus
[2025-01-11 14:11:27,923]    INFO [count] Correcting BUS records in /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265376/tmp/output.s.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265376/tmp/output.s.c.bus with on-list /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265376/10x_version3_whitelist.txt
[2025-01-11 14:14:17,197]    INFO [count] Sorting BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265376/tmp/output.s.c.bus to /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265376/output.unfiltered.bus
[2025-01-11 14:19:22,176]    INFO [count] Generating count matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265376/counts_unfiltered/cells_x_tcc from BUS file /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265376/output.unfiltered.bus
[2025-01-11 14:21:31,136]    INFO [count] Reading matrix /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265376/counts_unfiltered/cells_x_tcc.mtx
[2025-01-11 14:21:37,149]    INFO [count] Writing matrix to h5ad /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265376/counts_unfiltered/adata.h5ad

In [ ]:
!kb count -i index_std.idx -g t2g_std.txt --overwrite -x 10xv3 --tcc --h5ad -o /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX12265377/ /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S10_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S10_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S10_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S10_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L001_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L001_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L002_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L002_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L003_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L003_R2_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L004_R1_001.fastq.gz /content/drive/MyDrive/pituitary_atlas/Unstructured/fastqs/devriendt/scrEXT364_mm10_S6_L004_R2_001.fastq.gz

# Loop for TCC processing for all normal datasets

In [ ]:
import os
datasets_already_downloaded = os.listdir('/content/drive/MyDrive/pituitary_atlas/processed/tcc/')

In [ ]:
#iterating through the table and getting datasets
import subprocess
for i in range(len(df)-1,-1,-1):
  SRA_ID = df.iloc[i]['SRA_ID']
  experiment_type = df.iloc[i]['Modality']
  tech = df.iloc[i]['10X version']
  #if experiment_type is not sc print SRA_ID and continue
  if experiment_type != "sc":
    print(f"SRA: {SRA_ID} . Experiment type is not sc: {experiment_type}")
    continue
  #print all of these
  print("""
  SRA_ID: {}
  experiment_type: {}
  tech: {}
  """.format(SRA_ID,experiment_type,tech))

  #check if SRA_ID is already downloaded
  if SRA_ID in datasets_already_downloaded:
    print("SRA_ID already aligned for tcc")
    continue

  #if no folder in tcc
  if not os.path.exists('/content/drive/MyDrive/pituitary_atlas/processed/tcc/' + SRA_ID):
    os.mkdir('/content/drive/MyDrive/pituitary_atlas/processed/tcc/' + SRA_ID)

  directory = '/content/drive/MyDrive/pituitary_atlas/raw/' + SRA_ID
  files = os.listdir(directory)
  all_fastqs = []
  for file in files:
      if file.endswith('.fastq.gz'):
          all_fastqs.append(directory + '/' + file)
  #if there are fastq files with the same string before .sralite, only keep the two largest of them in the list
  #does any of the files have lite in name
  lite_name = True if any(x for x in all_fastqs if 'lite' in x) else False
  if lite_name:
    id_tags = [x.split('lite')[0] for x in all_fastqs]

  else:
    id_tags = [x.split('_R1_')[0] for x in all_fastqs if '_R1_' in x]

  print(id_tags)
  all_fastqs_final = []
  unique_tags= list(set(id_tags))
  for tag in unique_tags:
    fastqs_with_tag = [x for x in all_fastqs if tag in x]
    if len(fastqs_with_tag) > 1:
      fastqs_with_tag.sort(key=lambda x: os.path.getsize(x), reverse=True)
      all_fastqs_final.append(fastqs_with_tag[1])
      all_fastqs_final.append(fastqs_with_tag[0])


  all_fastqs = all_fastqs_final
  #if there arent at least 2 fastqs then continue
  if len(all_fastqs) < 2:
    print("Not enough fastqs")
    continue

  if experiment_type == "sc":
    print("Running kb count")
    output_dir = f"/content/drive/MyDrive/pituitary_atlas/processed/tcc/{SRA_ID}/"
    kbcount_tcc_command1 = f"kb count -i index_std.idx -g t2g_std.txt --overwrite -x {tech} --tcc --h5ad -o {output_dir} {' '.join(all_fastqs)}"
    print(kbcount_tcc_command1)
    subprocess.run(kbcount_tcc_command1, shell=True)


  #elif experiment_type == "multi_rna":

    #from all_fastqs remove ones that contain "atac"
  #  all_fastqs = [x for x in all_fastqs if "atac" not in x]


  #  print("Running kb count")
  #  output_dir = f"/content/drive/MyDrive/pituitary_atlas/processed/tcc/{SRA_ID}/"
  #  kbcount_tcc_command1 = f"kb count -i index_std.idx -g t2g_std.txt --overwrite -x {tech} --tcc --h5ad -w /content/10xMultiome/gex_737K-arc-v1.txt -o {output_dir} {' '.join(all_fastqs)}"
  #  print(kbcount_tcc_command1)
  #  subprocess.run(kbcount_tcc_command1, shell=True)
  else:
    print(f"Experiment not single cell: {experiment_type}")

SRA: SRX29174030 . Experiment type is not sc: sn
SRA: SRX29174029 . Experiment type is not sc: sn
SRA: SRX29174028 . Experiment type is not sc: sn
SRA: SRX29174027 . Experiment type is not sc: sn

  SRA_ID: SRX25982299
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX25982300
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX25982301
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX25982298
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX25982297
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX25982296
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX25982295
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX25982294
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX26708357
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc
SRA: SRX25736229 . Experiment type is not sc: sn
SRA: SRX25736228 . Experiment type is not sc: sn
SRA: SRX25736227 . Experiment type is not sc: sn
SRA: SRX25736226 . Experiment type is not sc: sn
SRA: SRX25736225 . Experiment type is not sc: sn
SRA: SRX25736224 . Experiment type is not sc: sn
SRA: SRX25736223 . Experiment type is not sc: sn
SRA: SRX25736222 . Experiment type is not sc: sn
SRA: SRX25736221 . Experiment type is not sc: sn
SRA: SRX25736220 . Experiment type is not sc: sn
SRA: SRX25736219 . Experiment type is not sc: sn

  SRA_ID: ERX12265377
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: ERX12265376
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: ERX12265375
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: ERX12265374
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: ERX13202615
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: ERX13202614
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: ERX13202613
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: ERX13202612
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX18716675
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX18716674
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX18716673
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: SRX18716672
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc
SRA: SRX21902370 . Experiment type is not sc: multi_rna
SRA: SRX21902369 . Experiment type is not sc: multi_rna
SRA: SRX21902368 . Experiment type is not sc: multi_rna
SRA: SRX21902367 . Experiment type is not sc: multi_rna
SRA: SRX21902366 . Experiment type is not sc: multi_rna
SRA: SRX21902365 . Experiment type is not sc: multi_rna
SRA: SRX21902364 . Experiment type is not sc: multi_rna
SRA: SRX21902356 . Experiment type is not sc: multi_rna
SRA: SRX21902355 . Experiment type is not sc: multi_rna
SRA: SRX21902354 . Experiment type is not sc: multi_rna
SRA: SRX21902353 . Experiment type is not sc: multi_rna
SRA: SRX21902352 . Experiment type is not sc: multi_rna
SRA: SRX21902351 . Experiment type is not sc: multi_rna
SRA: SRX21902350 . Experiment type is not sc: multi_rna
SRA: SRX21902349 . Experiment type is not sc: multi_rna
SRA: SRX21902348 . Experiment type is not sc: multi_rna

  SRA_ID: SRX19698100
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX19698101
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX19698102
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX25839821
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX25839820
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX21636477
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX21636476
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX22219346
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX22219345
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: SRX24151439
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX24151438
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX24151437
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX24151436
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX24151435
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX24151434
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX24151433
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX24151432
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX25532499
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: SRX25532498
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: SRX7377166
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: SRX7377164
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc
SRA: SRX20679984 . Experiment type is not sc: multi_rna

  SRA_ID: SRX9637224
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX8497094
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX8497093
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX8497092
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX8602212
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX8602211
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX15581371
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX15581370
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX18224109
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: SRX18224108
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: SRX18224107
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX18224106
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX18224105
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: SRX18224104
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc
SRA: SRX13290062 . Experiment type is not sc: sn
SRA: SRX13290061 . Experiment type is not sc: sn
SRA: SRX13290060 . Experiment type is not sc: sn
SRA: SRX13290059 . Experiment type is not sc: sn
SRA: SRX13290058 . Experiment type is not sc: sn
SRA: SRX13290057 . Experiment type is not sc: sn

  SRA_ID: SRX21986116
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX21986115
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX21986114
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX21986113
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX21986112
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX21986111
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX21986110
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX21986109
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX21986108
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX21986107
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX21986106
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX21986105
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX21170825
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX21170824
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX21170823
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: ERX7593484
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: ERX7593483
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: ERX7593482
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: ERX7593481
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: ERX4978544
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: ERX4978543
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: ERX4978542
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: ERX4978541
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: ERX4978540
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: ERX4978539
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: ERX4978538
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: ERX4978537
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: SRX21241801
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX21241800
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX21241799
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX21241798
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX9528565
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: SRX9528564
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: SRX7874746
  experiment_type: sc
  tech: DROPSEQ

SRA_ID already aligned for tcc

  SRA_ID: SRX7874745
  experiment_type: sc
  tech: DROPSEQ

SRA_ID already aligned for tcc

  SRA_ID: SRX7874744
  experiment_type: sc
  tech: DROPSEQ

SRA_ID already aligned for tcc

  SRA_ID: SRX7874743
  experiment_type: sc
  tech: DROPSEQ

SRA_ID already aligned for tcc

  SRA_ID: SRX7874742
  experiment_type: sc
  tech: DROPSEQ

SRA_ID already aligned for tcc

  SRA_ID: SRX7874741
  experiment_type: sc
  tech: DROPSEQ

SRA_ID already aligned for tcc

  SRA_ID: SRX7874740
  experiment_type: sc
  tech: DROPSEQ

SRA_ID already aligned for tcc

  SRA_ID: SRX7874739
  experiment_type: sc
  tech: DROPSEQ

SRA_ID already aligned for tcc

  SRA_ID: SRX7874738
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: SRX7874737
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: SRX6699503
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: SRX6699502
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: SRX5292053
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: SRX4736338
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: SRX4736337
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc
SRA: SRX8489842 . Experiment type is not sc: sn
SRA: SRX8489841 . Experiment type is not sc: sn
SRA: SRX8489840 . Experiment type is not sc: sn
SRA: SRX8489839 . Experiment type is not sc: sn
SRA: SRX8489838 . Experiment type is not sc: sn
SRA: SRX8489837 . Experiment type is not sc: sn
SRA: SRX8489836 . Experiment type is not sc: sn
SRA: SRX8489835 . Experiment type is not sc: sn
SRA: SRX8489834 . Experiment type is not sc: sn

  SRA_ID: SRX8489824
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX8489823
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX8489822
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

  SRA_ID: SRX8489821
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX8489820
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX8489819
  experiment_type: sc
  tech: 10XV3

SRA_ID already aligned for tcc

  SRA_ID: SRX8489818
  experiment_type: sc
  tech: 10XV2

SRA_ID already aligned for tcc

# Downloading new Cheung et al (2025) ageing data

In [ ]:
# 2. Define the target directory in Google Drive
output_dir = "/content/drive/MyDrive/pituitary_atlas/raw/SRX29174027/"

# 3. Create the directory if it doesn't exist
# The -p flag ensures that parent directories are also created if they don't exist
!mkdir -p "$output_dir"

# 4. Change to the target directory for prefetch
# This is important so prefetch downloads directly into the desired location
%cd "$output_dir"

# 5. Pre-fetch the .sra files
# --max-size 0 means no size limit
# Ensure you are in the correct directory before running prefetch
!prefetch --max-size 0 SRR33975506

# Optional: Verify the downloaded files
!ls -lh "$output_dir"

/content/drive/MyDrive/pituitary_atlas/raw/SRX29174027

2025-06-27T14:44:17 prefetch.2.11.3: Current preference is set to retrieve SRA Normalized Format files with full base quality scores.
2025-06-27T14:44:18 prefetch.2.11.3: 1) Downloading 'SRR33975506'...
2025-06-27T14:44:18 prefetch.2.11.3: SRA Normalized Format file is being retrieved, if this is different from your preference, it may be due to current file availability.
2025-06-27T14:44:18 prefetch.2.11.3:  Downloading via HTTPS...
2025-06-27T15:16:08 prefetch.2.11.3:  HTTPS download succeed
2025-06-27T15:16:08 prefetch.2.11.3:   verifying 'SRR33975506'...
2025-06-27T15:18:30 prefetch.2.11.3:  'SRR33975506' is valid
2025-06-27T15:18:30 prefetch.2.11.3: 1) 'SRR33975506' was downloaded successfully
2025-06-27T15:18:31 prefetch.2.11.3: 'SRR33975506' has 0 unresolved dependencies
total 4.0K
drwx------ 2 root root 4.0K Jun 27 15:18 SRR33975506

In [ ]:
# Define the SRA file path (where your SRR33975506.sra is located)
# Based on your prompt, it seems SRR33975506.sra is DIRECTLY inside this folder.
sra_input_dir = "/content/drive/MyDrive/pituitary_atlas/raw/SRX29174027/SRR33975506/"

# Define the final output directory for FASTQ files (can be the same as sra_input_dir if you prefer)
fastq_output_dir = "/content/drive/MyDrive/pituitary_atlas/raw/SRX29174027/SRR33975506/fastqs/" # Let's put FASTQs in a separate 'fastqs' folder for organization

# Define a temporary directory *on Google Drive* for fasterq-dump's intermediate files
# This is CRITICAL for large files to avoid exhausting Colab's local storage
temp_dir_on_drive = "/content/drive/MyDrive/pituitary_atlas/raw/SRX29174027/SRR33975506/temp_fasterq_dump/" # Create a dedicated temp folder on Drive

# Create all necessary directories
!mkdir -p "$sra_input_dir"
!mkdir -p "$fastq_output_dir"
!mkdir -p "$temp_dir_on_drive" # Create the temp directory on Drive

# Change the current working directory to where the SRA files are.
# This makes it easier for fasterq-dump to find them by just their name.
%cd "$sra_input_dir"

# Verify the SRA file exists in the current directory
print(f"Checking for SRR33975506.sra in {sra_input_dir}:")
!ls -lh SRR33975506.sra

!fastq-dump SRR33975506.sra -O "$fastq_output_dir"  --split-files --gzip

print("\nFinished fasterq-dump.")

# Optional: Verify the generated FASTQ files
print(f"\nFASTQ files generated in {fastq_output_dir}:")
!ls -lh "$fastq_output_dir"/*.fastq

# Optional: Clean up temporary files on Drive if successful
# Be careful with rm -rf! Only uncomment if you are sure.
# !rm -rf "$temp_dir_on_drive"/*

/content/drive/MyDrive/pituitary_atlas/raw/SRX29174027/SRR33975506
Checking for SRR33975506.sra in /content/drive/MyDrive/pituitary_atlas/raw/SRX29174027/SRR33975506/:
-rw------- 1 root root 26G Jun 27 15:16 SRR33975506.sra

Starting fasterq-dump...

In [ ]:
# 2. Define the target directory in Google Drive
output_dir = "/content/drive/MyDrive/pituitary_atlas/raw/SRX29174028/"

# 3. Create the directory if it doesn't exist
# The -p flag ensures that parent directories are also created if they don't exist
!mkdir -p "$output_dir"

# 4. Change to the target directory for prefetch
# This is important so prefetch downloads directly into the desired location
%cd "$output_dir"

# 5. Pre-fetch the .sra files
# --max-size 0 means no size limit
# Ensure you are in the correct directory before running prefetch
!prefetch --max-size 0 SRR33975505

# Optional: Verify the downloaded files
!ls -lh "$output_dir"

/content/drive/MyDrive/pituitary_atlas/raw/SRX29174028

2025-06-27T15:18:33 prefetch.2.11.3: Current preference is set to retrieve SRA Normalized Format files with full base quality scores.
2025-06-27T15:18:34 prefetch.2.11.3: 1) Downloading 'SRR33975505'...
2025-06-27T15:18:34 prefetch.2.11.3: SRA Normalized Format file is being retrieved, if this is different from your preference, it may be due to current file availability.
2025-06-27T15:18:34 prefetch.2.11.3:  Downloading via HTTPS...
2025-06-27T15:49:11 prefetch.2.11.3:  HTTPS download succeed
2025-06-27T15:49:11 prefetch.2.11.3:   verifying 'SRR33975505'...
2025-06-27T15:51:37 prefetch.2.11.3:  'SRR33975505' is valid
2025-06-27T15:51:37 prefetch.2.11.3: 1) 'SRR33975505' was downloaded successfully
2025-06-27T15:51:38 prefetch.2.11.3: 'SRR33975505' has 0 unresolved dependencies
total 4.0K
drwx------ 2 root root 4.0K Jun 27 15:51 SRR33975505

In [ ]:
output_dir = "/content/drive/MyDrive/pituitary_atlas/raw/SRX29174028/SRR33975505/"

# 3. Create the directory if it doesn't exist
# The -p flag ensures that parent directories are also created if they don't exist
!mkdir -p "$output_dir"

# 4. Change to the target directory for prefetch
# This is important so prefetch downloads directly into the desired location
%cd "$output_dir"
!fasterq-dump SRR33975505.sra -O "$output_dir" -e 8 --split-files

/content/drive/MyDrive/pituitary_atlas/raw/SRX29174028/SRR33975505
1900-01-00T00:00:00 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='11'
1900-01-00T00:00:00 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='26'
1900-01-00T00:00:00 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='17'
1900-01-00T00:00:00 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='24'
1900-01-00T00:00:00 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='19'
1900-01-00T00:00:00 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='21'
1900-01-00T00:00:00 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='15'
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='14'
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='17'
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1 rcFS,rcFile,rcWriting,rcStorage,rcExhausted)
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1:  unknown while destroying file within file system module - unknown system error 'No space left on device(28)'
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1 rcFS,rcFile,rcDestroying,rcNoObj,rcUnknown)
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='21'
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1 rcFS,rcFile,rcWriting,rcStorage,rcExhausted)
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='11'
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1 rcFS,rcFile,rcWriting,rcStorage,rcExhausted)
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='15'
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1 rcFS,rcFile,rcWriting,rcStorage,rcExhausted)
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='19'
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1 rcFS,rcFile,rcWriting,rcStorage,rcExhausted)
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='24'
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1 rcFS,rcFile,rcWriting,rcStorage,rcExhausted)
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1:  unknown while destroying file within file system module - unknown system error 'No space left on device(28)'
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1 rcFS,rcFile,rcDestroying,rcNoObj,rcUnknown)
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1:  unknown while destroying file within file system module - unknown system error 'No space left on device(28)'
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1:  unknown while destroying file within file system module - unknown system error 'No space left on device(28)'
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1 rcFS,rcFile,rcDestroying,rcNoObj,rcUnknown)
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1 rcFS,rcFile,rcDestroying,rcNoObj,rcUnknown)
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='20'
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1:  unknown while destroying file within file system module - unknown system error 'No space left on device(28)'
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1 rcFS,rcFile,rcWriting,rcStorage,rcExhausted)
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1 rcFS,rcFile,rcDestroying,rcNoObj,rcUnknown)
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1:  unknown while destroying file within file system module - unknown system error 'No space left on device(28)'
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1 rcFS,rcFile,rcDestroying,rcNoObj,rcUnknown)
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='16'
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1 rcFS,rcFile,rcWriting,rcStorage,rcExhausted)
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='14'
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1 rcFS,rcFile,rcWriting,rcStorage,rcExhausted)
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='26'
2025-06-27T22:07:44 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1 rcFS,rcFile,rcWriting,rcStorage,rcExhausted)
fasterq-dump quit with error code 3

In [ ]:
# 2. Define the target directory in Google Drive
output_dir = "/content/drive/MyDrive/pituitary_atlas/raw/SRX29174029/"

# 3. Create the directory if it doesn't exist
# The -p flag ensures that parent directories are also created if they don't exist
!mkdir -p "$output_dir"

# 4. Change to the target directory for prefetch
# This is important so prefetch downloads directly into the desired location
%cd "$output_dir"

# 5. Pre-fetch the .sra files
# --max-size 0 means no size limit
# Ensure you are in the correct directory before running prefetch
!prefetch --max-size 0 SRR33975504

# Optional: Verify the downloaded files
!ls -lh "$output_dir"

/content/drive/MyDrive/pituitary_atlas/raw/SRX29174029

2025-06-27T15:51:40 prefetch.2.11.3: Current preference is set to retrieve SRA Normalized Format files with full base quality scores.
2025-06-27T15:51:41 prefetch.2.11.3: 1) Downloading 'SRR33975504'...
2025-06-27T15:51:41 prefetch.2.11.3: SRA Normalized Format file is being retrieved, if this is different from your preference, it may be due to current file availability.
2025-06-27T15:51:41 prefetch.2.11.3:  Downloading via HTTPS...
2025-06-27T16:25:17 prefetch.2.11.3:  HTTPS download succeed
2025-06-27T16:25:17 prefetch.2.11.3:   verifying 'SRR33975504'...

In [ ]:
output_dir = "/content/drive/MyDrive/pituitary_atlas/raw/SRX29174029/SRR33975504/"

# 3. Create the directory if it doesn't exist
# The -p flag ensures that parent directories are also created if they don't exist
!mkdir -p "$output_dir"

# 4. Change to the target directory for prefetch
# This is important so prefetch downloads directly into the desired location
%cd "$output_dir"
!fasterq-dump SRR33975504.sra -O "$output_dir" -e 8 --split-files

/content/drive/MyDrive/pituitary_atlas/raw/SRX29174029/SRR33975504
2025-06-27T22:21:30 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='14'
2025-06-27T22:21:30 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1:  unknown while destroying file within file system module - unknown system error 'No space left on device(28)'
2025-06-27T22:21:30 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1 rcFS,rcFile,rcDestroying,rcNoObj,rcUnknown)
2025-06-27T22:21:30 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1:  unknown while destroying file within file system module - unknown system error 'No space left on device(28)'
2025-06-27T22:21:30 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1 rcFS,rcFile,rcDestroying,rcNoObj,rcUnknown)
2025-06-27T22:21:30 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='14'
2025-06-27T22:21:30 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1 rcFS,rcFile,rcWriting,rcStorage,rcExhausted)
2025-06-27T22:21:30 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1:  unknown while destroying file within file system module - unknown system error 'No space left on device(28)'
2025-06-27T22:21:30 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1 rcFS,rcFile,rcDestroying,rcNoObj,rcUnknown)
2025-06-27T22:21:30 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1:  unknown while destroying file within file system module - unknown system error 'No space left on device(28)'
2025-06-27T22:21:30 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1 rcFS,rcFile,rcDestroying,rcNoObj,rcUnknown)
2025-06-27T22:21:30 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='12'
2025-06-27T22:21:30 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1 rcFS,rcFile,rcWriting,rcStorage,rcExhausted)
2025-06-27T22:21:30 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='19'
2025-06-27T22:21:30 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1 rcFS,rcFile,rcWriting,rcStorage,rcExhausted)
2025-06-27T22:21:30 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1:  unknown while destroying file within file system module - unknown system error 'No space left on device(28)'
2025-06-27T22:21:30 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1 rcFS,rcFile,rcDestroying,rcNoObj,rcUnknown)
fasterq-dump quit with error code 3

In [ ]:
# 2. Define the target directory in Google Drive
output_dir = "/content/drive/MyDrive/pituitary_atlas/raw/SRX29174030/"

# 3. Create the directory if it doesn't exist
# The -p flag ensures that parent directories are also created if they don't exist
!mkdir -p "$output_dir"

# 4. Change to the target directory for prefetch
# This is important so prefetch downloads directly into the desired location
%cd "$output_dir"

# 5. Pre-fetch the .sra files
# --max-size 0 means no size limit
# Ensure you are in the correct directory before running prefetch
!prefetch --max-size 0 SRR33975503

# Optional: Verify the downloaded files
!ls -lh "$output_dir"

In [ ]:
output_dir = "/content/drive/MyDrive/pituitary_atlas/raw/SRX29174030/SRR33975503/"

# 3. Create the directory if it doesn't exist
# The -p flag ensures that parent directories are also created if they don't exist
!mkdir -p "$output_dir"

# 4. Change to the target directory for prefetch
# This is important so prefetch downloads directly into the desired location
%cd "$output_dir"
!fasterq-dump SRR33975503.sra -O "$output_dir" -e 8 --split-files

/content/drive/MyDrive/pituitary_atlas/raw/SRX29174030/SRR33975503
2025-06-27T22:33:03 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='18'
2025-06-27T22:33:03 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1:  unknown while destroying file within file system module - unknown system error 'No space left on device(28)'
2025-06-27T22:33:03 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1 rcFS,rcFile,rcDestroying,rcNoObj,rcUnknown)
2025-06-27T22:33:03 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='21'
2025-06-27T22:33:03 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1 rcFS,rcFile,rcWriting,rcStorage,rcExhausted)
2025-06-27T22:33:03 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='23'
2025-06-27T22:33:03 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1 rcFS,rcFile,rcWriting,rcStorage,rcExhausted)
2025-06-27T22:33:03 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1:  unknown while destroying file within file system module - unknown system error 'No space left on device(28)'
2025-06-27T22:33:03 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1 rcFS,rcFile,rcDestroying,rcNoObj,rcUnknown)
2025-06-27T22:33:03 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='20'
2025-06-27T22:33:03 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1 rcFS,rcFile,rcWriting,rcStorage,rcExhausted)
2025-06-27T22:33:03 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='18'
2025-06-27T22:33:03 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1 rcFS,rcFile,rcWriting,rcStorage,rcExhausted)
2025-06-27T22:33:03 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1:  unknown while destroying file within file system module - unknown system error 'No space left on device(28)'
2025-06-27T22:33:03 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1 rcFS,rcFile,rcDestroying,rcNoObj,rcUnknown)
2025-06-27T22:33:03 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1: storage exhausted while writing file within file system module - system bad file descriptor error fd='24'
2025-06-27T22:33:03 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:464:KSysFileWrite_v1 rcFS,rcFile,rcWriting,rcStorage,rcExhausted)
2025-06-27T22:33:03 fasterq-dump.2.11.3 err: libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1:  unknown while destroying file within file system module - unknown system error 'No space left on device(28)'
2025-06-27T22:33:03 fasterq-dump.2.11.3 err: join_results.c destroy_join_printer() release_file() -> RC(libs/kfs/unix/sysfile.c:108:KSysFileDestroy_v1 rcFS,rcFile,rcDestroying,rcNoObj,rcUnknown)
fasterq-dump quit with error code 3

## The rest is code to optimise storage space

## Compress all bus files!

In [ ]:
%%bash
git clone https://github.com/BUStools/bustools && \
cd bustools && \
mkdir build && \
cd build && \
cmake .. && \
make && \
make install

-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Configuring done (2.1s)
-- Generating done (0.0s)
-- Build files have been written to: /content/bustools/build
[  3%] Building CXX object src/CMakeFiles/bustools_core.dir/BUSData.cpp.o
[  7%] Building CXX object src/CMakeFiles/bustools_core.dir/Common.cpp.o
[ 11%] Building CXX object src/CMakeFiles/bustools_core.dir/bustools_capture.cpp.o
[ 15%] Building CXX object src/CMakeFiles/bustools_core.dir/bustools_clusterhist.cpp.o
[ 19%] Building CXX object src/CMakeFiles/bustools_core.dir/bustools_collapse.cpp.o
[ 23%] Building CXX object src/CMakeFiles/bustools_core.dir/bustools_compress.cpp.o
[ 26%] Building CXX object src/CMakeFiles/bustools_core.dir/bustools_correct.cpp.o
[ 30%] Building CXX object src/CMakeFiles/bustools_core.dir/bustools_count.cpp.o
[ 34%] Building CXX object src/CMakeFiles/bustools_core.dir/bustools_decompress.cpp.o
[ 38%] Building CXX object src/CMakeFiles/bustools_core.dir/bustools_extract.cpp.o
[ 42%] Building CXX object src/CMakeFiles/bustools_core.dir/bustools_inspect.cpp.o
[ 46%] Building CXX object src/CMakeFiles/bustools_core.dir/bustools_linker.cpp.o
[ 50%] Building CXX object src/CMakeFiles/bustools_core.dir/bustools_main.cpp.o
[ 53%] Building CXX object src/CMakeFiles/bustools_core.dir/bustools_mash.cpp.o
[ 57%] Building CXX object src/CMakeFiles/bustools_core.dir/bustools_merge.cpp.o
[ 61%] Building CXX object src/CMakeFiles/bustools_core.dir/bustools_predict.cpp.o
[ 65%] Building CXX object src/CMakeFiles/bustools_core.dir/bustools_project.cpp.o
[ 69%] Building CXX object src/CMakeFiles/bustools_core.dir/bustools_sort.cpp.o
[ 73%] Building CXX object src/CMakeFiles/bustools_core.dir/bustools_text.cpp.o
[ 76%] Building CXX object src/CMakeFiles/bustools_core.dir/bustools_umicorrect.cpp.o
[ 80%] Building CXX object src/CMakeFiles/bustools_core.dir/bustools_whitelist.cpp.o
[ 84%] Building CXX object src/CMakeFiles/bustools_core.dir/hash.cpp.o
[ 88%] Building C object src/CMakeFiles/bustools_core.dir/roaring.c.o
[ 92%] Linking CXX static library libbustools_core.a
[ 92%] Built target bustools_core
[ 96%] Building CXX object src/CMakeFiles/bustools.dir/bustools_main.cpp.o
[100%] Linking CXX executable bustools
[100%] Built target bustools
[ 92%] Built target bustools_core
[100%] Built target bustools
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/bin/bustools

Cloning into 'bustools'...
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


release mode

In [ ]:
import os
import subprocess

# Directory to scan
directory = '/content/drive/MyDrive/pituitary_atlas/processed'

# Walk through the directory and find all .bus files
for root, dirs, files in os.walk(directory):
    for file in files:
        if file.endswith('.bus'):
            file_path = os.path.join(root, file)
            print(f'Compressing {file_path}')
            command = f'bustools compress {file_path} -o {file_path}'
            subprocess.run(command, shell=True)

Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8489818/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8489818/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8489819/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8489819/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8489820/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8489820/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRR6364452/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRR6364453/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRR6364454/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRR6364455/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERR1869557/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERR1869558/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERR1869559/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERR1869560/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERR1869561/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERR1869562/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX4736337/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX4736337/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX4736338/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX4736338/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX4978537/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX4978537/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX4978538/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX4978538/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX4978539/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX4978539/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX4978540/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX4978540/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX4978541/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX4978541/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX4978542/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX4978542/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX4978543/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX4978543/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX4978544/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX4978544/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8489821/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8489821/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8489822/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8489822/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8489823/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8489823/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8489824/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8489824/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX5292053/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX5292053/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX6699502/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX6699502/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX6699503/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX6699503/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7874737/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7874737/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7874738/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7874738/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7874739/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7874739/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7874740/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7874740/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7874741/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7874741/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7874742/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7874742/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7874743/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7874743/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7874744/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7874744/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7874745/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7874745/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7874746/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7874746/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX9528564/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX9528564/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX9528565/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX9528565/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21241798/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21241798/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21241799/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21241799/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21241801/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21241801/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX7593481/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX7593481/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX7593482/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX7593482/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX7593483/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX7593483/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX7593484/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/ERX7593484/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21170823/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21170823/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21170824/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21170824/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986105/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986105/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986106/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986106/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986107/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986107/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986108/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986108/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986109/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986109/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986110/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986110/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986111/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986111/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986112/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986112/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986113/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986113/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986114/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986114/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986115/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986115/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986116/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21986116/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21241800/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21241800/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX18224104/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX18224104/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX18224105/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX18224105/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX18224106/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX18224106/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX18224107/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX18224107/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX18224108/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX18224108/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX18224109/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX18224109/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX15581370/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX15581370/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX15581371/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX15581371/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8602211/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8602211/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8602212/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8602212/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8497092/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8497092/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8497093/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8497093/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8497094/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX8497094/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX9637224/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX9637224/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7377164/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7377164/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7377166/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX7377166/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/MEMB-BRF1-MUT1/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/MEMB-BRF1-MUT1/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/MMP3-CONT1/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/MMP3-CONT1/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/MMP3-MUT1/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/MMP3-MUT1/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/MMYAPCont-C1/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/MMYAPCont-C1/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/MMYAPCont-C2/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/MMYAPCont-C2/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/MMYAPTetO-M1/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/MMYAPTetO-M1/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/MMYAPTetO-M2/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/MMYAPTetO-M2/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/MF2_MM5_CONTA/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/MF2_MM5_CONTA/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/sox2egfp_p3/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/sox2egfp_p3/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/sox2egfp_p15/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/sox2egfp_p15/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/sox2egfp_p56/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/sox2egfp_p56/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/sox2egfp_14m/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/sox2egfp_14m/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/e145wls_ctrl/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/e145wls_ctrl/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/e145wls_mut/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/e145wls_mut/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX24151432/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX24151432/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX24151433/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX24151433/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX24151434/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX24151434/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX24151435/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX24151435/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX24151436/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX24151436/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX24151437/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX24151437/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX24151438/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX24151438/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX24151439/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX24151439/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX22219346/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX22219346/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21636476/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21636476/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21636477/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/tcc/SRX21636477/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/nac/SRX8489818/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/nac/SRX8489818/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/nac/SRX8489819/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/nac/SRX8489819/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/nac/SRX8489820/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/nac/SRX8489820/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/nac/SRX8489821/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/nac/SRX8489821/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/nac/SRX8489822/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/nac/SRX8489822/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/nac/SRX8489823/output.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/nac/SRX8489823/output.unfiltered.bus
Compressing /content/ddrive/MyDrive/pituitary_atlas/processed/nac/SRX8489824/output.bus

In [ ]:
# Directory to scan
import os
directory = '/content/drive/MyDrive/pituitary_atlas/processed'

# Walk through the directory and find all .bus files
for root, dirs, files in os.walk(directory):
    for file in files:
        if file.endswith('.bus'):
          #delete file
          print(f'Deleting {os.path.join(root, file)}')
          #print size
          print(f'Size: {os.path.getsize(os.path.join(root, file))}')
          os.remove(os.path.join(root, file))

Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX17837195/output.bus
Size: 364604241
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX17837196/output.bus
Size: 309513041
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX17837197/output.bus
Size: 456506801
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX17837198/output.bus
Size: 436741393
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX17837199/output.bus
Size: 347011153
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX17837200/output.bus
Size: 429347697
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX17837201/output.bus
Size: 450219633
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX17837202/output.bus
Size: 399632849
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX10689726/output.bus
Size: 1046971985
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX10689727/output.bus
Size: 926407089
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX10689729/output.bus
Size: 1106093905
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX10689725/output.bus
Size: 1192768721
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX10689728/output.bus
Size: 891519089
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/ERX10689730/output.bus
Size: 275984529
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25982300/output.bus
Size: 1936088913
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25982300/output.unfiltered.bus
Size: 833712017
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25982301/output.bus
Size: 2185232721
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25982301/output.unfiltered.bus
Size: 1287633297
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25982298/output.bus
Size: 2029475281
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25982298/output.unfiltered.bus
Size: 977549969
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25982297/output.bus
Size: 2065613489
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25982297/output.unfiltered.bus
Size: 1017302417
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25982296/output.bus
Size: 1698094449
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25982296/output.unfiltered.bus
Size: 1039612529
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25982295/output.bus
Size: 2053459441
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25982295/output.unfiltered.bus
Size: 1145946065
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25982294/output.bus
Size: 2854962993
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25982294/output.unfiltered.bus
Size: 1585274769
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX26708357/output.bus
Size: 12782142481
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX26708357/output.unfiltered.bus
Size: 3235025937
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25839821/output.bus
Size: 7262957585
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25839821/output.unfiltered.bus
Size: 3042747057
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25839820/output.bus
Size: 12426360753
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25839820/output.unfiltered.bus
Size: 5238844817
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX22219345/output.bus
Size: 4027779505
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX22219345/output.unfiltered.bus
Size: 1530023409
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25532499/output.bus
Size: 5979531441
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25532499/output.unfiltered.bus
Size: 2353548849
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25532498/output.bus
Size: 7280570609
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25532498/output.unfiltered.bus
Size: 2758570673
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX21170825/output.bus
Size: 12218980145
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX21170825/output.unfiltered.bus
Size: 1994103985
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25982299/output.bus
Size: 2085041905
Deleting /content/drive/MyDrive/pituitary_atlas/processed/tcc/SRX25982299/output.unfiltered.bus
Size: 918697841
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX25982294/output.bus
Size: 3391856881
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX25982294/output.unfiltered.bus
Size: 1955498001
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX25982295/output.bus
Size: 2406111121
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX25982295/output.unfiltered.bus
Size: 1396300817
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX25982296/output.bus
Size: 2142949617
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX25982296/output.unfiltered.bus
Size: 1351515217
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX25982297/output.bus
Size: 2450018897
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX25982297/output.unfiltered.bus
Size: 1271227793
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX25982298/output.bus
Size: 2387372145
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX25982298/output.unfiltered.bus
Size: 1204143313
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX25982301/output.bus
Size: 2534589841
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX25982301/output.unfiltered.bus
Size: 1551575761
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX25982300/output.bus
Size: 2376738225
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX25982300/output.unfiltered.bus
Size: 1059514257
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX25982299/output.bus
Size: 2592613489
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX25982299/output.unfiltered.bus
Size: 1177691985
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX17837195/output.bus
Size: 442286641
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21170825/output.bus
Size: 13285896913
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21170825/output.unfiltered.bus
Size: 2585008657
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX17837196/output.bus
Size: 384865521
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX17837197/output.bus
Size: 552581393
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX17837198/output.bus
Size: 517479313
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX17837199/output.bus
Size: 428737361
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX17837200/output.bus
Size: 528847185
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX17837201/output.bus
Size: 541318097
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX17837202/output.bus
Size: 503348785

In [ ]:
import os

# Directory to scan
directory = '/content/drive/MyDrive/pituitary_atlas/raw'

# Walk through the directory and find all files that don't end with .fastq or .fastq.gz
for root, dirs, files in os.walk(directory):
    for file in files:
        # Check if the file does not end with .fastq or .fastq.gz
        if not (file.endswith('.fastq') or file.endswith('.fastq.gz')):

            #if it contains lite
            if 'lite' in file:
              print(f'File does not end with .fastq or .fastq.gz: {os.path.join(root, file)}')
              #print size
              print(f'Size: {os.path.getsize(os.path.join(root, file))}')
              #os.remove(os.path.join(root, file))

In [ ]:
# Directory to scan
import os
directory = '/content/drive/MyDrive/pituitary_atlas/processed'

# Walk through the directory and find all .bus files
for root, dirs, files in os.walk(directory):
    for file in files:
        if file.endswith('.bus'):
          #delete file
          print(f'Deleting {os.path.join(root, file)}')
          #print size
          print(f'Size: {os.path.getsize(os.path.join(root, file))}')
          os.remove(os.path.join(root, file))

Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/output.bus
Size: 16908264625
Deleting /content/drive/MyDrive/pituitary_atlas/processed/nac/SRX21168596/output.unfiltered.bus
Size: 7832310417

In [8]:
pip freeze

absl-py==1.4.0
accelerate==1.13.0
access==1.1.10.post3
affine==2.4.0
aiofiles==24.1.0
aiohappyeyeballs==2.6.1
aiohttp==3.13.3
aiosignal==1.4.0
aiosqlite==0.22.1
alabaster==1.0.0
albucore==0.0.24
albumentations==2.0.8
ale-py==0.11.2
alembic==1.18.4
altair==5.5.0
anndata==0.12.10
annotated-doc==0.0.4
annotated-types==0.7.0
antlr4-python3-runtime==4.9.3
anyio==4.12.1
anywidget==0.9.21
apsw==3.51.2.0
apswutils==0.1.2
argon2-cffi==25.1.0
argon2-cffi-bindings==25.1.0
array-api-compat==1.14.0
array_record==0.8.3
arrow==1.4.0
arviz==0.22.0
astropy==7.2.0
astropy-iers-data==0.2026.3.2.0.47.4
astunparse==1.6.3
atpublic==5.1
attrs==25.4.0
audioread==3.1.0
Authlib==1.6.9
autograd==1.8.0
babel==2.18.0
backcall==0.2.0
beartype==0.22.9
beautifulsoup4==4.13.5
betterproto==2.0.0b6
bigframes==2.37.0
bigquery-magics==0.10.3
biopython==1.86
bleach==6.3.0
blinker==1.9.0
blis==1.3.3
blobfile==3.2.0
blosc2==4.1.2
bokeh==3.8.2
Bottleneck==1.4.2
bqplot==0.12.45
branca==0.8.2
brotli==1.2.0
CacheControl==0.14.4
cachetools==6.2.6
catalogue==2.0.10
certifi==2026.2.25
cffi==2.0.0
chardet==5.2.0
charset-normalizer==3.4.4
clarabel==0.11.1
click==8.3.1
click-plugins==1.1.1.2
cligj==0.7.2
cloudpathlib==0.23.0
cloudpickle==3.1.2
cmake==3.31.10
cmdstanpy==1.3.0
colorcet==3.1.0
colorlover==0.3.0
colour==0.1.5
community==1.0.0b1
confection==0.1.5
cons==0.4.7
contourpy==1.3.3
cramjam==2.11.0
cryptography==43.0.3
cufflinks==0.17.3
curl_cffi==0.14.0
cvxopt==1.3.2
cvxpy==1.6.7
cycler==0.12.1
cyipopt==1.5.0
cymem==2.0.13
Cython==3.0.12
dask==2026.1.2
dataproc-spark-connect==1.0.2
datasets==4.0.0
db-dtypes==1.5.0
dbus-python==1.2.18
debugpy==1.8.15
decorator==4.4.2
defusedxml==0.7.1
deprecation==2.1.0
diffusers==0.37.0
dill==0.3.8
distro==1.9.0
dlib==19.24.6
dm-tree==0.1.9
docstring_parser==0.17.0
docutils==0.21.2
donfig==0.8.1.post1
dopamine_rl==4.1.2
duckdb==1.3.2
earthengine-api==1.5.24
easydict==1.13
editdistance==0.8.1
eerepr==0.1.2
einops==0.8.2
en_core_web_sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl#sha256=1932429db727d4bff3deed6b34cfc05df17794f4a52eeb26cf8928f7c1a0fb85
entrypoints==0.4
epitome_tools==1.0.4
esda==2.8.2
et_xmlfile==2.0.0
etils==1.14.0
etuples==0.3.10
Farama-Notifications==0.0.4
fast-array-utils==1.3.1
fastai==2.8.7
fastapi==0.135.1
fastcore==1.12.23
fastdownload==0.0.7
fastjsonschema==2.21.2
fastlite==0.2.4
fastprogress==1.1.5
fasttransform==0.0.2
ffmpy==1.0.0
ffq==0.3.1
filelock==3.25.0
fiona==1.10.1
firebase-admin==6.9.0
Flask==3.1.3
flatbuffers==25.12.19
flax==0.11.2
folium==0.20.0
fonttools==4.61.1
fqdn==1.5.1
frozendict==2.4.7
frozenlist==1.8.0
fsspec==2025.3.0
future==1.0.0
gast==0.7.0
gcsfs==2025.3.0
GDAL==3.8.4
gdown==5.2.1
geemap==0.35.3
geocoder==1.38.1
geographiclib==2.1
geopandas==1.1.2
geopy==2.4.1
giddy==2.3.8
gin-config==0.5.0
gitdb==4.0.12
GitPython==3.1.46
glob2==0.7
google==3.0.0
google-adk==1.26.0
google-ai-generativelanguage==0.6.15
google-api-core==2.30.0
google-api-python-client==2.192.0
google-auth==2.47.0
google-auth-httplib2==0.3.0
google-auth-oauthlib==1.3.0
google-cloud-aiplatform==1.140.0
google-cloud-appengine-logging==1.8.0
google-cloud-audit-log==0.4.0
google-cloud-bigquery==3.40.1
google-cloud-bigquery-connection==1.20.0
google-cloud-bigquery-storage==2.36.2
google-cloud-bigtable==2.35.0
google-cloud-core==2.5.0
google-cloud-dataproc==5.25.0
google-cloud-datastore==2.23.0
google-cloud-discoveryengine==0.13.12
google-cloud-firestore==2.23.0
google-cloud-functions==1.22.0
google-cloud-iam==2.21.0
google-cloud-language==2.19.0
google-cloud-logging==3.13.0
google-cloud-monitoring==2.29.1
google-cloud-pubsub==2.35.0
google-cloud-resource-manager==1.16.0
google-cloud-secret-manager==2.26.0
google-cloud-spanner==3.63.0
google-cloud-speech==2.37.0
google-cloud-storage==3.9.0
google-cloud-trace==1.18.0
google-cloud-translate==3.24.0
google-colab @ file:///colabtools/dist/google_colab-1.0.0.tar.gz
google-crc32c==1.8.0
google-genai==1.66.0
google-generativeai==0.8.6
google-pasta==0.2.0
google-resumable-media==2.8.0
googleapis-common-protos==1.72.0
googledrivedownloader==1.1.0
gradio==5.50.0
gradio_client==1.14.0
grain==0.2.16
graphviz==0.21
greenlet==3.3.2
groovy==0.1.2
grpc-google-iam-v1==0.14.3
grpc-interceptor==0.15.4
grpcio==1.78.0
grpcio-status==1.71.2
grpclib==0.4.9
gspread==6.2.1
gspread-dataframe==4.0.0
gym==0.25.2
gym-notices==0.1.0
gymnasium==1.2.3
h11==0.16.0
h2==4.3.0
h5netcdf==1.8.1
h5py==3.15.1
hdbscan==0.8.41
hf-xet==1.3.2
highspy==1.13.1
holidays==0.92
holoviews==1.22.1
hpack==4.1.0
html5lib==1.1
httpcore==1.0.9
httpimport==1.4.1
httplib2==0.31.2
httptools==0.7.1
httpx==0.28.1
httpx-sse==0.4.3
huggingface_hub==1.5.0
humanize==4.15.0
hyperframe==6.1.0
hyperopt==0.2.7
ibis-framework==9.5.0
idna==3.11
ImageIO==2.37.2
imageio-ffmpeg==0.6.0
imagesize==2.0.0
imbalanced-learn==0.14.1
immutabledict==4.3.1
importlib_metadata==8.7.1
importlib_resources==6.5.2
imutils==0.5.4
inequality==1.1.2
inflect==7.5.0
iniconfig==2.3.0
intel-cmplr-lib-ur==2025.3.2
intel-openmp==2025.3.2
ipyevents==2.0.4
ipyfilechooser==0.6.0
ipykernel==6.17.1
ipyleaflet==0.20.0
ipyparallel==8.8.0
ipython==7.34.0
ipython-genutils==0.2.0
ipython-sql==0.5.0
ipytree==0.2.2
ipywidgets==7.7.1
isoduration==20.11.0
itsdangerous==2.2.0
jaraco.classes==3.4.0
jaraco.context==6.1.0
jaraco.functools==4.4.0
jax==0.7.2
jaxlib==0.7.2
jeepney==0.9.0
jieba==0.42.1
Jinja2==3.1.6
jiter==0.13.0
joblib==1.5.3
jsonpatch==1.33
jsonpickle==4.1.1
jsonpointer==3.0.0
jsonschema==4.26.0
jsonschema-specifications==2025.9.1
jupyter-console==6.6.3
jupyter-events==0.12.0
jupyter-leaflet==0.20.0
jupyter_client==7.4.9
jupyter_core==5.9.1
jupyter_kernel_gateway @ git+https://github.com/googlecolab/kernel_gateway@b134e9945df25c2dcb98ade9129399be10788671
jupyter_server==2.14.0
jupyter_server_terminals==0.5.4
jupyterlab_pygments==0.3.0
jupyterlab_widgets==3.0.16
jupytext==1.19.1
kaggle==1.7.4.5
kagglehub==0.3.13
kb_python==0.29.5
keras==3.10.0
keras-hub==0.21.1
keras-nlp==0.21.1
keyring==25.7.0
keyrings.google-artifactregistry-auth==1.1.2
kiwisolver==1.4.9
langchain==1.2.10
langchain-core==1.2.17
langgraph==1.0.10
langgraph-checkpoint==4.0.1
langgraph-prebuilt==1.0.8
langgraph-sdk==0.3.9
langsmith==0.7.13
lark==1.3.1
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
lazy_loader==0.4
legacy-api-wrap==1.5
libclang==18.1.1
libpysal==4.14.1
librosa==0.11.0
lightgbm==4.6.0
linkify-it-py==2.1.0
llvmlite==0.43.0
locket==1.0.0
logical-unification==0.4.7
loompy==3.0.8
lxml==6.0.2
Mako==1.3.10
mapclassify==2.10.0
Markdown==3.10.2
markdown-it-py==4.0.0
MarkupSafe==3.0.3
matplotlib==3.10.0
matplotlib-inline==0.2.1
matplotlib-venn==1.1.2
mcp==1.26.0
mdit-py-plugins==0.5.0
mdurl==0.1.2
mgwr==2.2.1
miniKanren==1.0.5
missingno==0.5.2
mistune==3.2.0
mizani==0.13.5
mkl==2025.3.1
ml_dtypes==0.5.4
mlxtend==0.23.4
mmh3==5.2.1
momepy==0.11.0
more-itertools==10.8.0
moviepy==1.0.3
mpmath==1.3.0
msgpack==1.1.2
multidict==6.7.1
multipledispatch==1.0.0
multiprocess==0.70.16
multitasking==0.0.12
murmurhash==1.0.15
music21==9.9.1
namex==0.1.0
narwhals==2.17.0
natsort==8.4.0
nbclassic==1.3.3
nbclient==0.10.4
nbconvert==7.17.0
nbformat==5.10.4
ndindex==1.10.1
nest-asyncio==1.6.0
networkx==3.6.1
ngs-tools==1.8.6
nibabel==5.4.0
nltk==3.9.1
notebook==6.5.7
notebook_shim==0.2.4
numba==0.60.0
numcodecs==0.16.5
numexpr==2.14.1
numpy==2.0.2
numpy-groupies==0.11.3
nvidia-nccl-cu12==2.29.7
oauth2client==4.1.3
oauthlib==3.3.1
omegaconf==2.3.0
onemkl-license==2025.3.1
openai==2.26.0
opencv-contrib-python==4.13.0.92
opencv-python==4.13.0.92
opencv-python-headless==4.13.0.92
openpyxl==3.1.5
opentelemetry-api==1.38.0
opentelemetry-exporter-gcp-logging==1.11.0a0
opentelemetry-exporter-gcp-monitoring==1.11.0a0
opentelemetry-exporter-gcp-trace==1.11.0
opentelemetry-exporter-otlp-proto-common==1.38.0
opentelemetry-exporter-otlp-proto-http==1.38.0
opentelemetry-proto==1.38.0
opentelemetry-resourcedetector-gcp==1.11.0a0
opentelemetry-sdk==1.38.0
opentelemetry-semantic-conventions==0.59b0
opt_einsum==3.4.0
optax==0.2.7
optree==0.19.0
orbax-checkpoint==0.11.33
orjson==3.11.7
ormsgpack==1.12.2
osqp==1.1.1
overrides==7.7.0
packaging==26.0
pandas==2.2.2
pandas-datareader==0.10.0
pandas-gbq==0.30.0
pandas-stubs==2.2.2.240909
pandocfilters==1.5.1
panel==1.8.9
param==2.3.2
parso==0.8.6
parsy==2.2
partd==1.4.2
patsy==1.0.2
peewee==4.0.1
peft==0.18.1
pexpect==4.9.0
pickleshare==0.7.5
pillow==11.3.0
platformdirs==4.9.4
plotly==5.24.1
plotnine==0.14.5
pluggy==1.6.0
plum-dispatch==2.7.1
pointpats==2.5.5
polars==1.35.2
polars-runtime-32==1.35.2
pooch==1.9.0
portpicker==1.5.2
preshed==3.0.12
prettytable==3.17.0
proglog==0.1.12
progressbar2==4.5.0
prometheus_client==0.24.1
promise==2.3
prompt_toolkit==3.0.52
propcache==0.4.1
prophet==1.3.0
proto-plus==1.27.1
protobuf==5.29.6
psutil==5.9.5
psycopg2==2.9.11
psygnal==0.15.1
ptyprocess==0.7.0
PuLP==3.3.0
py-cpuinfo==9.0.0
py4j==0.10.9.9
pyarrow==18.1.0
pyasn1==0.6.2
pyasn1_modules==0.4.2
pycairo==1.29.0
pycocotools==2.0.11
pycparser==3.0
pycryptodomex==3.23.0
pydantic==2.12.3
pydantic-settings==2.13.1
pydantic_core==2.41.4
pydata-google-auth==1.9.1
pydot==4.0.1
pydotplus==2.0.2
PyDrive2==1.21.3
pydub==0.25.1
pyerfa==2.0.1.5
pygame==2.6.1
pygit2==1.19.1
Pygments==2.19.2
PyGObject==3.48.2
pyiceberg==0.11.1
PyJWT==2.11.0
pymc==5.28.1
pynndescent==0.6.0
pyogrio==0.12.1
pyomo==6.10.0
PyOpenGL==3.1.10
pyOpenSSL==24.2.1
pyparsing==3.3.2
pyperclip==1.11.0
pyproj==3.7.2
pyroaring==1.0.3
pysal==25.7
pysam==0.23.3
pyshp==3.0.3
PySocks==1.7.1
pyspark==4.0.2
pytensor==2.38.1
pytest==8.4.2
python-apt==0.0.0
python-box==7.4.1
python-dateutil==2.9.0.post0
python-dotenv==1.2.2
python-fasthtml==0.12.48
python-json-logger==4.0.0
python-louvain==0.16
python-multipart==0.0.22
python-slugify==8.0.4
python-snappy==0.7.3
python-utils==3.9.1
pytz==2025.2
pyviz_comms==3.0.6
PyWavelets==1.9.0
PyYAML==6.0.3
pyzmq==26.2.1
quantecon==0.11.0
rasterio==1.5.0
rasterstats==0.20.0
ratelim==0.1.6
referencing==0.37.0
regex==2025.11.3
requests==2.32.4
requests-oauthlib==2.0.0
requests-toolbelt==1.0.0
requirements-parser==0.9.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rfc3987-syntax==1.1.0
rich==13.9.4
roman-numerals==4.1.0
roman-numerals-py==4.1.0
rpds-py==0.30.0
rpy2==3.5.17
rsa==4.9.1
rtree==1.4.1
ruff==0.15.5
safehttpx==0.1.7
safetensors==0.7.0
scanpy==1.12
scikit-image==0.25.2
scikit-learn==1.6.1
scipy==1.16.3
scooby==0.11.0
scs==3.2.11
seaborn==0.13.2
SecretStorage==3.5.0
segregation==2.5.3
semantic-version==2.10.0
Send2Trash==2.1.0
sentence-transformers==5.2.3
sentencepiece==0.2.1
sentry-sdk==2.54.0
session-info2==0.4
setuptools==75.2.0
shap==0.51.0
shapely==2.1.2
shellingham==1.5.4
shortuuid==1.0.13
simple-parsing==0.1.8
simplejson==3.20.2
simsimd==6.5.15
six==1.17.0
sklearn-compat==0.1.5
sklearn-pandas==2.2.0
slicer==0.0.8
smart_open==7.5.1
smmap==5.0.2
sniffio==1.3.1
snowballstemmer==3.0.1
soundfile==0.13.1
soupsieve==2.8.3
soxr==1.0.0
spacy==3.8.11
spacy-legacy==3.0.12
spacy-loggers==1.0.5
spaghetti==1.7.6
spanner-graph-notebook==1.1.8
spglm==1.1.0
Sphinx==8.2.3
sphinxcontrib-applehelp==2.0.0
sphinxcontrib-devhelp==2.0.0
sphinxcontrib-htmlhelp==2.1.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==2.0.0
sphinxcontrib-serializinghtml==2.0.0
spint==1.0.7
splot==1.1.7
spopt==0.7.0
spreg==1.8.5
SQLAlchemy==2.0.48
sqlalchemy-spanner==1.17.2
sqlglot==25.20.2
sqlparse==0.5.5
srsly==2.5.2
sse-starlette==3.3.2
stanio==0.5.1
starlette==0.52.1
statsmodels==0.14.6
strictyaml==1.7.3
stringzilla==4.6.0
stumpy==1.13.0
sympy==1.14.0
tables==3.10.2
tabulate==0.9.0
tbb==2022.3.1
tcmlib==1.4.1
tenacity==9.1.4
tensorboard==2.19.0
tensorboard-data-server==0.7.2
tensorflow==2.19.0
tensorflow-datasets==4.9.9
tensorflow-hub==0.16.1
tensorflow-metadata==1.17.3
tensorflow-probability==0.25.0
tensorflow-text==2.19.0
tensorflow_decision_forests==1.12.0
tensorstore==0.1.81
termcolor==3.3.0
terminado==0.18.1
text-unidecode==1.3
textblob==0.19.0
tf-slim==1.1.0
tf_keras==2.19.0
thinc==8.3.10
threadpoolctl==3.6.0
tifffile==2026.3.3
tiktoken==0.12.0
timm==1.0.25
tinycss2==1.4.0
tobler==0.13.0
tokenizers==0.22.2
toml==0.10.2
tomlkit==0.13.3
toolz==0.12.1
torch @ https://download.pytorch.org/whl/cpu/torch-2.10.0%2Bcpu-cp312-cp312-manylinux_2_28_x86_64.whl
torchao==0.10.0
torchaudio @ https://download.pytorch.org/whl/cpu/torchaudio-2.10.0%2Bcpu-cp312-cp312-manylinux_2_28_x86_64.whl
torchcodec @ https://download.pytorch.org/whl/cpu/torchcodec-0.10.0-cp312-cp312-manylinux_2_28_x86_64.whl
torchdata==0.11.0
torchsummary==1.5.1
torchtune==0.6.1
torchvision @ https://download.pytorch.org/whl/cpu/torchvision-0.25.0%2Bcpu-cp312-cp312-manylinux_2_28_x86_64.whl
tornado==6.5.1
tqdm==4.67.3
traitlets==5.7.1
traittypes==0.2.3
transformers==5.0.0
treescope==0.1.10
tsfresh==0.21.1
tweepy==4.16.0
typeguard==4.5.1
typer==0.24.1
typer-slim==0.24.0
types-pytz==2026.1.1.20260304
types-setuptools==80.9.0.20251223
typing-inspection==0.4.2
typing_extensions==4.15.0
tzdata==2025.3
tzlocal==5.3.1
uc-micro-py==2.0.0
umap-learn==0.5.11
umf==1.0.3
uri-template==1.3.0
uritemplate==4.2.0
urllib3==2.5.0
uuid_utils==0.14.1
uvicorn==0.41.0
uvloop==0.22.1
vega-datasets==0.9.0
wadllib==1.3.6
wandb==0.25.0
wasabi==1.1.3
watchdog==6.0.0
watchfiles==1.1.1
wcwidth==0.6.0
weasel==0.4.3
webcolors==25.10.0
webencodings==0.5.1
websocket-client==1.9.0
websockets==15.0.1
Werkzeug==3.1.6
wheel==0.46.3
widgetsnbextension==3.6.10
wordcloud==1.9.6
wrapt==2.1.1
wurlitzer==3.1.1
xarray==2025.12.0
xarray-einstats==0.10.0
xgboost==3.2.0
xlrd==2.0.2
xxhash==3.6.0
xyzservices==2025.11.0
yarl==1.23.0
ydf==0.15.0
yellowbrick==1.5
yfinance==0.2.66
zarr==3.1.5
zipp==3.23.0
zstandard==0.25.0